<?php

/*
Generated by: Claude Code CLI

Date time: 2026/10/08 SAST

Version: 0.8.9

Description:
The design of invoices, receipts and credit notes, as ADMIN makes it on Commerce → Financial
Documents: an optional logo, a typeface, an accent colour and the closing note each document prints.
One design draws all three documents, so they always match. It is stored as it was made in each
financial template version (document_template_versions.design); FinancialDocumentDesignCompiler
turns it into the template HTML and CSS the document engine renders.

Everything else on the documents - the business and customer details, the lines, the totals, the
promotion, the payment and the refund - is data from the issued order, never part of the design.

Changelog:
2026/10/08 SAST
- Created for financial documents on the document template engine (Phase K).
*/

declare(strict_types=1);

namespace CattoLearning\Commerce\Document;

use CattoLearning\Course\Certificate\CertificateImage;
use CattoLearning\Document\DocumentType;

final class FinancialDocumentDesign
{
    /** key => [label, CSS font stack]. The Plex faces are bundled with the PDF engine; DejaVu Sans is its own. */
    public const TYPEFACES = [
        'dejavu' => ['Standard (DejaVu Sans)', '"DejaVu Sans", sans-serif'],
        'plex-sans' => ['IBM Plex Sans', '"Plex Sans", "DejaVu Sans", sans-serif'],
        'plex-serif' => ['IBM Plex Serif', '"Plex Serif", "DejaVu Serif", serif'],
    ];
    public const NOTE_LIMIT = 600;
    public const STANDARD_COLOUR = '#1F3A5F';
    public const STANDARD_NOTES = [
        'invoice' => 'Tax is not charged. An invoice is not proof of payment.',
        'receipt' => 'Thank you. This receipt confirms payment of the order above.',
        'credit_note' => 'The amount is credited to Account Funds. This document does not record a bank payout.',
    ];

    /** @param array<string,string> $notes document type value => its closing note */
    public function __construct(
        public readonly ?CertificateImage $logo,
        public readonly string $typeface,
        public readonly string $colour,
        public readonly array $notes,
    ) {}

    public static function standard(): self
    {
        return new self(null, 'dejavu', self::STANDARD_COLOUR, self::STANDARD_NOTES);
    }

    /** @return list<DocumentType> the documents one design draws, in the order they are shown */
    public static function types(): array
    {
        return [DocumentType::Invoice, DocumentType::Receipt, DocumentType::CreditNote];
    }

    public function note(DocumentType $type): string
    {
        return $this->notes[$type->value] ?? '';
    }

    public function fontStack(): string
    {
        return self::TYPEFACES[$this->typeface][1] ?? self::TYPEFACES['dejavu'][1];
    }

    /** @return list<string> what stops the design being saved, in words for the person making it */
    public function problems(): array
    {
        $problems = [];
        if (!isset(self::TYPEFACES[$this->typeface])) {
            $problems[] = 'Choose one of the typefaces offered.';
        }
        if (preg_match('/^#[0-9A-F]{6}$/D', $this->colour) !== 1) {
            $problems[] = 'Choose the accent colour with the colour picker.';
        }
        foreach (self::types() as $type) {
            if (mb_strlen($this->note($type)) > self::NOTE_LIMIT) {
                $problems[] = 'The ' . strtolower($type->label()) . ' note can be at most ' . self::NOTE_LIMIT . ' characters.';
            }
        }
        return $problems;
    }

    /** @return array{logo:?array{sha:string,width:int,height:int},typeface:string,colour:string,notes:array<string,string>} */
    public function toArray(): array
    {
        return ['logo' => $this->logo?->toArray(), 'typeface' => $this->typeface, 'colour' => $this->colour, 'notes' => $this->notes];
    }

    /** @param array<string,mixed> $row as stored; anything missing is the standard design's */
    public static function fromArray(array $row): self
    {
        $standard = self::standard();
        $notes = [];
        foreach (self::types() as $type) {
            $note = $row['notes'][$type->value] ?? null;
            $notes[$type->value] = is_string($note) ? $note : $standard->note($type);
        }
        return new self(
            CertificateImage::fromArray(is_array($row['logo'] ?? null) ? $row['logo'] : null),
            is_string($row['typeface'] ?? null) ? $row['typeface'] : $standard->typeface,
            is_string($row['colour'] ?? null) ? strtoupper($row['colour']) : $standard->colour,
            $notes,
        );
    }
}
