<?php

/*
Generated by: Claude Code CLI

Date time: 2026/10/07 SAST

Version: 0.8.8.9

Description:
Development-only fixture for certificates.cjs: an ADMIN, two learners with the names they print on
certificates, and a published course that issues certificates, with a one-question final assessment
both learners have started. It records which template is current for each document type. `cleanup`
removes the course, its enrolments and certificates and the people, makes the recorded templates
current again, and archives the templates the run created. Published versions are immutable history
and stay; the development database is disposable, and a reset removes them.

Changelog:
2026/10/07 SAST
- Created for certificates on the document template engine (Phase J).
*/

declare(strict_types=1);

use CattoLearning\Application\CliBootstrap;
use CattoLearning\Course\LearningService;
use CattoLearning\Infrastructure\Persistence\AuthSessionRepository;
use CattoLearning\Infrastructure\Persistence\Database;
use CattoLearning\Infrastructure\Persistence\RoleRepository;
use CattoLearning\Support\Token;
use CattoLearning\Tests\Support\DevelopmentFixture;

require dirname(__DIR__, 2) . '/vendor/autoload.php';

$container = CliBootstrap::boot()['container'];
$db = $container->get(Database::class);
$statePath = $argv[2] ?? '/tmp/catto-certificates-state.json';
$action = $argv[1] ?? '';
$fixture = new DevelopmentFixture($db);

$session = static function (int $id, string $email) use ($container): string {
    $token = Token::generate();
    $container->get(AuthSessionRepository::class)->create($id, Token::hash($token), 7200, '', 'Certificates browser', $email);
    return $token;
};
// One sign-in per browser context, as a person using several browsers has.
$person = static function (string $key, string $name, string $role, string $suffix, int $sessions = 1) use ($fixture, $container, $session, $db): array {
    $email = 'certificates-browser-' . $key . '-' . $suffix . '@example.test';
    $id = $fixture->createUser($name, $email);
    $db->executeStatement('UPDATE users SET certificate_name = :name WHERE id = :id', ['name' => $name, 'id' => $id]);
    $container->get(RoleRepository::class)->assign($id, $role);
    $tokens = [];
    for ($i = 0; $i < $sessions; $i++) $tokens[] = $session($id, $email);
    return ['id' => $id, 'token' => $tokens[0], 'tokens' => $tokens];
};

if ($action === 'create') {
    if (is_file($statePath)) throw new RuntimeException('Clean up the previous certificates fixture first.');
    $suffix = $fixture->suffix();
    $admin = $person('admin', 'Certificates Administrator', 'ADMIN', $suffix, 8);
    $first = $person('first', 'Lerato Browser Mokoena', 'STUDENT', $suffix);
    $second = $person('second', 'Pieter Browser van Wyk', 'STUDENT', $suffix);
    $company = $fixture->createCompany($admin['id'], 'Certificates ' . $suffix, 'certificates-' . $suffix . '.example.test');
    $slug = 'certificates-browser-' . $suffix;
    $title = 'Certificate Browser Course ' . $suffix;
    $course = $fixture->createCourse($admin['id'], $company, $slug, $title, 'published');
    $db->executeStatement("UPDATE courses SET certificate_enabled = TRUE, certificate_signatory_name = 'Dr. Browser Signatory', certificate_signatory_title = 'Head of Learning' WHERE id = :id", ['id' => $course]);
    $fixture->addGradeBands($course);
    $final = $fixture->createAssessmentItem($course, $admin['id'], 'final', 3);
    $fixture->createQuestion($final['item_id']);
    foreach ([$first, $second] as $learner) {
        $fixture->createEnrolment($learner['id'], $course, $admin['id'], 31536000);
        $container->get(LearningService::class)->start($learner['id'], $slug);
    }
    $current = $db->fetchAllAssociative('SELECT document_type, id FROM document_templates WHERE is_current');
    $state = ['suffix' => $suffix, 'slug' => $slug, 'course' => $course, 'course_title' => $title, 'company' => $company,
        'assessment' => '/learn/' . $slug . '/item/' . $final['node_id'] . '/assessment/' . $final['key'],
        'admin_id' => $admin['id'], 'admin_tokens' => $admin['tokens'],
        'first_id' => $first['id'], 'first_token' => $first['token'], 'second_id' => $second['id'], 'second_token' => $second['token'],
        'current' => array_column($current, 'id', 'document_type'), 'max_template_id' => (int) $db->fetchOne('SELECT COALESCE(MAX(id), 0) FROM document_templates')];
    file_put_contents($statePath, json_encode($state, JSON_THROW_ON_ERROR));
    chmod($statePath, 0600);
    echo "Created the certificates fixture.\n";
} elseif ($action === 'cleanup') {
    if (!is_file($statePath)) exit(0);
    $state = json_decode((string) file_get_contents($statePath), true, 512, JSON_THROW_ON_ERROR);
    if (!str_starts_with((string) $state['slug'], 'certificates-browser-')) throw new RuntimeException('Unexpected fixture course.');
    $db->beginTransaction();
    foreach ($state['current'] as $type => $id) {
        $db->executeStatement('UPDATE document_templates SET is_current = FALSE WHERE document_type = :type AND is_current', ['type' => $type]);
        $db->executeStatement('UPDATE document_templates SET is_current = TRUE WHERE id = :id', ['id' => $id]);
    }
    $db->executeStatement("DELETE FROM document_template_versions WHERE state = 'draft' AND template_id IN (SELECT id FROM document_templates WHERE id > :max OR document_type = 'certificate')", ['max' => $state['max_template_id']]);
    $db->executeStatement("UPDATE document_templates SET status = 'archived' WHERE id > :max", ['max' => $state['max_template_id']]);
    $db->executeStatement('DELETE FROM certificates WHERE enrolment_id IN (SELECT id FROM course_enrolments WHERE course_id = :c)', ['c' => $state['course']]);
    $db->executeStatement('DELETE FROM analytics_events WHERE course_id = :c', ['c' => $state['course']]);
    $db->executeStatement('DELETE FROM course_enrolments WHERE course_id = :c', ['c' => $state['course']]);
    $db->executeStatement('DELETE FROM courses WHERE id = :c', ['c' => $state['course']]);
    $db->executeStatement('DELETE FROM course_items WHERE created_by_user_id = :u', ['u' => $state['admin_id']]);
    $db->executeStatement('DELETE FROM companies WHERE id = :c', ['c' => $state['company']]);
    foreach (['admin_id', 'first_id', 'second_id'] as $key) {
        foreach (['auth_sessions', 'audit_log', 'analytics_events', 'user_roles', 'user_emails'] as $table) {
            $db->executeStatement('DELETE FROM ' . $table . ' WHERE user_id = :id', ['id' => $state[$key]]);
        }
        $db->executeStatement('DELETE FROM users WHERE id = :id', ['id' => $state[$key]]);
    }
    $db->commit();
    unlink($statePath);
    echo "Removed the certificates fixture and restored the current document templates; the run's templates are archived.\n";
} else {
    fwrite(STDERR, "Usage: php tests/Browser/certificates-fixture.php create|cleanup [state.json]\n");
    exit(1);
}
