<?php

/*
Generated by: ChatGPT

Date time: 2026/08/12 23:56 SAST

Version: 0.5.7.5.1

Description:
Provides the Fat-Free Framework SQL mapper for the course categories persistence table used by Catto Learning.

Changelog:
2026/08/12 23:56 SAST
- Updated source metadata for the Catto Learning 0.5.5 release.
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Updated source metadata for the Catto Learning 0.5.2 release.
2026/08/11 15:02 SAST
- Standardised this source file with the Catto Learning 0.5.1 SAST metadata header.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Persistence\M;

final class CourseCategoriesM extends BaseM
{
    protected function tableName(): string
    {
        return 'course_categories';
    }
}