<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/06 18:00 SAST

Version: 0.6

Description:
Immutable sort state shared by every sortable list surface. It normalises an untrusted column key
and direction from the request against the columns a dataset actually offers.

Architectural boundary: a pure value object. It holds no SQL, no PostgreSQL knowledge, no F3
template knowledge and no route knowledge. A repository maps the resolved key onto its own SQL
expression; this decides only which key is in force and which way it points.

Why a whitelist rather than an escaped column name.

A sort column arrives in the query string, and a column name interpolated into an ORDER BY is a SQL
injection whatever escaping is applied to it, because an ORDER BY takes an expression rather than a
value and no parameter binding exists for it. So the request never supplies a column: it supplies a
*key*, and the dataset supplies the map from keys to expressions. A key that is not in the map is
not rejected with an error either - it falls back to the dataset's default, because a stale
bookmark or a hand-edited URL should show the reader a list, not a failure.

Sorting never replaces the tiebreaker. A repository appends its own unique column to whatever this
resolves to, so an ordering chosen by the reader is still total and paging through it still shows
every row exactly once - see PaginationOrderingContractTest.

Changelog:
2026/09/06 18:00 SAST
- Created for the v0.6 sortable list columns.
*/

declare(strict_types=1);

namespace CattoLearning\Support;

final class SortOrder
{
    public const ASCENDING = 'asc';
    public const DESCENDING = 'desc';

    /** The key in force, always one the dataset offers. */
    public readonly string $key;

    public readonly string $direction;

    private function __construct(string $key, string $direction)
    {
        $this->key = $key;
        $this->direction = $direction;
    }

    /**
     * Resolves a requested sort against the keys a dataset offers.
     *
     * @param list<string> $allowed     The dataset's sortable keys.
     * @param string       $defaultKey  Used when the request names nothing, or names something unknown.
     */
    public static function create(mixed $key, mixed $direction, array $allowed, string $defaultKey, string $defaultDirection = self::ASCENDING): self
    {
        $requested = is_string($key) ? trim($key) : '';
        $resolved = in_array($requested, $allowed, true) ? $requested : $defaultKey;

        // The direction is only honoured for a key that was actually recognised. Carrying a
        // direction over from a rejected key would silently reverse the default ordering, which
        // reads as the list having reordered itself for no reason.
        $requestedDirection = is_string($direction) ? strtolower(trim($direction)) : '';
        $resolvedDirection = $resolved === $requested && in_array($requestedDirection, [self::ASCENDING, self::DESCENDING], true)
            ? $requestedDirection
            : $defaultDirection;

        return new self($resolved, $resolvedDirection);
    }

    public function isDescending(): bool
    {
        return $this->direction === self::DESCENDING;
    }

    /** Whether this is the column currently in force. */
    public function isOn(string $key): bool
    {
        return $this->key === $key;
    }

    /**
     * The direction a header link should request.
     *
     * Clicking the column already in force reverses it; clicking any other column starts it in the
     * direction that column reads best. A name starts A to Z and a date starts newest first, which
     * is what a reader expects without having to click twice to find out.
     */
    public function nextDirectionFor(string $key, string $naturalDirection = self::ASCENDING): string
    {
        if (!$this->isOn($key)) {
            return $naturalDirection;
        }

        return $this->isDescending() ? self::ASCENDING : self::DESCENDING;
    }

    /** `ASC` or `DESC`, for a repository composing an ORDER BY around a whitelisted expression. */
    public function sql(): string
    {
        return $this->isDescending() ? 'DESC' : 'ASC';
    }

    /**
     * The scalars a view needs, prefixed per dataset so several lists can sort independently on
     * one route.
     *
     * @return array<string,string>
     */
    public function toPrefixedArray(string $prefix): array
    {
        return [
            $prefix . '_sort' => $this->key,
            $prefix . '_dir' => $this->direction,
        ];
    }
}
