<?php

/*
Generated by: Claude Code CLI

Date time: 2026/08/24 20:30 SAST

Version: 0.5.8.2

Description:
Keeps the test-suite loadability guard wired into the gate.

The instruction for this round asked for an Architecture test that fails when a test class
overrides a final PHPUnit method. That cannot work, and the reason is worth stating rather than
quietly substituting something else:

PHPUnit builds every suite named in phpunit.xml before executing anything, even when `--testsuite`
narrows what will actually run. A class that cannot be declared therefore kills the process during
suite construction, before any test executes. Verified directly: with a deliberate offender placed
in tests/Integration, `--testsuite Architecture --testdox` produced no test output at all, only the
fatal. **A PHPUnit test cannot guard against a class that stops PHPUnit from starting.**

So the real guard is `tools/check-test-suite.php`, a source scan that never loads a class and
therefore survives one that cannot be loaded. It runs inside `composer qa` beside the other
tools/check-*.php gates.

What this test does is make that protection permanent: it asserts the tool exists, still checks
the thing it was written to check, and is still wired into the qa script. Without this, the tool
could be dropped from the gate and nothing would notice until the next fatal on the VPS.

Changelog:
2026/08/24 20:30 SAST
- Narrowed the no-loading assertion to discovered classes. It forbade class_exists() outright, which also blocked the guard from checking whether PHPUnit is installed at all.
2026/08/24 17:45 SAST
- Created after the final-method collision reached the VPS, to pin the guard into the gate.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Architecture;

use PHPUnit\Framework\Assert;
use PHPUnit\Framework\TestCase;
use ReflectionClass;

final class TestSuiteLoadabilityTest extends TestCase
{
    private static function root(): string
    {
        return dirname(__DIR__, 2);
    }

    private static function read(string $relative): string
    {
        return (string) file_get_contents(self::root() . '/' . $relative);
    }

    /** The guard exists and still checks for final-method collisions. */
    public function testTheLoadabilityGuardExists(): void
    {
        $tool = self::root() . '/tools/check-test-suite.php';
        self::assertFileExists($tool, 'tools/check-test-suite.php is the only guard that survives an unloadable class.');

        $source = (string) file_get_contents($tool);
        self::assertStringContainsString('isFinal()', $source, 'The guard must read the final methods from PHPUnit itself.');
        self::assertStringContainsString('extends\s+TestCase', $source, 'The guard must scope itself to TestCase subclasses.');
        self::assertStringContainsString('exit(1)', $source, 'The guard must fail the build rather than only reporting.');
    }

    /**
     * The guard never loads a class it discovered.
     *
     * This is the property that makes it work at all: loading a discovered test class triggers the
     * very fatal it exists to report.
     */
    public function testTheGuardNeverLoadsATestClass(): void
    {
        $source = self::read('tools/check-test-suite.php');

        // The distinction is between a *discovered* class and a *known framework* class. Loading a
        // discovered one triggers the fatal this guard exists to report; asking whether PHPUnit
        // itself is installed does not, and is worth doing. A discovered class name is always in a
        // variable, so that is what is forbidden here rather than the function outright.
        foreach (['class_exists($', 'new ReflectionClass($candidate', 'require_once $file'] as $forbidden) {
            self::assertStringNotContainsString(
                $forbidden,
                $source,
                'The guard must not load a class it discovered; loading one is the fatal it exists to report.'
            );
        }

        self::assertStringNotContainsString(
            'RecursiveDirectoryIterator($root)',
            $source,
            'The guard reads test sources; it must not walk and include them.'
        );
    }

    /** The guard is part of the authoritative gate, not an optional extra. */
    public function testTheGuardIsWiredIntoTheQaGate(): void
    {
        $composer = (array) json_decode(self::read('composer.json'), true);
        $scripts = (array) ($composer['scripts'] ?? []);

        self::assertArrayHasKey('test-suite:check', $scripts, 'The guard needs its own composer script.');
        self::assertStringContainsString('tools/check-test-suite.php', (string) $scripts['test-suite:check']);

        $qa = $scripts['qa'] ?? '';
        $qa = is_array($qa) ? implode(' ', $qa) : (string) $qa;
        self::assertStringContainsString(
            'test-suite:check',
            $qa,
            'composer qa must run the loadability guard, or an unloadable class reaches the VPS again.'
        );
    }

    /**
     * PHPUnit still marks methods final, so the guard has something to check.
     *
     * If a future PHPUnit stopped finalising its API this guard would pass vacuously, which is the
     * quiet failure mode worth catching.
     */
    public function testPhpunitStillFinalisesItsApi(): void
    {
        $final = [];
        foreach ([TestCase::class, Assert::class] as $frameworkClass) {
            foreach ((new ReflectionClass($frameworkClass))->getMethods() as $method) {
                if ($method->isFinal() && !$method->isPrivate()) {
                    $final[] = $method->getName();
                }
            }
        }

        self::assertContains('count', $final, 'TestCase::count() is the collision that caused this guard to exist.');
        self::assertGreaterThan(50, count(array_unique($final)));
    }
}
