<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/09 05:00 SAST

Version: 0.7

Description:
The colours generated artwork is allowed to use.

Architectural boundary: presentation data. It holds no logic beyond picking a set from a number.

Twelve sets, each a deep base, a lighter partner and an accent that reads on both. They are chosen
rather than computed: a hue picked at random from the whole wheel produces the muddy yellow-greens
and the fluorescent magentas that make procedural artwork look procedural, and no amount of
saturation clamping fixes that. Twelve is enough that a catalogue page does not look like one
palette, and few enough that every one of them was actually looked at.

Every set carries an `ink` that meets contrast against its own base, so a monogram drawn on the
artwork is legible without the caller reasoning about luminance.

Changelog:
2026/09/09 05:00 SAST
- Created with generated course, category and tag artwork.
*/

declare(strict_types=1);

namespace CattoLearning\View\Artwork;

final class ArtworkPalette
{
    /** @var list<array{base:string,tint:string,accent:string,ink:string}> */
    private const SETS = [
        ['base' => '#1f3a5f', 'tint' => '#2e5c8a', 'accent' => '#f2b134', 'ink' => '#f7fafc'],
        ['base' => '#14532d', 'tint' => '#2f7a4d', 'accent' => '#d9f99d', 'ink' => '#f7fafc'],
        ['base' => '#4c1d3d', 'tint' => '#7c3a63', 'accent' => '#f6a5c0', 'ink' => '#fdf2f8'],
        ['base' => '#0f3d3e', 'tint' => '#1d6b6d', 'accent' => '#7fd1cc', 'ink' => '#f0fdfa'],
        ['base' => '#432818', 'tint' => '#6f4322', 'accent' => '#e8b04b', 'ink' => '#fefaf3'],
        ['base' => '#1e1b4b', 'tint' => '#3c357f', 'accent' => '#a5b4fc', 'ink' => '#f5f3ff'],
        ['base' => '#3f1d1d', 'tint' => '#6d3232', 'accent' => '#f0a58f', 'ink' => '#fff5f2'],
        ['base' => '#0c4a6e', 'tint' => '#1e7aa8', 'accent' => '#7dd3fc', 'ink' => '#f0f9ff'],
        ['base' => '#3b2f0b', 'tint' => '#6b5514', 'accent' => '#facc15', 'ink' => '#fefce8'],
        ['base' => '#2d3142', 'tint' => '#4f5568', 'accent' => '#bfc0c0', 'ink' => '#f7f7f7'],
        ['base' => '#4a1942', 'tint' => '#7a2f6d', 'accent' => '#e0aaff', 'ink' => '#faf5ff'],
        ['base' => '#173b2b', 'tint' => '#2c6b4f', 'accent' => '#9ae6b4', 'ink' => '#f0fff4'],
    ];

    /** @return array{base:string,tint:string,accent:string,ink:string} */
    public static function forNumber(int $number): array
    {
        return self::SETS[$number % count(self::SETS)];
    }

    public static function count(): int
    {
        return count(self::SETS);
    }
}
