<?php

/*
Generated by: Claude Code CLI

Date time: 2026/10/07 SAST

Version: 0.8.8.10

Description:
Issued certificates: the identity minted once per enrolment, and the data and template version each
issue is drawn from.

Changelog:
2026/10/07 SAST
- Certificate designs: the issue context reads the course title and its accreditation line instead of the course certificate wording.
2026/10/07 SAST
- Created for certificates on the document template engine (Phase J).
*/

declare(strict_types=1);

namespace CattoLearning\Course\Certificate;

use CattoLearning\Infrastructure\Persistence\Database;
use DateTimeImmutable;
use JsonException;
use RuntimeException;

final class CertificateRepository
{
    public function __construct(private readonly Database $db) {}

    /**
     * Everything an enrolment's certificate is filled with at issue: the learner's names, the
     * course's title and accreditation line, and the result when there is one.
     *
     * @return array<string,mixed>|null
     */
    public function issueContext(int $enrolmentId): ?array
    {
        $row = $this->db->fetchAssociative(
            'SELECT ce.course_id, ce.completed_at, u.certificate_name, u.display_name,
                    (SELECT ue.email FROM user_emails ue WHERE ue.user_id = u.id AND ue.is_primary LIMIT 1) AS email,
                    c.title, c.certificate_accreditation,
                    cr.overall_percentage, cr.grade_code
               FROM course_enrolments ce
               JOIN users u ON u.id = ce.user_id
               JOIN courses c ON c.id = ce.course_id
               LEFT JOIN course_results cr ON cr.enrolment_id = ce.id
              WHERE ce.id = :id',
            ['id' => $enrolmentId]
        );
        return $row === false ? null : $row;
    }

    /** @return array{public_id:string,certificate_number:string}|null */
    public function identityForEnrolment(int $enrolmentId): ?array
    {
        $row = $this->db->fetchAssociative('SELECT public_id, certificate_number FROM certificates WHERE enrolment_id = :id FOR UPDATE', ['id' => $enrolmentId]);
        return $row === false ? null : ['public_id' => (string) $row['public_id'], 'certificate_number' => (string) $row['certificate_number']];
    }

    /**
     * Records an issue. A reissue keeps the row's identity and replaces what it was issued with.
     *
     * @param array<string,mixed> $data the certificate placeholders exactly as rendered
     * @param array{document_type:string,template_id:?int,template_version_id:?int,template_version_number:?int} $reference
     * @return array<string,mixed>
     */
    public function store(int $enrolmentId, string $publicId, string $number, array $data, array $reference, DateTimeImmutable $issuedAt): array
    {
        if ($reference['template_id'] === null || $reference['template_version_id'] === null || $reference['template_version_number'] === null) {
            throw new RuntimeException('A certificate must name the template version it was rendered with.');
        }
        try {
            $json = json_encode($data, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        } catch (JsonException $invalid) {
            throw new RuntimeException('The certificate data could not be stored.', 0, $invalid);
        }
        $this->db->executeStatement(
            'INSERT INTO certificates (public_id, enrolment_id, certificate_number, learner_name, course_title, grade_code, overall_percentage,
                    document_data, template_id, template_version_id, template_version_number, issued_at)
             VALUES (:public_id, :enrolment_id, :number, :learner, :course, :grade, :percentage,
                    CAST(:data AS JSONB), :template, :version, :version_number, :issued_at)
             ON CONFLICT (enrolment_id) DO UPDATE SET
                    learner_name = EXCLUDED.learner_name, course_title = EXCLUDED.course_title, grade_code = EXCLUDED.grade_code,
                    overall_percentage = EXCLUDED.overall_percentage, document_data = EXCLUDED.document_data,
                    template_id = EXCLUDED.template_id, template_version_id = EXCLUDED.template_version_id,
                    template_version_number = EXCLUDED.template_version_number, issued_at = EXCLUDED.issued_at,
                    revoked_at = NULL, revocation_reason = NULL',
            [
                'public_id' => $publicId, 'enrolment_id' => $enrolmentId, 'number' => $number,
                'learner' => mb_substr((string) $data['learner.name'], 0, 240), 'course' => mb_substr((string) $data['course.title'], 0, 240),
                'grade' => $data['result.grade'] ?? null, 'percentage' => $data['result.percentage'] ?? null,
                'data' => $json, 'template' => $reference['template_id'], 'version' => $reference['template_version_id'],
                'version_number' => $reference['template_version_number'], 'issued_at' => $issuedAt->format(DATE_ATOM),
            ]
        );
        return $this->forEnrolment($enrolmentId) ?? throw new RuntimeException('The certificate could not be stored.');
    }

    /** @return array<string,mixed>|null */
    public function forEnrolment(int $enrolmentId): ?array
    {
        return $this->one('cert.enrolment_id = :key', $enrolmentId);
    }

    /**
     * The certificate behind a public verification address, revoked or not.
     *
     * @return array<string,mixed>|null
     */
    public function byPublicId(string $publicId): ?array
    {
        if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i', $publicId) !== 1) {
            return null;
        }
        return $this->one('cert.public_id = :key', $publicId);
    }

    /** How many certificates were issued with a template version. */
    public function countForVersion(int $versionId): int
    {
        return (int) $this->db->fetchOne('SELECT COUNT(*) FROM certificates WHERE template_version_id = :id', ['id' => $versionId]);
    }

    /** @return array<string,mixed>|null */
    private function one(string $where, int|string $key): ?array
    {
        $row = $this->db->fetchAssociative(
            'SELECT cert.*, c.slug AS course_slug, t.name AS template_name, ce.user_id
               FROM certificates cert
               JOIN course_enrolments ce ON ce.id = cert.enrolment_id
               JOIN courses c ON c.id = ce.course_id
               JOIN document_templates t ON t.id = cert.template_id
              WHERE ' . $where,
            ['key' => $key]
        );
        if ($row === false) {
            return null;
        }
        $row['document_data'] = json_decode((string) $row['document_data'], true, 512, JSON_THROW_ON_ERROR);
        return $row;
    }
}
