<?php

/*
Generated by: ChatGPT

Date time: 2026/08/17 00:02 SAST

Version: 0.5.7.5

Description:
Protects practice-vs-graded assessment semantics, attempt limits, module completion, final assessment calculation and learner course completion.

Changelog:
2026/08/17 01:03 SAST
- Isolated F3 process-wide error handling from PHPUnit and restore F3 handlers after the assessment workflow test.
2026/08/17 00:02 SAST
- Added end-to-end assessment workflow characterisation tests for the stabilisation phase.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Integration;

use CattoLearning\Application\CliBootstrap;
use CattoLearning\Course\AssessmentService;
use CattoLearning\Course\LearningService;
use CattoLearning\Tests\Support\DevelopmentFixture;
use DB\SQL;
use InvalidArgumentException;
use PHPUnit\Framework\Attributes\WithoutErrorHandler;
use PHPUnit\Framework\TestCase;

final class AssessmentWorkflowRegressionTest extends TestCase
{
    #[WithoutErrorHandler]
    public function testPracticeDoesNotCountButGradedModuleAndFinalCompleteCourse(): void
    {
        $container = CliBootstrap::boot()['container'];
        /** @var SQL $db */
        $db = $container->get(SQL::class);
        /** @var LearningService $learning */
        $learning = $container->get(LearningService::class);
        /** @var AssessmentService $assessments */
        $assessments = $container->get(AssessmentService::class);
        $fixture = new DevelopmentFixture($db);
        $suffix = $fixture->suffix();

        try {
            $adminId = $fixture->createUser('QA assess admin ' . $suffix);
            $learnerId = $fixture->createUser('QA assess learner ' . $suffix, 'qa-assess-' . $suffix . '@example.test');
            $companyId = $fixture->createCompany($adminId, 'QA Assess ' . $suffix, 'qa-assess-' . $suffix . '.example.test');
            $slug = 'qa-assess-' . $suffix;
            $courseId = $fixture->createCourse($adminId, $companyId, $slug, 'QA Assessment Course ' . $suffix, 'published');
            $fixture->addGradeBands($courseId);
            $moduleId = $fixture->createModule($courseId, 'm1', 1, true);
            $moduleAssessmentId = $fixture->createAssessment($courseId, $moduleId, 'module', 'Module assessment', null, 1);
            $moduleQuestion = $fixture->createQuestion($moduleAssessmentId);
            $finalAssessmentId = $fixture->createAssessment($courseId, null, 'final', 'Final assessment', null, 1);
            $finalQuestion = $fixture->createQuestion($finalAssessmentId);
            $enrolmentId = $fixture->createEnrolment($learnerId, $courseId, $adminId, 2592000);
            $learning->start($learnerId, $slug);

            $practice = $assessments->startModuleAttempt($learnerId, $slug, 1, 'practice');
            $practiceResult = $assessments->respond(
                $learnerId,
                (string) $practice['public_id'],
                $moduleQuestion['question_id'],
                $moduleQuestion['correct_option_id'],
                false
            );
            self::assertSame('submitted', (string) $practiceResult['status']);
            self::assertSame('practice', (string) $practiceResult['attempt_mode']);
            self::assertSame(100.0, (float) $practiceResult['percentage']);

            $attemptCount = $db->exec(
                'SELECT COUNT(*)::int AS total FROM assessment_attempts WHERE enrolment_id=:enrolment_id AND assessment_id=:assessment_id',
                [':enrolment_id' => $enrolmentId, ':assessment_id' => $moduleAssessmentId]
            );
            self::assertSame(0, (int) $attemptCount[0]['total']);
            $progress = $db->exec(
                'SELECT completed_at,best_percentage FROM module_progress WHERE enrolment_id=:enrolment_id AND module_id=:module_id',
                [':enrolment_id' => $enrolmentId, ':module_id' => $moduleId]
            );
            self::assertSame([], $progress);

            $graded = $assessments->startModuleAttempt($learnerId, $slug, 1, 'graded');
            $gradedResult = $assessments->respond(
                $learnerId,
                (string) $graded['public_id'],
                $moduleQuestion['question_id'],
                $moduleQuestion['correct_option_id'],
                false
            );
            self::assertSame('submitted', (string) $gradedResult['status']);
            self::assertSame(100.0, (float) $gradedResult['percentage']);

            $attempt = $db->exec(
                'SELECT percentage,passed FROM assessment_attempts WHERE enrolment_id=:enrolment_id AND assessment_id=:assessment_id',
                [':enrolment_id' => $enrolmentId, ':assessment_id' => $moduleAssessmentId]
            );
            self::assertCount(1, $attempt);
            self::assertSame(100.0, (float) $attempt[0]['percentage']);
            self::assertContains($attempt[0]['passed'], [true, 1, '1', 't', 'true']);

            $progress = $db->exec(
                'SELECT completed_at,best_percentage FROM module_progress WHERE enrolment_id=:enrolment_id AND module_id=:module_id',
                [':enrolment_id' => $enrolmentId, ':module_id' => $moduleId]
            );
            self::assertCount(1, $progress);
            self::assertNotSame('', trim((string) $progress[0]['completed_at']));
            self::assertSame(100.0, (float) $progress[0]['best_percentage']);

            try {
                $assessments->startModuleAttempt($learnerId, $slug, 1, 'graded');
                self::fail('Expected maximum graded-attempt limit to be enforced.');
            } catch (InvalidArgumentException $e) {
                self::assertSame('No graded assessment attempts remain.', $e->getMessage());
            }

            $final = $assessments->startFinalAttempt($learnerId, $slug, 'graded');
            $finalResult = $assessments->respond(
                $learnerId,
                (string) $final['public_id'],
                $finalQuestion['question_id'],
                $finalQuestion['correct_option_id'],
                false
            );
            self::assertSame(100.0, (float) $finalResult['percentage']);

            $result = $db->exec(
                'SELECT module_percentage,final_percentage,overall_percentage,grade_code,passed FROM course_results WHERE enrolment_id=:id',
                [':id' => $enrolmentId]
            );
            self::assertCount(1, $result);
            self::assertSame(100.0, (float) $result[0]['module_percentage']);
            self::assertSame(100.0, (float) $result[0]['final_percentage']);
            self::assertSame(100.0, (float) $result[0]['overall_percentage']);
            self::assertSame('Distinction', (string) $result[0]['grade_code']);
            self::assertContains($result[0]['passed'], [true, 1, '1', 't', 'true']);

            $enrolment = $db->exec('SELECT status,completed_at FROM course_enrolments WHERE id=:id', [':id' => $enrolmentId])[0];
            self::assertSame('completed', (string) $enrolment['status']);
            self::assertNotSame('', trim((string) $enrolment['completed_at']));
        } finally {
            $fixture->cleanup();
            // F3 installs process-wide error and exception handlers when Base is resolved.
            // This test disables PHPUnit's error handler and restores F3's handlers explicitly.
            restore_error_handler();
            restore_exception_handler();
        }
    }
}