<?php

/*
Generated by: Claude Code CLI

Date time: 2026/10/07 SAST

Version: 0.8.8.13

Description:
Importing a course that is already on the site. Its Course Items collide with the copy imported
before, so it cannot become a second course; the review says the course is already there, chooses
it under Replace existing course shell, and lists no key as a problem; a commit that would create a
second copy says so in one sentence; replacing the course imports cleanly. A conflict of any other
kind is not mistaken for a course to replace.

Every test runs inside a transaction that is rolled back.

Changelog:
2026/10/07 SAST
- Created after the owner's second import of a course listed 26 "Resolve the collision" warnings
  without saying the course was already on catto.test or that Replace would import it.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Integration;

use CattoLearning\Auth\CurrentUser;
use CattoLearning\Auth\PermissionCatalog;
use CattoLearning\Course\CoursePortabilityService;
use CattoLearning\Http\Controller\AdminCourseController;
use CattoLearning\Infrastructure\Persistence\Database;
use CattoLearning\Support\Uuid;
use CattoLearning\Tests\Support\InProcessPage;
use CattoLearning\Tests\Support\IntegrationContainer;
use CattoLearning\Tests\Support\IntegrationDataFixture;
use PHPUnit\Framework\TestCase;

final class ImportReplacementIntegrationTest extends TestCase
{
    private Database $db;
    private CoursePortabilityService $portability;
    private CurrentUser $admin;
    private int $userId = 0;
    private string $suffix = '';

    protected function setUp(): void
    {
        $this->db = IntegrationContainer::db();
        $this->db->beginTransaction();
        $fixture = new IntegrationDataFixture($this->db);
        $this->portability = IntegrationContainer::get()->get(CoursePortabilityService::class);
        $this->suffix = $fixture->suffix();
        $this->userId = $fixture->createUser('Import test ' . $this->suffix, 'import-test-' . $this->suffix . '@seed.test');
        $this->admin = new CurrentUser($this->userId, Uuid::v4(), 'import-test@seed.test', 'Import test', ['ADMIN'], (new PermissionCatalog())->keys(), Uuid::v4());
    }

    protected function tearDown(): void
    {
        if ($this->db->isTransactionActive()) $this->db->rollBack();
        unset($_SESSION['flash']);
    }

    public function testACourseImportedAgainIsOfferedForReplacementAndReplacesCleanly(): void
    {
        $title = 'Replacement import ' . $this->suffix;
        $first = $this->portability->commitImport((string) $this->stage($title)['import_key'], 0, $this->userId);

        $again = $this->stage($title);
        self::assertNotSame([], $again['key_conflicts'], 'The second import collides with the first one\'s Course Items.');
        self::assertSame($first, $this->portability->courseHoldingConflicts($again), 'Every collision belongs to the course imported before.');

        $page = InProcessPage::run($this->admin, AdminCourseController::class, 'previewImport', [], null, ['key' => (string) $again['import_key']]);
        self::assertSame(200, $page['status']);
        self::assertStringContainsString('This course is already on the site', $page['body']);
        self::assertStringNotContainsString('Course Item key already exists', $page['body'], 'No key is listed as a problem to resolve.');
        $document = new \DOMDocument();
        @$document->loadHTML('<?xml encoding="UTF-8"><body>' . $page['body'] . '</body>');
        self::assertSame(1, (new \DOMXPath($document))->query('//select[@name="replace_course_id"]/option[@value="' . $first . '" and @selected]')->length, 'The course is chosen under Replace.');

        try {
            $this->portability->commitImport((string) $again['import_key'], 0, $this->userId);
            self::fail('A second copy of the course was created.');
        } catch (\InvalidArgumentException $refused) {
            self::assertSame('This course is already on the site as “' . $title . '”. To update it, choose it under Replace existing course shell and import again.', $refused->getMessage());
        }
        self::assertSame($first, $this->portability->commitImport((string) $again['import_key'], 0, $this->userId, $first), 'Replacing the course imports cleanly.');
    }

    public function testOtherConflictsAreNotMistakenForACourseToReplace(): void
    {
        self::assertNull($this->portability->courseHoldingConflicts(['key_conflicts' => []]));
        self::assertNull($this->portability->courseHoldingConflicts(['key_conflicts' => ['Invalid Course Item key: bad key.']]));
        self::assertNull($this->portability->courseHoldingConflicts(['key_conflicts' => ['Course Item key already exists: no-such-key-' . $this->suffix . '. Resolve the collision before importing.']]), 'A key no course places names no course.');
    }

    /** @return array<string,mixed> */
    private function stage(string $title): array
    {
        $temporary = (string) tempnam(sys_get_temp_dir(), 'replacement-import-');
        file_put_contents($temporary, json_encode(['course' => ['slug' => 'replacement-import-' . $this->suffix, 'title' => $title], 'modules' => [['title' => 'Only module', 'module_key' => 'm1', 'assessment_required' => false, 'content_html' => '<p>Hello</p>']]], JSON_THROW_ON_ERROR));
        try {
            return $this->portability->stageImport(['error' => UPLOAD_ERR_OK, 'size' => filesize($temporary), 'tmp_name' => $temporary, 'name' => 'replacement.json'], $this->userId);
        } finally {
            @unlink($temporary);
        }
    }
}
