<?php

/*
Generated by: ChatGPT

Date time: 2026/08/12 02:45 SAST

Version: 0.5.4

Description:
Provides PostgreSQL persistence queries and data-access operations for administration records.

Changelog:
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Updated source metadata for the Catto Learning 0.5.2 release.
2026/08/11 15:02 SAST
- Standardised this source file with the Catto Learning 0.5.1 SAST metadata header.
- Added Activity Centre incremental event filtering.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Persistence;

use CattoLearning\Infrastructure\Persistence\M\CourseCreditAllocationsM;
use CattoLearning\Infrastructure\Persistence\M\CourseCreditsM;
use CattoLearning\Infrastructure\Persistence\M\CourseEnrolmentsM;
use CattoLearning\Infrastructure\Persistence\M\CourseRequestsM;
use CattoLearning\Support\Uuid;
use DB\SQL;
use RuntimeException;

final class AdministrationRepository
{
    public function __construct(private readonly SQL $db)
    {
    }

    /** @return array<string,int|float> */
    public function overview(): array
    {
        $rows = $this->db->exec(<<<'SQL'
SELECT
 (SELECT COUNT(*) FROM users WHERE status='active')::int AS people,
 (SELECT COUNT(*) FROM courses WHERE status='published')::int AS published_courses,
 (SELECT COUNT(*) FROM courses WHERE status='draft')::int AS draft_courses,
 (SELECT COUNT(*) FROM companies WHERE status='active')::int AS companies,
 (SELECT COUNT(*) FROM course_requests WHERE status='pending')::int AS pending_requests,
 (SELECT COUNT(*) FROM course_enrolments WHERE status IN ('assigned','active','completed') AND is_preview=FALSE)::int AS enrolments,
 (SELECT COUNT(*) FROM course_enrolments WHERE status='completed' AND is_preview=FALSE)::int AS completed
SQL);
        $row = $rows[0] ?? [];
        $enrolments = max(0, (int) ($row['enrolments'] ?? 0));
        $completed = max(0, (int) ($row['completed'] ?? 0));
        return [
            'people' => (int) ($row['people'] ?? 0),
            'published_courses' => (int) ($row['published_courses'] ?? 0),
            'draft_courses' => (int) ($row['draft_courses'] ?? 0),
            'companies' => (int) ($row['companies'] ?? 0),
            'pending_requests' => (int) ($row['pending_requests'] ?? 0),
            'enrolments' => $enrolments,
            'completion_rate' => $enrolments > 0 ? round($completed / $enrolments * 100, 1) : 0.0,
        ];
    }

    /** @return list<array<string,mixed>> */
    public function people(int $limit = 250): array
    {
        $limit = max(1, min(1000, $limit));

        $sql = <<<'SQL'
SELECT
    u.id,
    u.public_id,
    u.first_name,
    u.last_name,
    u.display_name,
    u.status,
    u.last_login_at,
    ue.email,
    c.id AS company_id,
    c.name AS company_name,
    COALESCE(string_agg(DISTINCT r.role_key, ',' ORDER BY r.role_key), '') AS role_keys,
    COUNT(DISTINCT ce.id) FILTER (WHERE ce.status IN ('assigned','active','completed'))::int AS course_count
FROM users u
JOIN user_emails ue ON ue.user_id = u.id AND ue.is_primary = TRUE
LEFT JOIN company_users cu ON cu.user_id = u.id AND cu.status = 'active'
LEFT JOIN companies c ON c.id = cu.company_id
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
LEFT JOIN course_enrolments ce ON ce.user_id = u.id AND ce.is_preview = FALSE
GROUP BY u.id, ue.email, c.id, c.name
ORDER BY COALESCE(NULLIF(trim(concat_ws(' ', u.first_name, u.last_name)), ''), u.display_name, ue.email)
SQL;

        return $this->db->exec($sql . ' LIMIT ' . $limit);
    }

    /** @return list<array<string,mixed>> */
    public function companies(): array
    {
        return $this->db->exec(
            'SELECT c.*,
                    COUNT(DISTINCT cu.user_id) FILTER (WHERE cu.status=\'active\')::int AS people_count,
                    COUNT(DISTINCT co.id)::int AS owned_course_count,
                    COUNT(DISTINCT ce.id) FILTER (WHERE ce.status IN (\'assigned\',\'active\',\'completed\'))::int AS enrolment_count
             FROM companies c
             LEFT JOIN company_users cu ON cu.company_id=c.id
             LEFT JOIN courses co ON co.owner_company_id=c.id
             LEFT JOIN company_users learner_cu ON learner_cu.company_id=c.id AND learner_cu.status=\'active\'
             LEFT JOIN course_enrolments ce ON ce.user_id=learner_cu.user_id AND ce.is_preview=FALSE
             GROUP BY c.id
             ORDER BY c.is_system DESC, c.name'
        );
    }

    /** @return list<array<string,mixed>> */
    public function enrolments(): array
    {
        return $this->db->exec(
            'SELECT ce.id, ce.public_id, ce.status, ce.assigned_at, ce.started_at, ce.expires_at, ce.completed_at,
                    ce.access_removed_at, ce.access_removed_reason,
                    c.id AS course_id, c.title AS course_title, c.slug,
                    u.id AS user_id, COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS learner_name,
                    ue.email,
                    COALESCE((SELECT COUNT(*) FROM module_progress mp WHERE mp.enrolment_id=ce.id AND mp.completed_at IS NOT NULL),0)::int AS modules_completed,
                    COALESCE((SELECT COUNT(*) FROM course_modules cm WHERE cm.course_id=ce.course_id),0)::int AS module_count
             FROM course_enrolments ce
             JOIN courses c ON c.id=ce.course_id
             JOIN users u ON u.id=ce.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE ce.is_preview=FALSE
             ORDER BY ce.updated_at DESC, ce.assigned_at DESC
             LIMIT 500'
        );
    }

    /** @return list<array<string,mixed>> */
    public function requests(): array
    {
        return $this->db->exec(
            'SELECT cr.*, c.title AS course_title, c.slug,
                    COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS learner_name,
                    ue.email, co.name AS company_name
             FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             JOIN users u ON u.id=cr.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             LEFT JOIN companies co ON co.id=cr.company_id
             ORDER BY CASE cr.status WHEN \'pending\' THEN 0 WHEN \'approved\' THEN 1 ELSE 2 END, cr.requested_at DESC
             LIMIT 500'
        );
    }

    /** @return list<array<string,mixed>> */
    public function creditLedger(): array
    {
        return $this->db->exec(
            'SELECT cc.id, cc.public_id, cc.company_id, cc.user_id, cc.course_id, cc.access_period_seconds,
                    cc.quantity, cc.source_type, cc.note, cc.created_at,
                    c.title AS course_title,
                    COALESCE(co.name, NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS holder_name,
                    COUNT(cca.id) FILTER (WHERE cca.status=\'assigned\')::int AS assigned_count,
                    COUNT(cca.id) FILTER (WHERE cca.status=\'consumed\')::int AS consumed_count,
                    GREATEST(cc.quantity - COUNT(cca.id) FILTER (WHERE cca.status IN (\'assigned\',\'consumed\')),0)::int AS available_count
             FROM course_credits cc
             JOIN courses c ON c.id=cc.course_id
             LEFT JOIN companies co ON co.id=cc.company_id
             LEFT JOIN users u ON u.id=cc.user_id
             LEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             LEFT JOIN course_credit_allocations cca ON cca.credit_id=cc.id
             GROUP BY cc.id,c.title,co.name,u.first_name,u.last_name,u.display_name,ue.email
             ORDER BY cc.created_at DESC'
        );
    }

    /** @return list<array<string,mixed>> */
    public function companyPeople(int $companyId): array
    {
        return $this->db->exec(
            'SELECT u.id,u.public_id,u.first_name,u.last_name,u.display_name,u.status,u.last_login_at,
                    ue.email,cu.company_role,
                    COALESCE(string_agg(DISTINCT r.role_key,\',\' ORDER BY r.role_key),\'\') AS role_keys,
                    COUNT(DISTINCT ce.id) FILTER (WHERE ce.status IN (\'assigned\',\'active\',\'completed\'))::int AS course_count
             FROM company_users cu
             JOIN users u ON u.id=cu.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             LEFT JOIN user_roles ur ON ur.user_id=u.id
             LEFT JOIN roles r ON r.id=ur.role_id
             LEFT JOIN course_enrolments ce ON ce.user_id=u.id AND ce.is_preview=FALSE
             WHERE cu.company_id=:company_id AND cu.status=\'active\'
             GROUP BY u.id,ue.email,cu.company_role
             ORDER BY COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email)',
            [':company_id' => $companyId]
        );
    }

    /** @return list<array<string,mixed>> */
    public function companyRequests(int $companyId): array
    {
        return $this->db->exec(
            'SELECT cr.*,c.title AS course_title,c.slug,
                    COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS learner_name,
                    ue.email
             FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             JOIN users u ON u.id=cr.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE cr.company_id=:company_id
             ORDER BY CASE cr.status WHEN \'pending\' THEN 0 WHEN \'approved\' THEN 1 ELSE 2 END,cr.requested_at DESC',
            [':company_id' => $companyId]
        );
    }

    /** @return list<array<string,mixed>> */
    public function companyEnrolments(int $companyId): array
    {
        return $this->db->exec(
            'SELECT ce.id,ce.public_id,ce.status,ce.assigned_at,ce.started_at,ce.expires_at,ce.completed_at,
                    ce.access_removed_at,ce.access_removed_reason,c.id AS course_id,c.title AS course_title,c.slug,
                    u.id AS user_id,COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS learner_name,
                    ue.email,
                    COALESCE((SELECT COUNT(*) FROM module_progress mp WHERE mp.enrolment_id=ce.id AND mp.completed_at IS NOT NULL),0)::int AS modules_completed,
                    COALESCE((SELECT COUNT(*) FROM course_modules cm WHERE cm.course_id=ce.course_id),0)::int AS module_count
             FROM course_enrolments ce
             JOIN company_users cu ON cu.user_id=ce.user_id AND cu.company_id=:company_id AND cu.status=\'active\'
             JOIN courses c ON c.id=ce.course_id
             JOIN users u ON u.id=ce.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE ce.is_preview=FALSE
             ORDER BY ce.updated_at DESC',
            [':company_id' => $companyId]
        );
    }

    /** @return list<array<string,mixed>> */
    public function companyCredits(int $companyId): array
    {
        return $this->db->exec(
            'SELECT cc.id,cc.public_id,cc.company_id,cc.course_id,cc.access_period_seconds,cc.quantity,cc.source_type,cc.note,cc.created_at,
                    c.title AS course_title,
                    COUNT(cca.id) FILTER (WHERE cca.status=\'assigned\')::int AS assigned_count,
                    COUNT(cca.id) FILTER (WHERE cca.status=\'consumed\')::int AS consumed_count,
                    GREATEST(cc.quantity-COUNT(cca.id) FILTER (WHERE cca.status IN (\'assigned\',\'consumed\')),0)::int AS available_count
             FROM course_credits cc
             JOIN courses c ON c.id=cc.course_id
             LEFT JOIN course_credit_allocations cca ON cca.credit_id=cc.id
             WHERE cc.company_id=:company_id
             GROUP BY cc.id,c.title
             ORDER BY cc.created_at DESC',
            [':company_id' => $companyId]
        );
    }

    public function enrolmentBelongsToCompany(int $enrolmentId, int $companyId): bool
    {
        $rows = $this->db->exec(
            'SELECT EXISTS(
                SELECT 1 FROM course_enrolments ce
                JOIN company_users cu ON cu.user_id=ce.user_id AND cu.status=\'active\'
                WHERE ce.id=:enrolment_id AND cu.company_id=:company_id AND ce.is_preview=FALSE
            ) AS allowed',
            [':enrolment_id' => $enrolmentId, ':company_id' => $companyId]
        );
        return in_array($rows[0]['allowed'] ?? false, [true,1,'1','t','true'], true);
    }

    /** @param array<string,mixed> $filters @return list<array<string,mixed>> */
    public function activity(array $filters = [], int $limit = 250): array
    {
        $where = [];
        $params = [];
        $from = trim((string) ($filters['from'] ?? ''));
        $to = trim((string) ($filters['to'] ?? ''));
        $family = trim((string) ($filters['family'] ?? ''));
        $actorId = max(0, (int) ($filters['actor_id'] ?? 0));
        $courseId = max(0, (int) ($filters['course_id'] ?? 0));
        $companyId = max(0, (int) ($filters['company_id'] ?? 0));
        $query = trim((string) ($filters['q'] ?? ''));
        $eventId = max(0, (int) ($filters['event_id'] ?? 0));
        $afterId = max(0, (int) ($filters['after_id'] ?? 0));

        if ($eventId > 0) {
            $where[] = 'al.id=:event_id';
            $params[':event_id'] = $eventId;
        }
        if ($afterId > 0) {
            $where[] = 'al.id>:after_id';
            $params[':after_id'] = $afterId;
        }
        if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $from) === 1) {
            $where[] = 'al.created_at >= CAST(:from AS date)';
            $params[':from'] = $from;
        }
        if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $to) === 1) {
            $where[] = "al.created_at < CAST(:to AS date) + INTERVAL '1 day'";
            $params[':to'] = $to;
        }
        if ($family !== '' && preg_match('/^[a-z][a-z0-9_-]*$/', $family) === 1) {
            $where[] = "split_part(al.event_key,'.',1)=:family";
            $params[':family'] = $family;
        }
        if ($actorId > 0) {
            $where[] = 'al.user_id=:actor_id';
            $params[':actor_id'] = $actorId;
        }
        if ($courseId > 0) {
            $courseText = (string) $courseId;
            $params[':course_direct'] = $courseText;
            $params[':course_enrolment'] = $courseText;
            $params[':course_assessment'] = $courseText;
            $params[':course_request'] = $courseText;
            $where[] = "(
                al.metadata->>'course_id'=:course_direct
                OR EXISTS (SELECT 1 FROM course_enrolments ace WHERE ace.id::text=al.metadata->>'enrolment_id' AND ace.course_id::text=:course_enrolment)
                OR EXISTS (SELECT 1 FROM course_assessments aca WHERE aca.id::text=al.metadata->>'assessment_id' AND aca.course_id::text=:course_assessment)
                OR EXISTS (SELECT 1 FROM course_requests acr WHERE acr.id::text=al.metadata->>'request_id' AND acr.course_id::text=:course_request)
            )";
        }
        if ($companyId > 0) {
            $companyText = (string) $companyId;
            $params[':company_direct'] = $companyText;
            $params[':company_request'] = $companyText;
            $params[':company_enrolment'] = $companyText;
            $params[':company_actor'] = $companyText;
            $where[] = "(
                al.metadata->>'company_id'=:company_direct
                OR EXISTS (SELECT 1 FROM course_requests arq WHERE arq.id::text=al.metadata->>'request_id' AND arq.company_id::text=:company_request)
                OR EXISTS (
                    SELECT 1 FROM course_enrolments aen
                    JOIN company_users acu ON acu.user_id=aen.user_id AND acu.status='active'
                    WHERE aen.id::text=al.metadata->>'enrolment_id' AND acu.company_id::text=:company_enrolment
                )
                OR EXISTS (SELECT 1 FROM company_users acu2 WHERE acu2.user_id=al.user_id AND acu2.status='active' AND acu2.company_id::text=:company_actor)
            )";
        }
        if ($query !== '') {
            $like = '%' . $query . '%';
            $params[':query_event'] = $like;
            $params[':query_actor'] = $like;
            $params[':query_metadata'] = $like;
            $where[] = "(al.event_key ILIKE :query_event OR COALESCE(NULLIF(trim(concat_ws(' ',u.first_name,u.last_name)),''),u.display_name,ue.email,'System') ILIKE :query_actor OR al.metadata::text ILIKE :query_metadata)";
        }

        $sql = <<<'SQL'
SELECT al.id, al.event_key, al.metadata, al.created_at, al.user_id AS actor_user_id,
       COALESCE(NULLIF(trim(concat_ws(' ',u.first_name,u.last_name)),''),u.display_name,ue.email,'System') AS actor_name,
       COALESCE(
           (SELECT c.title FROM courses c WHERE c.id::text=al.metadata->>'course_id' LIMIT 1),
           (SELECT c.title FROM course_enrolments ce JOIN courses c ON c.id=ce.course_id WHERE ce.id::text=al.metadata->>'enrolment_id' LIMIT 1),
           (SELECT c.title FROM course_assessments ca JOIN courses c ON c.id=ca.course_id WHERE ca.id::text=al.metadata->>'assessment_id' LIMIT 1),
           (SELECT c.title FROM course_requests cr JOIN courses c ON c.id=cr.course_id WHERE cr.id::text=al.metadata->>'request_id' LIMIT 1)
       ) AS course_title,
       COALESCE(
           (SELECT co.name FROM companies co WHERE co.id::text=al.metadata->>'company_id' LIMIT 1),
           (SELECT co.name FROM course_requests cr JOIN companies co ON co.id=cr.company_id WHERE cr.id::text=al.metadata->>'request_id' LIMIT 1),
           (SELECT co.name FROM course_enrolments ce JOIN company_users cu ON cu.user_id=ce.user_id AND cu.status='active' JOIN companies co ON co.id=cu.company_id WHERE ce.id::text=al.metadata->>'enrolment_id' LIMIT 1),
           (SELECT co.name FROM company_users cu JOIN companies co ON co.id=cu.company_id WHERE cu.user_id=al.user_id AND cu.status='active' LIMIT 1)
       ) AS company_name,
       COALESCE(
           (SELECT COALESCE(NULLIF(trim(concat_ws(' ',tu.first_name,tu.last_name)),''),tu.display_name,te.email) FROM users tu LEFT JOIN user_emails te ON te.user_id=tu.id AND te.is_primary=TRUE WHERE tu.id::text=al.metadata->>'user_id' LIMIT 1),
           (SELECT COALESCE(NULLIF(trim(concat_ws(' ',eu.first_name,eu.last_name)),''),eu.display_name,ee.email) FROM course_enrolments ce JOIN users eu ON eu.id=ce.user_id LEFT JOIN user_emails ee ON ee.user_id=eu.id AND ee.is_primary=TRUE WHERE ce.id::text=al.metadata->>'enrolment_id' LIMIT 1)
       ) AS subject_user_name,
       split_part(al.event_key,'.',1) AS event_family
FROM audit_log al
LEFT JOIN users u ON u.id=al.user_id
LEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
SQL;
        if ($where !== []) {
            $sql .= ' WHERE ' . implode(' AND ', $where);
        }
        $sql .= ' ORDER BY al.created_at DESC, al.id DESC LIMIT ' . max(1, min(500, $limit));
        return $this->db->exec($sql, $params);
    }

    /** @return list<string> */
    public function activityFamilies(): array
    {
        $rows = $this->db->exec("SELECT DISTINCT split_part(event_key,'.',1) AS family FROM audit_log WHERE event_key<>'' ORDER BY family");
        return array_values(array_filter(array_map(static fn(array $row): string => (string) ($row['family'] ?? ''), $rows)));
    }

    /** @return array<string,int|float> */
    public function reportSummary(): array
    {
        $rows = $this->db->exec(<<<'SQL'
SELECT
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE)::int AS enrolments,
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE AND status='assigned')::int AS assigned,
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE AND status='active')::int AS active,
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE AND status='completed')::int AS completed,
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE AND status='cancelled')::int AS cancelled,
  (SELECT COUNT(*) FROM assessment_sessions s JOIN course_enrolments e ON e.id=s.enrolment_id WHERE e.is_preview=FALSE AND s.status='submitted' AND s.attempt_mode='graded')::int AS graded_assessments,
  COALESCE((SELECT ROUND(AVG(s.percentage),1) FROM assessment_sessions s JOIN course_enrolments e ON e.id=s.enrolment_id WHERE e.is_preview=FALSE AND s.status='submitted' AND s.attempt_mode='graded'),0)::float AS assessment_average,
  COALESCE((SELECT ROUND(100.0*AVG(CASE WHEN s.passed THEN 1 ELSE 0 END),1) FROM assessment_sessions s JOIN course_enrolments e ON e.id=s.enrolment_id WHERE e.is_preview=FALSE AND s.status='submitted' AND s.attempt_mode='graded'),0)::float AS assessment_pass_rate,
  (SELECT COUNT(*) FROM certificates WHERE revoked_at IS NULL)::int AS certificates
SQL);
        return $rows[0] ?? [];
    }

    /** @return list<array<string,mixed>> */
    public function courseReport(): array
    {
        return $this->db->exec(<<<'SQL'
SELECT c.id,c.title,c.status,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE)::int AS enrolments,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE AND ce.started_at IS NOT NULL)::int AS started,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE AND ce.status='completed')::int AS completed,
       COALESCE(ROUND(AVG(cr.overall_percentage) FILTER (WHERE ce.is_preview=FALSE),1),0)::float AS average_result
FROM courses c
LEFT JOIN course_enrolments ce ON ce.course_id=c.id
LEFT JOIN course_results cr ON cr.enrolment_id=ce.id
GROUP BY c.id
ORDER BY c.title
SQL);
    }

    /** @return list<array<string,mixed>> */
    public function companyReport(): array
    {
        return $this->db->exec(<<<'SQL'
SELECT co.id,co.name,co.company_type,
       COUNT(DISTINCT cu.user_id) FILTER (WHERE cu.status='active')::int AS people,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE)::int AS enrolments,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE AND ce.status='completed')::int AS completed
FROM companies co
LEFT JOIN company_users cu ON cu.company_id=co.id
LEFT JOIN course_enrolments ce ON ce.user_id=cu.user_id
WHERE co.status='active'
GROUP BY co.id
ORDER BY co.is_system DESC,co.name
SQL);
    }

    /** @return list<array<string,mixed>> */
    public function favourites(int $userId): array
    {
        return $this->db->exec(
            'SELECT c.* FROM course_favourites cf JOIN courses c ON c.id=cf.course_id
             WHERE cf.user_id=:user_id ORDER BY cf.created_at DESC',
            [':user_id' => $userId]
        );
    }

    /** @return list<array<string,mixed>> */
    public function userRequests(int $userId): array
    {
        return $this->db->exec(
            'SELECT cr.*, c.title AS course_title, c.slug FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             WHERE cr.user_id=:user_id ORDER BY cr.requested_at DESC',
            [':user_id' => $userId]
        );
    }

    public function toggleFavourite(int $userId, int $courseId): bool
    {
        $deleted = $this->db->exec(
            'DELETE FROM course_favourites WHERE user_id=:user_id AND course_id=:course_id RETURNING course_id',
            [':user_id' => $userId, ':course_id' => $courseId]
        );
        if ($deleted !== []) {
            return false;
        }
        $this->db->exec(
            'INSERT INTO course_favourites (user_id,course_id,created_at) VALUES (:user_id,:course_id,NOW()) ON CONFLICT (user_id,course_id) DO NOTHING',
            [':user_id' => $userId, ':course_id' => $courseId]
        );
        return true;
    }

    public function createRequest(int $userId, ?int $companyId, int $courseId, int $accessPeriodSeconds, string $note): int
    {
        $existing = new CourseRequestsM($this->db);
        $existing->load([
            "user_id = ? AND course_id = ? AND status IN ('pending','approved')",
            $userId,
            $courseId,
        ]);
        if (!$existing->dry()) {
            throw new RuntimeException('You already have an open request for this course.');
        }
        $model = new CourseRequestsM($this->db);
        $model->public_id = Uuid::v4();
        $model->user_id = $userId;
        $model->company_id = $companyId;
        $model->course_id = $courseId;
        $model->access_period_seconds = $accessPeriodSeconds;
        $model->learner_note = trim($note);
        $model->decision_note = '';
        $model->status = 'pending';
        $model->requested_at = gmdate('Y-m-d H:i:sP');
        $model->save();
        return (int) $model->id;
    }

    /** @return array<string,mixed>|null */
    public function requestForUpdate(int $requestId): ?array
    {
        $rows = $this->db->exec(
            'SELECT cr.*, c.title AS course_title, ue.email, co.name AS company_name
             FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             JOIN user_emails ue ON ue.user_id=cr.user_id AND ue.is_primary=TRUE
             LEFT JOIN companies co ON co.id=cr.company_id
             WHERE cr.id=:id FOR UPDATE',
            [':id' => $requestId]
        );
        return $rows[0] ?? null;
    }

    public function decideRequest(int $requestId, string $status, string $note, int $actorUserId, ?int $enrolmentId = null): void
    {
        $model = new CourseRequestsM($this->db);
        $model->load(['id = ?', $requestId]);
        if ($model->dry()) {
            throw new RuntimeException('The course request no longer exists.');
        }
        $model->status = $status;
        $model->decision_note = trim($note);
        $model->decided_at = gmdate('Y-m-d H:i:sP');
        $model->decided_by_user_id = $actorUserId;
        if ($enrolmentId !== null) {
            $model->enrolment_id = $enrolmentId;
            $model->fulfilled_at = gmdate('Y-m-d H:i:sP');
        }
        $model->save();
    }

    /** @return array<string,mixed>|null */
    public function availableCredit(int $companyId, int $courseId, int $accessPeriodSeconds): ?array
    {
        // A correlated count keeps the candidate row lock legal in PostgreSQL.
        // GROUP BY queries cannot be combined safely with FOR UPDATE.
        $rows = $this->db->exec(
            'SELECT cc.*,
                    (SELECT COUNT(*) FROM course_credit_allocations cca
                     WHERE cca.credit_id=cc.id AND cca.status IN (\'assigned\',\'consumed\'))::int AS used_count
             FROM course_credits cc
             WHERE cc.company_id=:company_id
               AND cc.course_id=:course_id
               AND cc.access_period_seconds=:period
               AND cc.quantity > (
                    SELECT COUNT(*) FROM course_credit_allocations cca
                    WHERE cca.credit_id=cc.id AND cca.status IN (\'assigned\',\'consumed\')
               )
             ORDER BY cc.created_at, cc.id
             FOR UPDATE OF cc SKIP LOCKED
             LIMIT 1',
            [':company_id' => $companyId, ':course_id' => $courseId, ':period' => $accessPeriodSeconds]
        );
        return $rows[0] ?? null;
    }

    public function allocateCredit(int $creditId, int $userId, int $enrolmentId, int $actorUserId): void
    {
        $model = new CourseCreditAllocationsM($this->db);
        $model->credit_id = $creditId;
        $model->user_id = $userId;
        $model->enrolment_id = $enrolmentId;
        $model->status = 'assigned';
        $model->assigned_by_user_id = $actorUserId;
        $model->assigned_at = gmdate('Y-m-d H:i:sP');
        $model->save();
    }

    public function addCredit(?int $companyId, ?int $userId, int $courseId, int $period, int $quantity, string $reason, string $note, int $actorUserId): int
    {
        $model = new CourseCreditsM($this->db);
        $model->public_id = Uuid::v4();
        $model->company_id = $companyId;
        $model->user_id = $userId;
        $model->course_id = $courseId;
        $model->access_period_seconds = $period;
        $model->quantity = $quantity;
        $model->source_type = $reason;
        $model->note = trim($note);
        $model->created_by_user_id = $actorUserId;
        $model->created_at = gmdate('Y-m-d H:i:sP');
        $model->save();
        return (int) $model->id;
    }

    /** @return list<int> */
    public function activeCompanyUserEnrolmentIds(int $companyId, int $userId): array
    {
        $rows = $this->db->exec(
            "SELECT ce.id
             FROM course_enrolments ce
             JOIN company_users cu ON cu.user_id=ce.user_id AND cu.company_id=:company_id
             WHERE ce.user_id=:user_id AND ce.is_preview=FALSE AND ce.status IN ('assigned','active','completed')",
            [':company_id' => $companyId, ':user_id' => $userId]
        );
        return array_values(array_map(static fn(array $row): int => (int) $row['id'], $rows));
    }

    public function removeEnrolmentAccess(int $enrolmentId, int $actorUserId, string $reason): void
    {
        $model = new CourseEnrolmentsM($this->db);
        $model->load(['id = ? AND is_preview = FALSE', $enrolmentId]);
        if ($model->dry()) {
            throw new RuntimeException('The enrolment does not exist.');
        }
        $model->status = 'cancelled';
        $model->access_removed_at = gmdate('Y-m-d H:i:sP');
        $model->access_removed_by_user_id = $actorUserId;
        $model->access_removed_reason = trim($reason);
        $model->updated_at = gmdate('Y-m-d H:i:sP');
        $model->save();

        // Unstarted allocations may return to the holder's pool. Once the
        // learner has started, the course credit remains permanently consumed.
        if ($model->started_at === null || $model->started_at === '') {
            $this->db->exec(
                "UPDATE course_credit_allocations
                 SET status='returned', returned_at=NOW()
                 WHERE enrolment_id=:enrolment_id AND status='assigned'",
                [':enrolment_id' => $enrolmentId]
            );
        }
    }

    public function restoreEnrolmentAccess(int $enrolmentId, int $actorUserId): void
    {
        $model = new CourseEnrolmentsM($this->db);
        $model->load(['id = ? AND is_preview = FALSE', $enrolmentId]);
        if ($model->dry()) {
            throw new RuntimeException('The enrolment does not exist.');
        }

        $duplicate = new CourseEnrolmentsM($this->db);
        $duplicate->load([
            "id <> ? AND user_id = ? AND course_id = ? AND is_preview = FALSE AND status IN ('assigned','active','completed')",
            $enrolmentId,
            (int) $model->user_id,
            (int) $model->course_id,
        ]);
        if (!$duplicate->dry()) {
            throw new RuntimeException('This learner already has active access to the course. Remove the duplicate access before restoring this enrolment.');
        }

        $model->status = ($model->started_at === null || $model->started_at === '') ? 'assigned' : 'active';
        $model->access_removed_at = null;
        $model->access_removed_by_user_id = null;
        $model->access_removed_reason = '';
        $model->updated_at = gmdate('Y-m-d H:i:sP');
        $model->save();

        $allocationStatus = ($model->started_at === null || $model->started_at === '') ? 'assigned' : 'consumed';
        $this->db->exec(
            "UPDATE course_credit_allocations
             SET status=:status,
                 returned_at=CASE WHEN :status='assigned' THEN NULL ELSE returned_at END,
                 consumed_at=CASE WHEN :status='consumed' THEN COALESCE(consumed_at,NOW()) ELSE consumed_at END
             WHERE enrolment_id=:enrolment_id AND status IN ('returned','assigned','consumed')",
            [':status' => $allocationStatus, ':enrolment_id' => $enrolmentId]
        );
    }

    public function resetEnrolmentProgress(int $enrolmentId): void
    {
        $this->db->exec('DELETE FROM certificates WHERE enrolment_id=:id', [':id' => $enrolmentId]);
        $this->db->exec('DELETE FROM course_results WHERE enrolment_id=:id', [':id' => $enrolmentId]);
        $this->db->exec('DELETE FROM assessment_sessions WHERE enrolment_id=:id', [':id' => $enrolmentId]);
        $this->db->exec('DELETE FROM assessment_attempts WHERE enrolment_id=:id', [':id' => $enrolmentId]);
        $this->db->exec('DELETE FROM module_progress WHERE enrolment_id=:id', [':id' => $enrolmentId]);
        $model = new CourseEnrolmentsM($this->db);
        $model->load(['id = ?', $enrolmentId]);
        if (!$model->dry()) {
            $model->status = 'assigned';
            $model->started_at = null;
            $model->expires_at = null;
            $model->completed_at = null;
            $model->updated_at = gmdate('Y-m-d H:i:sP');
            $model->save();
        }
    }
}