<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/04 21:00 SAST

Version: 0.6

Description:
Provides PostgreSQL persistence queries and data-access operations for administration records.
Every list query is bounded and paired with a count query that describes exactly the same
population, so no Administration or Company surface can truncate silently or report a total
that disagrees with the rows beneath it.

Changelog:




2026/09/07 23:45 SAST

- isActiveCompanyMember() and learnerNotice(), for the assignment guard and the enrolment email.
2026/09/07 21:00 SAST

- Course Requests filters by status, with the same predicate on the rows and the count.
2026/09/07 12:00 SAST

- companyOwnsCourse(): ownership is the entitlement, so approval no longer looks for a credit for a company's own course.
2026/09/07 11:00 SAST

- Sort whitelists for every remaining paginated list, Administration and Company alike, and one orderFor() helper so a sorted list cannot forget its tiebreaker.
2026/09/04 21:00 SAST
- Pagination 2.0: every paginated read is a deferred join - the page identifiers are selected first and the joins, aggregates and correlated sub-selects run for those rows only. Orderings moved into named constants ending in a unique tiebreaker, People and Requests now order on the generated sort keys, the Companies aggregate no longer builds a cartesian product of three one-to-many joins, and the Activity actor joins are carried only when the search reads them.
2026/08/31 19:05 SAST
- Round: shared search button moved into noscript, server-search marker on every results region, Course Library rebuilt as paginated accordions, Reports paginated and searched, company requests as a table, company dashboard Courses figure.
2026/08/23 04:19 SAST
- Scoped every list, count and aggregate to the caller's data universe. The dashboard and report scalars mattered most: an unscoped count blends generated data into a genuine figure with nothing on screen to show it happened.
2026/08/21 01:00 SAST
- Restored the activity() PHPDoc dropped when activityConditions() was extracted; PHPStan level 6 requires the iterable value types.
2026/08/20 20:02 SAST
- Added LIMIT/OFFSET pagination plus matching count queries to People, Enrolments, Requests, the credit ledger and every company-scoped list.
- Removed the silent 250-row People cap and the hard 500-row Enrolments/Requests caps; the credit ledger is no longer unbounded.
- Extracted activityConditions() so activity() and the new activityCount() cannot drift apart on filter semantics.
- Added unique ordering tiebreakers to every paginated query so rows cannot repeat or vanish between pages.
- Centralised LIMIT/OFFSET interpolation in limitOffset(), clamped to the approved Pagination page sizes.
2026/08/17 01:03 SAST
- Fixed PostgreSQL request locking so course approval locks only the course_requests row when optional company data is joined.
2026/08/17 00:57 SAST
- Added account creation timestamps to the Administration People listing.
2026/08/12 23:56 SAST
- Updated source metadata for the Catto Learning 0.5.5 release.
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Updated source metadata for the Catto Learning 0.5.2 release.
2026/08/11 15:02 SAST
- Standardised this source file with the Catto Learning 0.5.1 SAST metadata header.
- Added Activity Centre incremental event filtering.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Persistence;

use CattoLearning\Support\Pagination;
use CattoLearning\Support\SortOrder;
use CattoLearning\Support\Uuid;

use RuntimeException;

final class AdministrationRepository
{
    public function __construct(
        private readonly Database $db
    ) {
    }

    /** @return array<string,int|float> */
    public function overview(): array
    {
        // Every sub-select carries its own scope. These are the headline dashboard figures, and
        // an unscoped scalar reports REAL+SEED to anyone holding PLATFORM.DASHBOARD.VIEW without
        // any list being visibly wrong - the failure mode this release exists to prevent.
        $rows = $this->db->fetchAllAssociative(<<<SQL
SELECT
 (SELECT COUNT(*) FROM users WHERE status='active')::int AS people,
 (SELECT COUNT(*) FROM courses WHERE status='published')::int AS published_courses,
 (SELECT COUNT(*) FROM courses WHERE status='draft')::int AS draft_courses,
 (SELECT COUNT(*) FROM companies WHERE status='active')::int AS companies,
 (SELECT COUNT(*) FROM course_requests WHERE status='pending')::int AS pending_requests,
 (SELECT COUNT(*) FROM course_enrolments WHERE status IN ('assigned','active','completed') AND is_preview=FALSE)::int AS enrolments,
 (SELECT COUNT(*) FROM course_enrolments WHERE status='completed' AND is_preview=FALSE)::int AS completed
SQL);
        $row = $rows[0] ?? [];
        $enrolments = max(0, (int) ($row['enrolments'] ?? 0));
        $completed = max(0, (int) ($row['completed'] ?? 0));
        return [
            'people' => (int) ($row['people'] ?? 0),
            'published_courses' => (int) ($row['published_courses'] ?? 0),
            'draft_courses' => (int) ($row['draft_courses'] ?? 0),
            'companies' => (int) ($row['companies'] ?? 0),
            'pending_requests' => (int) ($row['pending_requests'] ?? 0),
            'enrolments' => $enrolments,
            'completion_rate' => $enrolments > 0 ? round($completed / $enrolments * 100, 1) : 0.0,
        ];
    }


    /**
     * The WHERE clause a paginated dataset and its count query must both use.
     *
     * One builder for every searchable dataset. The guarantee that matters is not that the two
     * queries happen to agree today but that there is no second place to change: a count that
     * describes a different population from the rows it heads is a defect this project has already
     * shipped, and it is caused by two hand-written predicates drifting apart.
     *
     * The universe predicate is query structure and originates in DataUniverse, never in request
     * input. The search term is the opposite - it is user input, so it is bound once and reused by
     * every column rather than interpolated. `%` and `_` are escaped so a reader searching for a
     * literal underscore finds one instead of matching any character.
     *
     * An empty term contributes no predicate at all, so clearing a search returns the whole
     * selected universe rather than nothing.
     *
     * @param list<string> $columns SQL expressions to match against, e.g. 'c.name'
     * @return array{0:string,1:array<string,string>}
     */
    private static function searchFilter(string $alias, string $search, array $columns): array
    {
        $conditions = [];
        $bindings = [];

        $term = trim($search);
        if ($term !== '' && $columns !== []) {
            $matches = array_map(static fn(string $column): string => $column . ' ILIKE :search_term', $columns);
            $conditions[] = '(' . implode(' OR ', $matches) . ')';
            $bindings['search_term'] = '%' . addcslashes($term, '%_\\') . '%';
        }

        return [$conditions === [] ? '' : ' WHERE ' . implode(' AND ', $conditions), $bindings];
    }

    /**
     * The same search predicate as an AND-fragment, for a query that already has a WHERE clause.
     *
     * Enrolments, Requests and Credits all filter on `is_preview` or a status before anything
     * else, so their search cannot open a WHERE of its own. The matching rule is identical to
     * {@see searchFilter()}; only the joining keyword differs.
     *
     * @param list<string> $columns
     * @return array{0:string,1:array<string,string>}
     */
    private static function andSearch(string $search, array $columns): array
    {
        $term = trim($search);
        if ($term === '' || $columns === []) {
            return ['', []];
        }

        $matches = array_map(static fn(string $column): string => $column . ' ILIKE :search_term', $columns);

        return [
            ' AND (' . implode(' OR ', $matches) . ')',
            ['search_term' => '%' . addcslashes($term, '%_\\') . '%'],
        ];
    }

    /** Columns each shared dataset search matches on; the page and its count use the same list. */
    // Each expression is written to match a trigram index in
    // 20260830220000_add_search_trigram_indexes character for character. A predicate that differs
    // from its index - even by a cast - simply will not use it, and the search silently falls back
    // to a sequential scan. DatasetSearchIndexTest asserts the pairing.
    private const FULLNAME = "(coalesce(u.first_name,'') || ' ' || coalesce(u.last_name,''))";
    private const PEOPLE_SEARCH = [self::FULLNAME, 'u.display_name::text', 'ue.email::text'];

    /**
     * The learner-facing lists all search one thing: the course title. They are already narrowed
     * to one person, so a name or email column would match every row or none.
     */
    private const COURSE_TITLE_SEARCH = ['c.title::text'];

    /** Reports search the one column a reader can see and recognise. */
    private const COURSE_REPORT_SEARCH = ['c.title::text'];
    private const COMPANY_REPORT_SEARCH = ['co.name::text'];
    private const ENROLMENT_SEARCH = [self::FULLNAME, 'u.display_name::text', 'ue.email::text', 'c.title::text'];
    private const REQUEST_SEARCH = [self::FULLNAME, 'u.display_name::text', 'ue.email::text', 'c.title::text'];

    /**
     * The Enrolments ordering, newest activity first.
     *
     * `assigned_at` used to sit between `updated_at` and `id`. It decided nothing: two enrolments
     * updated in the same instant are separated by their id anyway, and carrying it meant no index
     * could serve the sort. `ce.id` alone makes the order total.
     */
    private const ENROLMENT_ORDER = 'ce.updated_at DESC, ce.id DESC';

    /**
     * The Course Requests ordering: pending first, then approved, then everything else.
     *
     * `status_rank` is the generated column the v0.6 migration added. It replaced a CASE over the
     * status text written out at each call site - three of them, which had to be kept identical by
     * hand - and unlike the CASE it can be indexed.
     */
    private const REQUEST_ORDER = 'cr.status_rank, cr.requested_at DESC, cr.id DESC';
    private const CREDIT_SEARCH = ['co.name::text', self::FULLNAME, 'u.display_name::text', 'ue.email::text', 'c.title::text'];

    /** The credit-ledger ordering, newest first, made total by the credit's own id. */
    private const CREDIT_ORDER = 'cc.created_at DESC, cc.id DESC';

    /** The Activity log ordering, newest first, made total by the entry's own id. */
    private const ACTIVITY_ORDER = 'al.created_at DESC, al.id DESC';

    /**
     * The two Reports orderings.
     *
     * Both ended on a name before v0.6 - a course title and a company name - and neither is
     * unique. Eighteen courses in this development database share a title, so a course could
     * appear on two consecutive report pages or on neither.
     */
    private const COURSE_REPORT_ORDER = 'c.title, c.id';
    private const COMPANY_REPORT_ORDER = 'co.is_system DESC, co.name, co.id';

    /**
     * The LIMIT/OFFSET clause for a paginated query, from the one shared clamp.
     *
     * This used to hold its own copy of the clamp; {@see PageQuery::limitOffset()} is now the
     * single definition, so the bound a repository interpolates cannot differ from the bound the
     * deferred-join composer applies to the same page.
     */
    private function limitOffset(int $limit, int $offset): string
    {
        return PageQuery::limitOffset($limit, $offset);
    }

    /**
     * The Administration and Company People ordering.
     *
     * `sort_name` is the generated column the v0.6 migration added, so this is an ordinary column
     * pair an index can walk. It replaced
     * `COALESCE(NULLIF(trim(concat_ws(' ',first_name,last_name)),''),display_name,ue.email)`, which
     * could not be indexed at all: `concat_ws()` is only STABLE, and the email fallback lives on
     * another table. `u.id` makes the order total, so two people sharing a name cannot swap places
     * between one page view and the next.
     */
    private const PEOPLE_ORDER = 'u.sort_name, u.id';

    /**
     * The columns Administration People may be sorted by, and the expression each one means.
     *
     * The request supplies a key from this map and never a column name: an ORDER BY takes an
     * expression rather than a value, so there is no binding that would make a supplied column
     * safe. A key that is not here resolves to the default instead of failing.
     *
     * Every expression is indexed or cheap to sort. `sort_name` and `created_at` are backed
     * directly; `email` sorts a joined column the primary-email index already covers.
     *
     * @var array<string,string>
     */
    public const PEOPLE_SORTS = [
        'name' => 'u.sort_name',
        'email' => 'ue.email',
        'company' => "(SELECT sco.name FROM companies sco
                         JOIN company_users scu ON scu.company_id=sco.id AND scu.user_id=u.id AND scu.status='active'
                        ORDER BY sco.name LIMIT 1)",
        'courses' => '(SELECT COUNT(*) FROM course_enrolments sce WHERE sce.user_id=u.id AND sce.is_preview=FALSE)',
        'status' => 'u.status',
        'created' => 'u.created_at',
        'last_login' => 'u.last_login_at',
    ];

    /**
     * Composes one ORDER BY from a whitelisted expression and the dataset's own tiebreaker.
     *
     * The tiebreaker is appended rather than replaced, so an ordering the reader chose is still
     * total. Without it, sorting People by status - four distinct values across a hundred thousand
     * rows - would leave PostgreSQL free to return any of them in any order, and paging through
     * that shows some people twice and others never.
     *
     * NULLS LAST in both directions on purpose: a person who has never signed in belongs at the
     * end of the list whether the reader asked for oldest or newest first, because "no value" is
     * not a value that sorts.
     */
    /**
     * The ORDER BY a list should use: the reader's chosen column, or the dataset's default.
     *
     * One helper rather than the same three lines in eight methods, so a list cannot be given a
     * sort and quietly forget to append its tiebreaker.
     *
     * @param array<string,string> $sorts
     */
    private static function orderFor(?SortOrder $sort, array $sorts, string $default, string $tiebreaker): string
    {
        return $sort === null ? $default : self::sorted($sorts[$sort->key], $sort, $tiebreaker);
    }

    private static function sorted(string $expression, SortOrder $sort, string $tiebreaker): string
    {
        return $expression . ' ' . $sort->sql() . ' NULLS LAST, ' . $tiebreaker;
    }

    /**
     * One page of the Administration People list.
     *
     * Deferred join. The key query finds the twenty-five user ids on this page using only the
     * columns the filter and the ordering need; the detail query then joins the company, the roles
     * and the enrolment counts for those twenty-five and nobody else. Written the obvious way this
     * aggregated every matching person in the platform to display a page of them, so the work grew
     * with the dataset rather than with the page.
     *
     * @return list<array<string,mixed>>
     */
    public function people(int $limit, int $offset, string $search = '', ?SortOrder $sort = null): array
    {
        $order = $sort === null
            ? self::PEOPLE_ORDER
            : self::sorted(self::PEOPLE_SORTS[$sort->key], $sort, 'u.id');

        $keys = <<<'SQL'
SELECT u.id
FROM users u
JOIN user_emails ue ON ue.user_id = u.id AND ue.is_primary = TRUE
SQL;

        $detail = <<<'SQL'
SELECT
    u.id,
    u.public_id,
    u.first_name,
    u.middle_names,
    u.last_name,
    u.display_name,
    u.status,
    u.created_at,
    u.last_login_at,
    ue.email,
    c.id AS company_id,
    c.name AS company_name,
    COALESCE(string_agg(DISTINCT r.role_key, ',' ORDER BY r.role_key), '') AS role_keys,
    COUNT(DISTINCT ce.id) FILTER (WHERE ce.status IN ('assigned','active','completed'))::int AS course_count
FROM page
JOIN users u ON u.id = page.id
JOIN user_emails ue ON ue.user_id = u.id AND ue.is_primary = TRUE
LEFT JOIN company_users cu ON cu.user_id = u.id AND cu.status = 'active'
LEFT JOIN companies c ON c.id = cu.company_id
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
LEFT JOIN course_enrolments ce ON ce.user_id = u.id AND ce.is_preview = FALSE
GROUP BY u.id, ue.email, c.id, c.name
SQL;

        [$where, $bindings] = self::searchFilter('u', $search, self::PEOPLE_SEARCH);

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys . $where, $detail, $order, $limit, $offset),
            $bindings
        );
    }

    /**
     * Total People rows.
     *
     * Membership must match {@see people()} exactly: the primary-email join is an INNER join
     * there, so a user without a primary email is absent from both the page and the total.
     */
    public function peopleCount(string $search = ''): int
    {
        [$where, $bindings] = self::searchFilter('u', $search, self::PEOPLE_SEARCH);
        $rows = $this->db->fetchAllAssociative(
            'SELECT COUNT(*)::int AS total
             FROM users u
             JOIN user_emails ue ON ue.user_id = u.id AND ue.is_primary = TRUE'
            . $where,
            $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    /**
     * Which companies a Companies screen is about.
     *
     * Two audiences rather than one list with a type column. A **creator** owns courses and offers
     * them; a **consumer** has staff being trained. They are asked different questions - a creator
     * screen wants owned courses, a consumer screen wants people and enrolments - and a single list
     * showing both columns to both audiences leaves most of every row empty.
     *
     * Split on the relationship rather than on a `company_type` field, so a company that both sells
     * and buys appears on both screens, which is what it actually is. A type field would force it to
     * be one or the other.
     */
    private static function companyAudienceWhere(string $existingWhere, string $audience): string
    {
        $predicate = self::companyAudiencePredicate($audience);
        if ($predicate === '') {
            return $existingWhere;
        }

        // The search filter opens the WHERE only when it has something to say, and in the ALL
        // universe with no search term it has nothing: appending an AND-fragment to an empty string
        // is a syntax error, not a narrower query.
        return $existingWhere === ''
            ? ' WHERE ' . $predicate
            : $existingWhere . ' AND ' . $predicate;
    }

    /** The predicate itself, without the joining keyword. */
    private static function companyAudiencePredicate(string $audience): string
    {
        return match ($audience) {
            'creators' => 'EXISTS (SELECT 1 FROM courses oc WHERE oc.owner_company_id = c.id)',
            // The last clause is what keeps every company reachable. A company with no staff, no
            // credits and no courses is on neither side of the split by any positive test, so it
            // would be administered from nowhere - and a company is created empty, which makes that
            // the state every new one starts in. Owning no courses is therefore enough to be a
            // consumer, and Consumers is where staff are added.
            'consumers' => "(EXISTS (SELECT 1 FROM company_users acu
                                 WHERE acu.company_id = c.id AND acu.status = 'active')
                              OR EXISTS (SELECT 1 FROM course_credits acc WHERE acc.company_id = c.id)
                              OR NOT EXISTS (SELECT 1 FROM courses noc WHERE noc.owner_company_id = c.id))",
            default => '',
        };
    }

    /**
     * One page of the Administration Companies list. This was the project's reference
     * pagination implementation and keeps its established behaviour and view-variable names;
     * only the shared limit/offset handling and the unique ordering tiebreaker changed.
     *
     * @return list<array<string,mixed>>
     */
    public function companies(int $limit, int $offset, string $search = '', ?SortOrder $sort = null, string $audience = ''): array
    {
        $order = self::orderFor($sort, self::COMPANY_SORTS, self::COMPANY_ORDER, 'c.id');
        $keys = 'SELECT c.id FROM companies c';

        // The three figures are scalar sub-selects rather than joined aggregates, and that is not a
        // style preference.
        //
        // This query used to join `company_users`, `courses` and a second `company_users` to the
        // same company and then de-duplicate with COUNT(DISTINCT). Those are three independent
        // one-to-many relationships, so the join produces their cartesian product: a company with
        // twenty thousand people and a hundred courses builds four hundred million intermediate
        // rows to arrive at three integers. On the development database, where the largest company
        // held a few dozen people, it was invisible; the v0.6 benchmark, whose largest company
        // holds twenty thousand, could not complete the first page of this list in ten minutes.
        //
        // Each sub-select counts one relationship on its own, so the cost is the sum of the three
        // rather than their product, and no DISTINCT is needed to undo a fan-out that never
        // happens. The membership rules are unchanged, which is why the counts are identical.
        $detail = <<<'SQL'
SELECT c.*,
       (SELECT COUNT(*)::int FROM company_users cu
         WHERE cu.company_id=c.id AND cu.status='active') AS people_count,
       (SELECT COUNT(*)::int FROM courses co
         WHERE co.owner_company_id=c.id) AS owned_course_count,
       (SELECT COUNT(*)::int FROM course_enrolments ce
          JOIN company_users lcu ON lcu.user_id=ce.user_id AND lcu.company_id=c.id AND lcu.status='active'
         WHERE ce.is_preview=FALSE AND ce.status IN ('assigned','active','completed')) AS enrolment_count
FROM page
JOIN companies c ON c.id=page.id
SQL;
        [$where, $bindings] = self::searchFilter('c', $search, self::COMPANY_SEARCH);
        $where = self::companyAudienceWhere($where, $audience);

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys . $where, $detail, $order, $limit, $offset),
            $bindings
        );
    }

    public function companyCount(string $search = '', string $audience = ''): int
    {
        // The identical audience predicate the rows use.
        [$where, $bindings] = self::searchFilter('c', $search, self::COMPANY_SEARCH);
        $where = self::companyAudienceWhere($where, $audience);
        $rows = $this->db->fetchAllAssociative('SELECT COUNT(*)::int AS total FROM companies c' . $where, $bindings);

        return (int) ($rows[0]['total'] ?? 0);
    }

    /** Columns the Companies search matches on; used by both the page and the count. */
    private const COMPANY_SEARCH = ['c.name::text', 'c.domain::text'];

    /**
     * The Companies ordering: the System Company first, then alphabetically, then by id.
     *
     * `c.id` is the tiebreaker that makes the order total. Two companies may share a name in
     * different data universes, and without it either could take the other's place on a page
     * boundary between one view and the next.
     */
    private const COMPANY_ORDER = 'c.is_system DESC, c.name, c.id';

    /**
     * The columns Administration Companies may be sorted by.
     *
     * The three counts are the same scalar sub-selects the projection uses, written out here rather
     * than referred to by their aliases, because the deferred join applies one order expression to
     * both halves and the key query has no aliases to refer to. They are correlated sub-queries in
     * an ORDER BY, so sorting by one of them costs a pass over the companies table - bounded by the
     * number of companies, never by the number of people in them, which is the shape that made the
     * old cartesian version of this list unusable.
     *
     * @var array<string,string>
     */
    public const COMPANY_SORTS = [
        'name' => 'c.name',
        'domain' => 'c.domain',
        'type' => 'c.company_type',
        'people' => "(SELECT COUNT(*) FROM company_users cu WHERE cu.company_id=c.id AND cu.status='active')",
        'courses' => '(SELECT COUNT(*) FROM courses co WHERE co.owner_company_id=c.id)',
        'enrolments' => "(SELECT COUNT(*) FROM course_enrolments ce
                            JOIN company_users lcu ON lcu.user_id=ce.user_id AND lcu.company_id=c.id AND lcu.status='active'
                           WHERE ce.is_preview=FALSE AND ce.status IN ('assigned','active','completed'))",
        'status' => 'c.status',
        'created' => 'c.created_at',
    ];

    /** @var array<string,string> */
    public const ENROLMENT_SORTS = [
        'learner' => 'u.sort_name',
        'email' => 'ue.email',
        'course' => 'c.title',
        'status' => 'ce.status',
        // Modules completed, which is what the Progress column shows. Ordering by the fraction
        // instead would put a one-module course finished ahead of a fifty-module course nearly
        // finished, which is not what a reader scanning for progress is looking for.
        'progress' => '(SELECT COUNT(*) FROM module_progress smp WHERE smp.enrolment_id=ce.id AND smp.completed_at IS NOT NULL)',
        'assigned' => 'ce.assigned_at',
        'updated' => 'ce.updated_at',
        'expires' => 'ce.expires_at',
    ];

    /** @var array<string,string> */
    public const REQUEST_SORTS = [
        'learner' => 'u.sort_name',
        'email' => 'ue.email',
        'course' => 'c.title',
        'company' => 'co.name',
        'status' => 'cr.status_rank',
        'requested' => 'cr.requested_at',
    ];

    /**
     * The credit ledger columns.
     *
     * The three allocation figures are aggregates in the projection, so they are sub-selects here:
     * the deferred join's key query selects ids and has no aggregate to order by. The holder is the
     * same COALESCE the projection builds, because a credit is held by a company or by a person and
     * one column has to stand for both.
     *
     * @var array<string,string>
     */
    public const CREDIT_SORTS = [
        'holder' => "COALESCE(co.name, NULLIF(trim(concat_ws(' ',u.first_name,u.last_name)),''), u.display_name, ue.email)",
        'course' => 'c.title',
        'period' => 'cc.access_period_seconds',
        'available' => "GREATEST(cc.quantity - (SELECT COUNT(*) FROM course_credit_allocations sca
                                                 WHERE sca.credit_id=cc.id AND sca.status IN ('assigned','consumed')),0)",
        'assigned' => "(SELECT COUNT(*) FROM course_credit_allocations sca WHERE sca.credit_id=cc.id AND sca.status='assigned')",
        'consumed' => "(SELECT COUNT(*) FROM course_credit_allocations sca WHERE sca.credit_id=cc.id AND sca.status='consumed')",
        'created' => 'cc.created_at',
        'expires' => 'cc.expires_at',
    ];

    /**
     * The Company workspace lists. Separate maps from the Administration ones because the two
     * screens show different columns of the same rows, and a shared map would offer a company
     * administrator a heading their table does not have.
     *
     * @var array<string,string>
     */
    public const COMPANY_PEOPLE_SORTS = [
        'person' => 'u.sort_name',
        'courses' => '(SELECT COUNT(*) FROM course_enrolments sce WHERE sce.user_id=u.id AND sce.is_preview=FALSE)',
        'account' => 'u.status',
        'last_login' => 'u.last_login_at',
    ];

    /** @var array<string,string> */
    public const COMPANY_REQUEST_SORTS = [
        'learner' => 'u.sort_name',
        'course' => 'c.title',
        'requested' => 'cr.requested_at',
        'status' => 'cr.status_rank',
    ];

    /** @var array<string,string> */
    public const COMPANY_ENROLMENT_SORTS = [
        'learner' => 'u.sort_name',
        'course' => 'c.title',
        'status' => 'ce.status',
        'assigned' => 'ce.assigned_at',
    ];

    /** @var array<string,string> */
    public const COMPANY_CREDIT_SORTS = [
        'course' => 'c.title',
        'period' => 'cc.access_period_seconds',
        'created' => 'cc.created_at',
    ];

    /** @var array<string,string> */
    public const ACTIVITY_SORTS = [
        'event' => 'al.event_key',
        'created' => 'al.created_at',
    ];

    /**
     * The report columns, as sub-selects rather than as the aliases the projection gives them.
     *
     * The reports aggregate with GROUP BY, and the deferred join's key query has no aggregates to
     * order by - it selects ids only. One order expression serves both halves, so it has to be one
     * that stands on its own in either, which a sub-select is and an alias is not.
     *
     * The aliases inside each sub-select are deliberately unlike the ones the detail query joins
     * with. Reusing `ce` or `cr` here would silently correlate against the outer join instead of
     * the sub-query's own table, and the figures would be wrong rather than the query broken.
     *
     * @var array<string,string>
     */
    public const COURSE_REPORT_SORTS = [
        'course' => 'c.title',
        'status' => 'c.status',
        'enrolments' => '(SELECT COUNT(*) FROM course_enrolments se WHERE se.course_id=c.id AND se.is_preview=FALSE)',
        'started' => '(SELECT COUNT(*) FROM course_enrolments se WHERE se.course_id=c.id AND se.is_preview=FALSE AND se.started_at IS NOT NULL)',
        'completed' => "(SELECT COUNT(*) FROM course_enrolments se WHERE se.course_id=c.id AND se.is_preview=FALSE AND se.status='completed')",
        'average' => '(SELECT AVG(sr.overall_percentage) FROM course_results sr
                         JOIN course_enrolments se ON se.id=sr.enrolment_id
                        WHERE se.course_id=c.id AND se.is_preview=FALSE)',
    ];

    /** @var array<string,string> */
    public const COMPANY_REPORT_SORTS = [
        'company' => 'co.name',
        'type' => 'co.company_type',
        'people' => "(SELECT COUNT(*) FROM company_users scu WHERE scu.company_id=co.id AND scu.status='active')",
        'enrolments' => "(SELECT COUNT(*) FROM course_enrolments se
                            JOIN company_users scu ON scu.user_id=se.user_id AND scu.company_id=co.id AND scu.status='active'
                           WHERE se.is_preview=FALSE)",
        'completed' => "(SELECT COUNT(*) FROM course_enrolments se
                            JOIN company_users scu ON scu.user_id=se.user_id AND scu.company_id=co.id AND scu.status='active'
                           WHERE se.is_preview=FALSE AND se.status='completed')",
    ];

    /**
     * One page of the Administration Enrolments list. This replaced a hard `LIMIT 500` that
     * truncated silently: beyond 500 enrolments the screen simply stopped showing rows without
     * saying so.
     *
     * @return list<array<string,mixed>>
     */
    public function enrolments(int $limit, int $offset, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::ENROLMENT_SORTS, self::ENROLMENT_ORDER, 'ce.id DESC');
        [$match, $bindings] = self::andSearch($search, self::ENROLMENT_SEARCH);

        // The three joins are membership joins, not decoration - the primary-email join is INNER -
        // so the key query carries all of them, exactly as the count does. What it does not carry
        // is the two correlated sub-selects, which are the expensive half and now run once per
        // displayed row instead of once per enrolment in the platform.
        $keys = 'SELECT ce.id
             FROM course_enrolments ce
             JOIN courses c ON c.id=ce.course_id
             JOIN users u ON u.id=ce.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE ce.is_preview=FALSE' . '' . $match;

        $detail = 'SELECT ce.id, ce.public_id, ce.status, ce.assigned_at, ce.started_at, ce.expires_at, ce.completed_at,
                    ce.access_removed_at, ce.access_removed_reason,
                    c.id AS course_id, c.title AS course_title, c.slug,
                    u.id AS user_id, COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS learner_name,
                    ue.email,
                    COALESCE((SELECT COUNT(*) FROM module_progress mp WHERE mp.enrolment_id=ce.id AND mp.completed_at IS NOT NULL),0)::int AS modules_completed,
                    COALESCE((SELECT COUNT(*) FROM course_modules cm WHERE cm.course_id=ce.course_id),0)::int AS module_count
             FROM page
             JOIN course_enrolments ce ON ce.id=page.id
             JOIN courses c ON c.id=ce.course_id
             JOIN users u ON u.id=ce.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE';

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys, $detail, $order, $limit, $offset),
            $bindings
        );
    }

    /**
     * Total Administration Enrolments rows. The joins are repeated rather than simplified
     * because the primary-email join is an INNER join in {@see enrolments()} and therefore
     * affects membership, not just the projected columns.
     */
    public function enrolmentsCount(string $search = ''): int
    {
        [$match, $bindings] = self::andSearch($search, self::ENROLMENT_SEARCH);
        $rows = $this->db->fetchAllAssociative(
            'SELECT COUNT(*)::int AS total
             FROM course_enrolments ce
             JOIN courses c ON c.id=ce.course_id
             JOIN users u ON u.id=ce.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE ce.is_preview=FALSE' . '' . $match,
            $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    /**
     * One page of the Administration Course Requests list. Requests share the
     * `/admin/enrolments` screen with enrolments but hold entirely separate pagination state,
     * because the two datasets grow at very different rates.
     *
     * @return list<array<string,mixed>>
     */
    public function requests(int $limit, int $offset, string $search = '', ?SortOrder $sort = null, string $status = ''): array
    {
        $order = self::orderFor($sort, self::REQUEST_SORTS, self::REQUEST_ORDER, 'cr.id DESC');
        [$where, $bindings] = self::searchFilter('cr', $search, self::REQUEST_SEARCH);
        [$statusMatch, $statusBinding] = self::andRequestStatus($status);
        $where .= $statusMatch;
        $bindings += $statusBinding;

        $keys = 'SELECT cr.id
             FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             JOIN users u ON u.id=cr.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE' . $where;

        $detail = 'SELECT cr.*, c.title AS course_title, c.slug,
                    COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS learner_name,
                    ue.email, co.name AS company_name
             FROM page
             JOIN course_requests cr ON cr.id=page.id
             JOIN courses c ON c.id=cr.course_id
             JOIN users u ON u.id=cr.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             LEFT JOIN companies co ON co.id=cr.company_id';

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys, $detail, $order, $limit, $offset),
            $bindings
        );
    }

    /** Total Administration Course Requests rows, using the same membership joins as {@see requests()}. */
    /**
     * One status, or every status.
     *
     * A whitelist rather than a bound value, for the same reason an ORDER BY column is: this is
     * compared against a CHECK-constrained column and a value outside that set can only ever match
     * nothing, so an unknown one widens to everything instead of returning a silently empty screen.
     *
     * @return array{0:string,1:array<string,mixed>}
     */
    private static function andRequestStatus(string $status): array
    {
        $allowed = ['pending', 'approved', 'fulfilled', 'rejected', 'cancelled'];

        return in_array($status, $allowed, true)
            ? [' AND cr.status = :request_status', ['request_status' => $status]]
            : ['', []];
    }

    public function requestsCount(string $search = '', string $status = ''): int
    {
        // The identical filter the rows use, status included. A count built from a different filter
        // set than its list is the defect this platform has already shipped twice.
        [$where, $bindings] = self::searchFilter('cr', $search, self::REQUEST_SEARCH);
        [$statusMatch, $statusBinding] = self::andRequestStatus($status);
        $where .= $statusMatch;
        $bindings += $statusBinding;
        $rows = $this->db->fetchAllAssociative(
            'SELECT COUNT(*)::int AS total
             FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             JOIN users u ON u.id=cr.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE'
            . $where,
            $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    /**
     * One page of the Administration credit ledger. This query was previously unbounded and
     * could render the entire `course_credits` table.
     *
     * @return list<array<string,mixed>>
     */
    public function creditLedger(int $limit, int $offset, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::CREDIT_SORTS, self::CREDIT_ORDER, 'cc.id DESC');
        [$where, $bindings] = self::searchFilter('cc', $search, self::CREDIT_SEARCH);

        // The holder joins are in the key query because the search matches on them; the allocation
        // join is not, because it fans a credit out into one row per allocation and contributes
        // nothing to which credits are on the page.
        $keys = 'SELECT cc.id
             FROM course_credits cc
             JOIN courses c ON c.id=cc.course_id
             LEFT JOIN companies co ON co.id=cc.company_id
             LEFT JOIN users u ON u.id=cc.user_id
             LEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE' . $where;

        $detail = 'SELECT cc.id, cc.public_id, cc.company_id, cc.user_id, cc.course_id, cc.access_period_seconds,
                    cc.quantity, cc.source_type, cc.note, cc.created_at,
                    c.title AS course_title,
                    COALESCE(co.name, NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS holder_name,
                    COUNT(cca.id) FILTER (WHERE cca.status=\'assigned\')::int AS assigned_count,
                    COUNT(cca.id) FILTER (WHERE cca.status=\'consumed\')::int AS consumed_count,
                    GREATEST(cc.quantity - COUNT(cca.id) FILTER (WHERE cca.status IN (\'assigned\',\'consumed\')),0)::int AS available_count
             FROM page
             JOIN course_credits cc ON cc.id=page.id
             JOIN courses c ON c.id=cc.course_id
             LEFT JOIN companies co ON co.id=cc.company_id
             LEFT JOIN users u ON u.id=cc.user_id
             LEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             LEFT JOIN course_credit_allocations cca ON cca.credit_id=cc.id
             GROUP BY cc.id,c.title,co.name,u.first_name,u.last_name,u.display_name,ue.email';

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys, $detail, $order, $limit, $offset),
            $bindings
        );
    }

    /**
     * Total credit-ledger rows.
     *
     * The row query groups by `cc.id`, so one credit is exactly one row regardless of how many
     * allocations it has. Counting `course_credits` with only the membership-affecting INNER
     * join to `courses` therefore yields the same population without the allocation fan-out.
     */
    public function creditLedgerCount(string $search = ''): int
    {
        // The holder joins are repeated here because the search matches on them. They are LEFT
        // joins onto single-valued columns, so they add no rows and the population is unchanged
        // whether or not a term is supplied - which is what keeps this count describing exactly
        // the rows creditLedger() returns.
        [$where, $bindings] = self::searchFilter('cc', $search, self::CREDIT_SEARCH);
        $rows = $this->db->fetchAllAssociative(
            'SELECT COUNT(*)::int AS total
             FROM course_credits cc
             JOIN courses c ON c.id=cc.course_id
             LEFT JOIN companies co ON co.id=cc.company_id
             LEFT JOIN users u ON u.id=cc.user_id
             LEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE'
            . $where,
            $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    /** @return list<array<string,mixed>> */
    public function companyPeople(int $companyId, int $limit, int $offset, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::COMPANY_PEOPLE_SORTS, self::PEOPLE_ORDER, 'u.id');
        [$match, $bindings] = self::andSearch($search, self::PEOPLE_SEARCH);

        $keys = 'SELECT u.id
             FROM company_users cu
             JOIN users u ON u.id=cu.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE cu.company_id=:company_id AND cu.status=\'active\'' . '' . $match;

        // certificate_name and mobile_number are selected because the Company People editor
        // offers them. A template that reads a column the query never selected is an
        // undefined-variable 500, not a blank field.
        $detail = 'SELECT u.id,u.public_id,u.first_name,u.middle_names,u.last_name,u.display_name,u.status,u.last_login_at,
                    u.certificate_name,u.mobile_number,
                    ue.email,cu.company_role,
                    COALESCE(string_agg(DISTINCT r.role_key,\',\' ORDER BY r.role_key),\'\') AS role_keys,
                    COUNT(DISTINCT ce.id) FILTER (WHERE ce.status IN (\'assigned\',\'active\',\'completed\'))::int AS course_count
             FROM page
             JOIN users u ON u.id=page.id
             JOIN company_users cu ON cu.user_id=u.id AND cu.company_id=:company_id AND cu.status=\'active\'
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             LEFT JOIN user_roles ur ON ur.user_id=u.id
             LEFT JOIN roles r ON r.id=ur.role_id
             LEFT JOIN course_enrolments ce ON ce.user_id=u.id AND ce.is_preview=FALSE
             GROUP BY u.id,ue.email,cu.company_role';

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys, $detail, $order, $limit, $offset),
            ['company_id' => $companyId] + $bindings
        );
    }

    /**
     * Total people in one company.
     *
     * Scope is enforced in SQL. Company screens must never load platform-wide rows and filter
     * them afterwards, because that reintroduces exactly the unbounded query pagination exists
     * to remove.
     */
    public function companyPeopleCount(int $companyId, string $search = ''): int
    {
        [$match, $bindings] = self::andSearch($search, self::PEOPLE_SEARCH);
        $rows = $this->db->fetchAllAssociative(
            'SELECT COUNT(*)::int AS total
             FROM company_users cu
             JOIN users u ON u.id=cu.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE cu.company_id=:company_id AND cu.status=\'active\'' . '' . $match,
            ['company_id' => $companyId] + $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    /** @return list<array<string,mixed>> */
    public function companyRequests(int $companyId, int $limit, int $offset, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::COMPANY_REQUEST_SORTS, self::REQUEST_ORDER, 'cr.id DESC');
        [$match, $bindings] = self::andSearch($search, self::REQUEST_SEARCH);

        $keys = 'SELECT cr.id
             FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             JOIN users u ON u.id=cr.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE cr.company_id=:company_id' . '' . $match;

        $detail = 'SELECT cr.*,c.title AS course_title,c.slug,
                    COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS learner_name,
                    ue.email
             FROM page
             JOIN course_requests cr ON cr.id=page.id
             JOIN courses c ON c.id=cr.course_id
             JOIN users u ON u.id=cr.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE';

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys, $detail, $order, $limit, $offset),
            ['company_id' => $companyId] + $bindings
        );
    }

    /** Total course requests raised by one company. */
    public function companyRequestsCount(int $companyId, string $search = ''): int
    {
        [$match, $bindings] = self::andSearch($search, self::REQUEST_SEARCH);
        $rows = $this->db->fetchAllAssociative(
            'SELECT COUNT(*)::int AS total
             FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             JOIN users u ON u.id=cr.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE cr.company_id=:company_id' . '' . $match,
            ['company_id' => $companyId] + $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    /** @return list<array<string,mixed>> */
    public function companyEnrolments(int $companyId, int $limit, int $offset, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::COMPANY_ENROLMENT_SORTS, self::ENROLMENT_ORDER, 'ce.id DESC');
        [$match, $bindings] = self::andSearch($search, self::ENROLMENT_SEARCH);

        $keys = 'SELECT ce.id
             FROM course_enrolments ce
             JOIN company_users cu ON cu.user_id=ce.user_id AND cu.company_id=:company_id AND cu.status=\'active\'
             JOIN courses c ON c.id=ce.course_id
             JOIN users u ON u.id=ce.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE ce.is_preview=FALSE' . '' . $match;

        $detail = 'SELECT ce.id,ce.public_id,ce.status,ce.assigned_at,ce.started_at,ce.expires_at,ce.completed_at,
                    ce.access_removed_at,ce.access_removed_reason,c.id AS course_id,c.title AS course_title,c.slug,
                    u.id AS user_id,COALESCE(NULLIF(trim(concat_ws(\' \',u.first_name,u.last_name)),\'\'),u.display_name,ue.email) AS learner_name,
                    ue.email,
                    COALESCE((SELECT COUNT(*) FROM module_progress mp WHERE mp.enrolment_id=ce.id AND mp.completed_at IS NOT NULL),0)::int AS modules_completed,
                    COALESCE((SELECT COUNT(*) FROM course_modules cm WHERE cm.course_id=ce.course_id),0)::int AS module_count
             FROM page
             JOIN course_enrolments ce ON ce.id=page.id
             JOIN courses c ON c.id=ce.course_id
             JOIN users u ON u.id=ce.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE';

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys, $detail, $order, $limit, $offset),
            ['company_id' => $companyId] + $bindings
        );
    }

    /**
     * Total enrolments held by members of one company.
     *
     * The `company_users` join is what scopes this to the company, so it must be repeated
     * verbatim in the count or the total would describe a different population from the page.
     */
    public function companyEnrolmentsCount(int $companyId, string $search = ''): int
    {
        [$match, $bindings] = self::andSearch($search, self::ENROLMENT_SEARCH);
        $rows = $this->db->fetchAllAssociative(
            'SELECT COUNT(*)::int AS total
             FROM course_enrolments ce
             JOIN company_users cu ON cu.user_id=ce.user_id AND cu.company_id=:company_id AND cu.status=\'active\'
             JOIN courses c ON c.id=ce.course_id
             JOIN users u ON u.id=ce.user_id
             JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE ce.is_preview=FALSE' . '' . $match,
            ['company_id' => $companyId] + $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    /** @return list<array<string,mixed>> */
    public function companyCredits(int $companyId, int $limit, int $offset, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::COMPANY_CREDIT_SORTS, self::CREDIT_ORDER, 'cc.id DESC');
        [$match, $bindings] = self::andSearch($search, self::CREDIT_SEARCH);

        $keys = 'SELECT cc.id
             FROM course_credits cc
             JOIN courses c ON c.id=cc.course_id
             LEFT JOIN companies co ON co.id=cc.company_id
             LEFT JOIN users u ON u.id=cc.user_id
             LEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE cc.company_id=:company_id' . '' . $match;

        $detail = 'SELECT cc.id,cc.public_id,cc.company_id,cc.course_id,cc.access_period_seconds,cc.quantity,cc.source_type,cc.note,cc.created_at,
                    c.title AS course_title,
                    COUNT(cca.id) FILTER (WHERE cca.status=\'assigned\')::int AS assigned_count,
                    COUNT(cca.id) FILTER (WHERE cca.status=\'consumed\')::int AS consumed_count,
                    GREATEST(cc.quantity-COUNT(cca.id) FILTER (WHERE cca.status IN (\'assigned\',\'consumed\')),0)::int AS available_count
             FROM page
             JOIN course_credits cc ON cc.id=page.id
             JOIN courses c ON c.id=cc.course_id
             LEFT JOIN course_credit_allocations cca ON cca.credit_id=cc.id
             GROUP BY cc.id,c.title';

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys, $detail, $order, $limit, $offset),
            ['company_id' => $companyId] + $bindings
        );
    }

    /** Total credits held by one company. */
    public function companyCreditsCount(int $companyId, string $search = ''): int
    {
        [$match, $bindings] = self::andSearch($search, self::CREDIT_SEARCH);
        $rows = $this->db->fetchAllAssociative(
            'SELECT COUNT(*)::int AS total
             FROM course_credits cc
             JOIN courses c ON c.id=cc.course_id
             LEFT JOIN companies co ON co.id=cc.company_id
             LEFT JOIN users u ON u.id=cc.user_id
             LEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
             WHERE cc.company_id=:company_id' . '' . $match,
            ['company_id' => $companyId] + $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    public function enrolmentBelongsToCompany(int $enrolmentId, int $companyId): bool
    {
        $rows = $this->db->fetchAllAssociative(
            'SELECT EXISTS(
                SELECT 1 FROM course_enrolments ce
                JOIN company_users cu ON cu.user_id=ce.user_id AND cu.status=\'active\'
                WHERE ce.id=:enrolment_id AND cu.company_id=:company_id AND ce.is_preview=FALSE
            ) AS allowed',
            ['enrolment_id' => $enrolmentId, 'company_id' => $companyId]
        );
        return in_array($rows[0]['allowed'] ?? false, [true,1,'1','t','true'], true);
    }

    /**
     * @param array<string,mixed> $filters
     * @return list<array<string,mixed>>
     */
    /**
     * Builds the shared Activity WHERE fragments and bound parameters.
     *
     * Extracted so {@see activity()} and {@see activityCount()} cannot drift apart. The page
     * query and the total query must apply identical date, family, person, company, course and
     * search filtering, otherwise the screen reports a total describing a different population
     * from the rows rendered beneath it.
     *
     * `needs_actor` reports whether anything in the conditions references the actor joins, so the
     * key query and the count can leave them out when nothing reads them.
     *
     * @param array<string,mixed> $filters
     * @return array{where: list<string>, params: array<string,mixed>, needs_actor: bool}
     */
    private function activityConditions(array $filters): array
    {
        $where = [];
        $params = [];
        $from = trim((string) ($filters['from'] ?? ''));
        $to = trim((string) ($filters['to'] ?? ''));
        $family = trim((string) ($filters['family'] ?? ''));
        $actorId = max(0, (int) ($filters['actor_id'] ?? 0));
        $courseId = max(0, (int) ($filters['course_id'] ?? 0));
        $companyId = max(0, (int) ($filters['company_id'] ?? 0));
        $query = trim((string) ($filters['q'] ?? ''));
        $eventId = max(0, (int) ($filters['event_id'] ?? 0));
        $afterId = max(0, (int) ($filters['after_id'] ?? 0));

        if ($eventId > 0) {
            $where[] = 'al.id=:event_id';
            $params['event_id'] = $eventId;
        }
        if ($afterId > 0) {
            $where[] = 'al.id>:after_id';
            $params['after_id'] = $afterId;
        }
        if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $from) === 1) {
            $where[] = 'al.created_at >= CAST(:from AS date)';
            $params['from'] = $from;
        }
        if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $to) === 1) {
            $where[] = "al.created_at < CAST(:to AS date) + INTERVAL '1 day'";
            $params['to'] = $to;
        }
        if ($family !== '' && preg_match('/^[a-z][a-z0-9_-]*$/', $family) === 1) {
            $where[] = "split_part(al.event_key,'.',1)=:family";
            $params['family'] = $family;
        }
        if ($actorId > 0) {
            $where[] = 'al.user_id=:actor_id';
            $params['actor_id'] = $actorId;
        }
        if ($courseId > 0) {
            $courseText = (string) $courseId;
            $params['course_direct'] = $courseText;
            $params['course_enrolment'] = $courseText;
            $params['course_assessment'] = $courseText;
            $params['course_request'] = $courseText;
            $where[] = "(
                al.metadata->>'course_id'=:course_direct
                OR EXISTS (SELECT 1 FROM course_enrolments ace WHERE ace.id::text=al.metadata->>'enrolment_id' AND ace.course_id::text=:course_enrolment)
                OR EXISTS (SELECT 1 FROM course_assessments aca WHERE aca.id::text=al.metadata->>'assessment_id' AND aca.course_id::text=:course_assessment)
                OR EXISTS (SELECT 1 FROM course_requests acr WHERE acr.id::text=al.metadata->>'request_id' AND acr.course_id::text=:course_request)
            )";
        }
        if ($companyId > 0) {
            $companyText = (string) $companyId;
            $params['company_direct'] = $companyText;
            $params['company_request'] = $companyText;
            $params['company_enrolment'] = $companyText;
            $params['company_actor'] = $companyText;
            $where[] = "(
                al.metadata->>'company_id'=:company_direct
                OR EXISTS (SELECT 1 FROM course_requests arq WHERE arq.id::text=al.metadata->>'request_id' AND arq.company_id::text=:company_request)
                OR EXISTS (
                    SELECT 1 FROM course_enrolments aen
                    JOIN company_users acu ON acu.user_id=aen.user_id AND acu.status='active'
                    WHERE aen.id::text=al.metadata->>'enrolment_id' AND acu.company_id::text=:company_enrolment
                )
                OR EXISTS (SELECT 1 FROM company_users acu2 WHERE acu2.user_id=al.user_id AND acu2.status='active' AND acu2.company_id::text=:company_actor)
            )";
        }
        if ($query !== '') {
            $like = '%' . $query . '%';
            $params['query_event'] = $like;
            $params['query_actor'] = $like;
            $params['query_metadata'] = $like;
            $where[] = "(al.event_key ILIKE :query_event OR COALESCE(NULLIF(trim(concat_ws(' ',u.first_name,u.last_name)),''),u.display_name,ue.email,'System') ILIKE :query_actor OR al.metadata::text ILIKE :query_metadata)";
        }


        // The actor joins are only ever referenced by the free-text condition above. Saying so here
        // lets the key query and the count leave them out when nothing needs them, which on a
        // hundred thousand audit entries is the difference between a two-second list and a
        // sixty-millisecond one: `user_emails` has no unique constraint on `user_id` alone, so
        // PostgreSQL cannot prove the LEFT JOIN adds no rows and has to perform it.
        return ['where' => $where, 'params' => $params, 'needs_actor' => $query !== ''];
    }

    /** The actor joins the Activity free-text search matches on. */
    private const ACTIVITY_ACTOR_JOINS = "\nLEFT JOIN users u ON u.id=al.user_id"
        . "\nLEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE";

    /**
     * One page of the Activity log for the given filters.
     *
     * @param array<string,mixed> $filters
     * @return list<array<string,mixed>>
     */
    public function activity(array $filters = [], int $limit = 250, int $offset = 0, ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::ACTIVITY_SORTS, self::ACTIVITY_ORDER, 'al.id DESC');
        ['where' => $where, 'params' => $params, 'needs_actor' => $needsActor] = $this->activityConditions($filters);
        
        // Deferred join. Every row of this list carries four COALESCE chains of correlated
        // sub-selects - up to fourteen lookups per row - to name the course, the company and the
        // subject a generic audit entry refers to. Evaluated across the whole filtered log in
        // order to display twenty-five entries, that is the single most expensive read on the
        // platform; evaluated for twenty-five ids it is nothing.
        $keys = 'SELECT al.id' . "\nFROM audit_log al" . ($needsActor ? self::ACTIVITY_ACTOR_JOINS : '');

        $detail = <<<'SQL'
SELECT al.id, al.event_key, al.metadata, al.created_at, al.user_id AS actor_user_id,
       COALESCE(host(al.ip_address), '') AS ip_address,
       COALESCE(NULLIF(trim(concat_ws(' ',u.first_name,u.last_name)),''),u.display_name,ue.email,'System') AS actor_name,
       COALESCE(
           (SELECT c.title FROM courses c WHERE c.id::text=al.metadata->>'course_id' LIMIT 1),
           (SELECT c.title FROM course_enrolments ce JOIN courses c ON c.id=ce.course_id WHERE ce.id::text=al.metadata->>'enrolment_id' LIMIT 1),
           (SELECT c.title FROM course_assessments ca JOIN courses c ON c.id=ca.course_id WHERE ca.id::text=al.metadata->>'assessment_id' LIMIT 1),
           (SELECT c.title FROM course_requests cr JOIN courses c ON c.id=cr.course_id WHERE cr.id::text=al.metadata->>'request_id' LIMIT 1)
       ) AS course_title,
       COALESCE(
           (SELECT co.name FROM companies co WHERE co.id::text=al.metadata->>'company_id' LIMIT 1),
           (SELECT co.name FROM course_requests cr JOIN companies co ON co.id=cr.company_id WHERE cr.id::text=al.metadata->>'request_id' LIMIT 1),
           (SELECT co.name FROM course_enrolments ce JOIN company_users cu ON cu.user_id=ce.user_id AND cu.status='active' JOIN companies co ON co.id=cu.company_id WHERE ce.id::text=al.metadata->>'enrolment_id' LIMIT 1),
           (SELECT co.name FROM company_users cu JOIN companies co ON co.id=cu.company_id WHERE cu.user_id=al.user_id AND cu.status='active' LIMIT 1)
       ) AS company_name,
       COALESCE(
           (SELECT COALESCE(NULLIF(trim(concat_ws(' ',tu.first_name,tu.last_name)),''),tu.display_name,te.email) FROM users tu LEFT JOIN user_emails te ON te.user_id=tu.id AND te.is_primary=TRUE WHERE tu.id::text=al.metadata->>'user_id' LIMIT 1),
           (SELECT COALESCE(NULLIF(trim(concat_ws(' ',eu.first_name,eu.last_name)),''),eu.display_name,ee.email) FROM course_enrolments ce JOIN users eu ON eu.id=ce.user_id LEFT JOIN user_emails ee ON ee.user_id=eu.id AND ee.is_primary=TRUE WHERE ce.id::text=al.metadata->>'enrolment_id' LIMIT 1)
       ) AS subject_user_name,
       split_part(al.event_key,'.',1) AS event_family
FROM page
JOIN audit_log al ON al.id=page.id
LEFT JOIN users u ON u.id=al.user_id
LEFT JOIN user_emails ue ON ue.user_id=u.id AND ue.is_primary=TRUE
SQL;

        if ($where !== []) {
            $keys .= ' WHERE ' . implode(' AND ', $where);
        }

        return $this->db->fetchAllAssociative(
            PageQuery::deferred($keys, $detail, $order, $limit, $offset),
            $params
        );
    }

    /**
     * Total Activity rows for the same filters as {@see activity()}.
     *
     * The two `LEFT JOIN`s are carried only when the free-text search condition is present, because
     * that condition is the only thing that references `u.first_name`, `u.last_name`,
     * `u.display_name` and `ue.email`. Dropping them unconditionally would make the count fail
     * whenever a term is set; carrying them unconditionally made every unsearched count pay for a
     * join it never read. The page query answers the same question the same way, so the two cannot
     * describe different populations.
     *
     * @param array<string,mixed> $filters
     */
    public function activityCount(array $filters = []): int
    {
        ['where' => $where, 'params' => $params, 'needs_actor' => $needsActor] = $this->activityConditions($filters);
        
        $sql = 'SELECT COUNT(*)::int AS total FROM audit_log al'
            . ($needsActor ? self::ACTIVITY_ACTOR_JOINS : '');
        if ($where !== []) $sql .= ' WHERE ' . implode(' AND ', $where);

        $rows = $this->db->fetchAllAssociative($sql, $params);

        return (int) ($rows[0]['total'] ?? 0);
    }

    /** @return list<string> */
    public function activityFamilies(): array
    {
        $rows = $this->db->fetchAllAssociative(
            "SELECT DISTINCT split_part(event_key,'.',1) AS family FROM audit_log WHERE event_key<>''"
            . '' . ' ORDER BY family'
        );
        return array_values(array_filter(array_map(static fn(array $row): string => (string) ($row['family'] ?? ''), $rows)));
    }

    /** @return array<string,int|float> */
    public function reportSummary(): array
    {
        // Report scalars are scoped exactly like the tables they summarise. An unscoped average
        // is worse than an unscoped list: it silently blends generated results into a genuine
        // performance figure with nothing on screen to suggest it happened.
        $enrolmentScope = '';
        $rows = $this->db->fetchAllAssociative(<<<SQL
SELECT
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE)::int AS enrolments,
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE AND status='assigned')::int AS assigned,
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE AND status='active')::int AS active,
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE AND status='completed')::int AS completed,
  (SELECT COUNT(*) FROM course_enrolments WHERE is_preview=FALSE AND status='cancelled')::int AS cancelled,
  (SELECT COUNT(*) FROM assessment_sessions s JOIN course_enrolments e ON e.id=s.enrolment_id WHERE e.is_preview=FALSE AND s.status='submitted' AND s.attempt_mode='graded'{$enrolmentScope})::int AS graded_assessments,
  COALESCE((SELECT ROUND(AVG(s.percentage),1) FROM assessment_sessions s JOIN course_enrolments e ON e.id=s.enrolment_id WHERE e.is_preview=FALSE AND s.status='submitted' AND s.attempt_mode='graded'{$enrolmentScope}),0)::float AS assessment_average,
  COALESCE((SELECT ROUND(100.0*AVG(CASE WHEN s.passed THEN 1 ELSE 0 END),1) FROM assessment_sessions s JOIN course_enrolments e ON e.id=s.enrolment_id WHERE e.is_preview=FALSE AND s.status='submitted' AND s.attempt_mode='graded'{$enrolmentScope}),0)::float AS assessment_pass_rate,
  (SELECT COUNT(*) FROM certificates WHERE revoked_at IS NULL)::int AS certificates
SQL);
        return $rows[0] ?? [];
    }

    /** @return list<array<string,mixed>> */
    public function courseReport(int $limit = 0, int $offset = 0, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::COURSE_REPORT_SORTS, self::COURSE_REPORT_ORDER, 'c.id');
        [$courseScope, $bindings] = self::searchFilter('c', $search, self::COURSE_REPORT_SEARCH);

        $detail = <<<'SQL'
SELECT c.id,c.title,c.status,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE)::int AS enrolments,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE AND ce.started_at IS NOT NULL)::int AS started,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE AND ce.status='completed')::int AS completed,
       COALESCE(ROUND(AVG(cr.overall_percentage) FILTER (WHERE ce.is_preview=FALSE),1),0)::float AS average_result
FROM %s
LEFT JOIN course_enrolments ce ON ce.course_id=c.id
LEFT JOIN course_results cr ON cr.enrolment_id=ce.id
%s
GROUP BY c.id
SQL;

        // A limit of zero means the whole report, which no screen asks for but the signature still
        // allows. There is nothing to defer in that case: every course is on the page.
        if ($limit <= 0) {
            return $this->db->fetchAllAssociative(
                sprintf($detail, 'courses c', $courseScope) . "\nORDER BY " . $order,
                $bindings
            );
        }

        return $this->db->fetchAllAssociative(
            PageQuery::deferred(
                'SELECT c.id FROM courses c' . $courseScope,
                sprintf($detail, 'page JOIN courses c ON c.id=page.id', ''),
                $order,
                $limit,
                $offset
            ),
            $bindings
        );
    }

    /**
     * The company's own course performance: how its staff are doing, course by course.
     *
     * The same report as {@see courseReport()} asked of one company. Every figure counts only
     * enrolments held by an active member of that company, and only courses at least one of them is
     * enrolled in appear at all - a company administrator asking how training is going is asking
     * about their own people, and a platform-wide figure on that screen would be somebody else's
     * answer to a question they did not ask.
     *
     * The membership predicate is repeated in the aggregate join and in every sort expression on
     * purpose. Sorting by a platform-wide count while displaying a company one would order the rows
     * by numbers that are not on the screen.
     *
     * @return list<array<string,mixed>>
     */
    public function companyCourseReport(int $companyId, int $limit, int $offset, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::companyCourseReportSorts(), self::COURSE_REPORT_ORDER, 'c.id');
        [$courseScope, $bindings] = self::searchFilter('c', $search, self::COURSE_REPORT_SEARCH);
        $bindings['report_company_id'] = $companyId;
        $where = $courseScope === ''
            ? ' WHERE ' . self::COMPANY_LEARNER_COURSE
            : $courseScope . ' AND ' . self::COMPANY_LEARNER_COURSE;

        $member = self::COMPANY_LEARNER_ENROLMENT;
        $detail = <<<SQL
SELECT c.id,c.title,c.status,
       COUNT(DISTINCT ce.id)::int AS enrolments,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.started_at IS NOT NULL)::int AS started,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.status='completed')::int AS completed,
       COALESCE(ROUND(AVG(cr.overall_percentage),1),0)::float AS average_result
FROM page
JOIN courses c ON c.id=page.id
LEFT JOIN course_enrolments ce ON ce.course_id=c.id AND ce.is_preview=FALSE AND {$member}
LEFT JOIN course_results cr ON cr.enrolment_id=ce.id
GROUP BY c.id
SQL;

        return $this->db->fetchAllAssociative(
            PageQuery::deferred('SELECT c.id FROM courses c' . $where, $detail, $order, $limit, $offset),
            $bindings
        );
    }

    /** Total rows behind {@see companyCourseReport()} under the identical scope and filter. */
    public function companyCourseReportCount(int $companyId, string $search = ''): int
    {
        [$where, $bindings] = self::searchFilter('c', $search, self::COURSE_REPORT_SEARCH);
        $bindings['report_company_id'] = $companyId;
        $where = $where === ''
            ? ' WHERE ' . self::COMPANY_LEARNER_COURSE
            : $where . ' AND ' . self::COMPANY_LEARNER_COURSE;
        $rows = $this->db->fetchAllAssociative('SELECT COUNT(*)::int AS total FROM courses c' . $where, $bindings);

        return (int) ($rows[0]['total'] ?? 0);
    }

    /** True for an enrolment held by an active member of the company being reported on. */
    private const COMPANY_LEARNER_ENROLMENT = "EXISTS (SELECT 1 FROM company_users rcu
                                                       WHERE rcu.user_id=ce.user_id
                                                         AND rcu.company_id=:report_company_id
                                                         AND rcu.status='active')";

    /** True for a course at least one active member of that company is enrolled in. */
    private const COMPANY_LEARNER_COURSE = "EXISTS (SELECT 1 FROM course_enrolments rce
                                                     JOIN company_users rcu ON rcu.user_id=rce.user_id
                                                      AND rcu.company_id=:report_company_id
                                                      AND rcu.status='active'
                                                    WHERE rce.course_id=c.id AND rce.is_preview=FALSE)";

    /**
     * The company report's sortable columns.
     *
     * The same keys as COURSE_REPORT_SORTS so one template and one view model serve both screens,
     * with every expression narrowed to the company's own members.
     *
     * @return array<string,string>
     */
    public static function companyCourseReportSorts(): array
    {
        $member = "AND EXISTS (SELECT 1 FROM company_users rcu
                                WHERE rcu.user_id=se.user_id
                                  AND rcu.company_id=:report_company_id
                                  AND rcu.status='active')";

        return [
            'course' => 'c.title',
            'status' => 'c.status',
            'enrolments' => "(SELECT COUNT(*) FROM course_enrolments se WHERE se.course_id=c.id AND se.is_preview=FALSE {$member})",
            'started' => "(SELECT COUNT(*) FROM course_enrolments se WHERE se.course_id=c.id AND se.is_preview=FALSE AND se.started_at IS NOT NULL {$member})",
            'completed' => "(SELECT COUNT(*) FROM course_enrolments se WHERE se.course_id=c.id AND se.is_preview=FALSE AND se.status='completed' {$member})",
            'average' => "(SELECT AVG(sr.overall_percentage) FROM course_results sr
                             JOIN course_enrolments se ON se.id=sr.enrolment_id
                            WHERE se.course_id=c.id AND se.is_preview=FALSE {$member})",
        ];
    }

    /** Total rows behind {@see courseReport()} under the identical scope and filter. */
    public function courseReportCount(string $search = ''): int
    {
        [$where, $bindings] = self::searchFilter('c', $search, self::COURSE_REPORT_SEARCH);
        $rows = $this->db->fetchAllAssociative('SELECT COUNT(*)::int AS total FROM courses c' . $where, $bindings);

        return (int) ($rows[0]['total'] ?? 0);
    }

    /** @return list<array<string,mixed>> */
    public function companyReport(int $limit = 0, int $offset = 0, string $search = '', ?SortOrder $sort = null): array
    {
        $order = self::orderFor($sort, self::COMPANY_REPORT_SORTS, self::COMPANY_REPORT_ORDER, 'co.id');
        $companyScope = '';
        [$match, $bindings] = self::andSearch($search, self::COMPANY_REPORT_SEARCH);
        $companyScope .= $match;

        $detail = <<<'SQL'
SELECT co.id,co.name,co.company_type,
       COUNT(DISTINCT cu.user_id) FILTER (WHERE cu.status='active')::int AS people,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE)::int AS enrolments,
       COUNT(DISTINCT ce.id) FILTER (WHERE ce.is_preview=FALSE AND ce.status='completed')::int AS completed
FROM %s
LEFT JOIN company_users cu ON cu.company_id=co.id
LEFT JOIN course_enrolments ce ON ce.user_id=cu.user_id
%s
GROUP BY co.id
SQL;

        if ($limit <= 0) {
            return $this->db->fetchAllAssociative(
                sprintf($detail, 'companies co', "WHERE co.status='active'" . $companyScope)
                . "\nORDER BY " . $order,
                $bindings
            );
        }

        return $this->db->fetchAllAssociative(
            PageQuery::deferred(
                "SELECT co.id FROM companies co WHERE co.status='active'" . $companyScope,
                sprintf($detail, 'page JOIN companies co ON co.id=page.id', ''),
                $order,
                $limit,
                $offset
            ),
            $bindings
        );
    }

    /** Total rows behind {@see companyReport()} under the identical scope and filter. */
    public function companyReportCount(string $search = ''): int
    {
        [$match, $bindings] = self::andSearch($search, self::COMPANY_REPORT_SEARCH);
        $rows = $this->db->fetchAllAssociative(
            "SELECT COUNT(*)::int AS total FROM companies co WHERE co.status='active'" . $match,
            $bindings
        );

        return (int) ($rows[0]['total'] ?? 0);
    }

    /**
     * Every favourite a learner holds, unbounded.
     *
     * The course pages use this to decide whether to draw one course as favourited, so they need
     * the whole set rather than a page of it. Screens that display the list use
     * {@see favouritesPage()} and {@see favouritesCount()}, which describe the same population
     * under the same scope.
     *
     * @return list<array<string,mixed>>
     */
    public function favourites(int $userId, string $search = ''): array
    {
        [$sql, $bindings] = self::favouritesQuery($userId, $search);

        return $this->db->fetchAllAssociative($sql . ' ORDER BY cf.created_at DESC', $bindings);
    }

    /**
     * One page of a learner's favourites.
     *
     * @return list<array<string,mixed>>
     */
    public function favouritesPage(int $userId, int $limit, int $offset, string $search = ''): array
    {
        [$sql, $bindings] = self::favouritesQuery($userId, $search);

        // `cf.course_id` completes the ordering: this table is keyed by the user and course pair
        // rather than by a surrogate id, and two favourites added in the same instant were free to
        // change places between one page view and the next.
        return $this->db->fetchAllAssociative(
            $sql . ' ORDER BY cf.created_at DESC, cf.course_id DESC' . $this->limitOffset($limit, $offset),
            $bindings
        );
    }

    /** Total favourites behind {@see favouritesPage()} under the identical scope and filter. */
    public function favouritesCount(int $userId, string $search = ''): int
    {
        [$sql, $bindings] = self::favouritesQuery($userId, $search, 'COUNT(*)::int AS total');
        $rows = $this->db->fetchAllAssociative($sql, $bindings);

        return (int) ($rows[0]['total'] ?? 0);
    }

    /**
     * The one membership rule behind every favourites read, so a page and its total cannot drift.
     *
     * @return array{0:string,1:array<string,mixed>}
     */
    private static function favouritesQuery(int $userId, string $search, string $select = 'c.*'): array
    {
        [$match, $bindings] = self::andSearch($search, self::COURSE_TITLE_SEARCH);

        return [
            'SELECT ' . $select . ' FROM course_favourites cf JOIN courses c ON c.id=cf.course_id
             WHERE cf.user_id=:user_id' . $match,
            ['user_id' => $userId] + $bindings,
        ];
    }

    /**
     * Every request a learner has raised, unbounded. See {@see favourites()} for why both an
     * unbounded and a paged read exist.
     *
     * @return list<array<string,mixed>>
     */
    public function userRequests(int $userId, string $search = ''): array
    {
        [$sql, $bindings] = self::userRequestsQuery($userId, $search);

        return $this->db->fetchAllAssociative($sql . ' ORDER BY cr.requested_at DESC', $bindings);
    }

    /**
     * One page of a learner's own course requests.
     *
     * @return list<array<string,mixed>>
     */
    public function userRequestsPage(int $userId, int $limit, int $offset, string $search = ''): array
    {
        [$sql, $bindings] = self::userRequestsQuery($userId, $search);

        return $this->db->fetchAllAssociative(
            $sql . ' ORDER BY cr.requested_at DESC, cr.id DESC' . $this->limitOffset($limit, $offset),
            $bindings
        );
    }

    /** Total requests behind {@see userRequestsPage()} under the identical scope and filter. */
    public function userRequestsCount(int $userId, string $search = ''): int
    {
        [$sql, $bindings] = self::userRequestsQuery($userId, $search, 'COUNT(*)::int AS total');
        $rows = $this->db->fetchAllAssociative($sql, $bindings);

        return (int) ($rows[0]['total'] ?? 0);
    }

    /**
     * @return array{0:string,1:array<string,mixed>}
     */
    private static function userRequestsQuery(int $userId, string $search, string $select = 'cr.*, c.title AS course_title, c.slug'): array
    {
        [$match, $bindings] = self::andSearch($search, self::COURSE_TITLE_SEARCH);

        return [
            'SELECT ' . $select . ' FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             WHERE cr.user_id=:user_id' . $match,
            ['user_id' => $userId] + $bindings,
        ];
    }

    public function toggleFavourite(int $userId, int $courseId): bool
    {
        $deleted = $this->db->fetchAllAssociative(
            'DELETE FROM course_favourites WHERE user_id=:user_id AND course_id=:course_id RETURNING course_id',
            ['user_id' => $userId, 'course_id' => $courseId]
        );
        if ($deleted !== []) {
            return false;
        }
        $this->db->executeStatement(
            'INSERT INTO course_favourites (user_id,course_id,created_at)
             VALUES (:user_id,:course_id,NOW()) ON CONFLICT (user_id,course_id) DO NOTHING',
            [
                'user_id' => $userId,
                'course_id' => $courseId,
                // The row's universe comes from the course, which is the resource it is about;
                // the identity holding it may be a genuine ADMIN from the other universe, which is
                // the D4 amendment of 2026/09/09 recorded in SeedTableCatalog.
            ]
        );
        return true;
    }

    public function createRequest(int $userId, ?int $companyId, int $courseId, int $accessPeriodSeconds, string $note): int
    {
        $open = (int) $this->db->fetchOne(
            "SELECT COUNT(*)::int FROM course_requests
              WHERE user_id = :user_id AND course_id = :course_id AND status IN ('pending','approved')",
            ['user_id' => $userId, 'course_id' => $courseId]
        );
        if ($open > 0) {
            throw new RuntimeException('You already have an open request for this course.');
        }

        $rows = $this->db->fetchAllAssociative(
            'INSERT INTO course_requests
                (public_id, user_id, company_id, course_id, access_period_seconds,
                 learner_note, decision_note, status, requested_at)
             VALUES
                (:public_id, :user_id, :company_id, :course_id, :access_period_seconds,
                 :learner_note, :decision_note, :status, :requested_at)
             RETURNING id',
            [
                'public_id' => Uuid::v4(),
                'user_id' => $userId,
                'company_id' => $companyId,
                'course_id' => $courseId,
                'access_period_seconds' => $accessPeriodSeconds,
                'learner_note' => trim($note),
                'decision_note' => '',
                'status' => 'pending',
                'requested_at' => gmdate('Y-m-d H:i:sP'),
            ]
        );

        return (int) ($rows[0]['id'] ?? 0);
    }

    /** @return array<string,mixed>|null */
    public function requestForUpdate(int $requestId): ?array
    {
        $rows = $this->db->fetchAllAssociative(
            'SELECT cr.*, c.title AS course_title, c.slug, ue.email, co.name AS company_name
             FROM course_requests cr
             JOIN courses c ON c.id=cr.course_id
             JOIN user_emails ue ON ue.user_id=cr.user_id AND ue.is_primary=TRUE
             LEFT JOIN companies co ON co.id=cr.company_id
             WHERE cr.id=:id FOR UPDATE OF cr',
            ['id' => $requestId]
        );
        return $rows[0] ?? null;
    }

    public function decideRequest(int $requestId, string $status, string $note, int $actorUserId, ?int $enrolmentId = null): void
    {
        $values = [
            'status' => $status,
            'decision_note' => trim($note),
            'decided_at' => gmdate('Y-m-d H:i:sP'),
            'decided_by_user_id' => $actorUserId,
        ];
        if ($enrolmentId !== null) {
            $values['enrolment_id'] = $enrolmentId;
            $values['fulfilled_at'] = gmdate('Y-m-d H:i:sP');
        }
        $assignments = implode(', ', array_map(static fn(string $c): string => $c . ' = :' . $c, array_keys($values)));

        $affected = $this->db->executeStatement(
            'UPDATE course_requests SET ' . $assignments . ' WHERE id = :id',
            $values + ['id' => $requestId]
        );
        if ($affected === 0) {
            throw new RuntimeException('The course request no longer exists.');
        }
    }

    /**
     * Whether this person is currently a member of this company.
     *
     * Checked before an assignment because the course id and the person id both arrive from a form,
     * and without it a company administrator could put anybody on the platform onto a course using
     * their own company's entitlement.
     */
    public function isActiveCompanyMember(int $companyId, int $userId): bool
    {
        $rows = $this->db->fetchAllAssociative(
            "SELECT 1 FROM company_users
              WHERE company_id = :company_id AND user_id = :user_id AND status = 'active' LIMIT 1",
            ['company_id' => $companyId, 'user_id' => $userId]
        );

        return $rows !== [];
    }

    /**
     * The address and course a newly enrolled learner should be told about.
     *
     * Read after the enrolment commits rather than carried out of the transaction, so the notice can
     * only ever describe something that actually happened.
     *
     * @return array<string,mixed>|null
     */
    public function learnerNotice(int $userId, int $courseId): ?array
    {
        $rows = $this->db->fetchAllAssociative(
            'SELECT ue.email, c.title AS course_title, c.slug
               FROM users u
               JOIN user_emails ue ON ue.user_id = u.id AND ue.is_primary = TRUE
               CROSS JOIN courses c
              WHERE u.id = :user_id AND c.id = :course_id
              LIMIT 1',
            ['user_id' => $userId, 'course_id' => $courseId]
        );

        return $rows[0] ?? null;
    }

    /**
     * Whether a company owns a course, and may therefore train its own staff on it for nothing.
     *
     * Ownership *is* the entitlement. A company that made a course has already paid for it by making
     * it, so approving one of its own staff onto it must not look for a credit, must not consume one
     * if a stray credit happens to exist, and must not leave the request in the limbo state that
     * "approved but no credit found" produces.
     *
     * See ROADMAP section 2c, owner decision of 2026/09/07.
     */
    public function companyOwnsCourse(int $companyId, int $courseId): bool
    {
        if ($companyId <= 0 || $courseId <= 0) {
            return false;
        }

        $rows = $this->db->fetchAllAssociative(
            'SELECT 1 AS owns FROM courses WHERE id = :course_id AND owner_company_id = :company_id LIMIT 1',
            ['course_id' => $courseId, 'company_id' => $companyId]
        );

        return $rows !== [];
    }

    /** @return array<string,mixed>|null */
    public function availableCredit(int $companyId, int $courseId, int $accessPeriodSeconds): ?array
    {
        // A correlated count keeps the candidate row lock legal in PostgreSQL.
        // GROUP BY queries cannot be combined safely with FOR UPDATE.
        $rows = $this->db->fetchAllAssociative(
            'SELECT cc.*,
                    (SELECT COUNT(*) FROM course_credit_allocations cca
                     WHERE cca.credit_id=cc.id AND cca.status IN (\'assigned\',\'consumed\'))::int AS used_count
             FROM course_credits cc
             WHERE cc.company_id=:company_id
               AND cc.course_id=:course_id
               AND cc.access_period_seconds=:period
               AND cc.quantity > (
                    SELECT COUNT(*) FROM course_credit_allocations cca
                    WHERE cca.credit_id=cc.id AND cca.status IN (\'assigned\',\'consumed\')
               )
             ORDER BY cc.created_at, cc.id
             FOR UPDATE OF cc SKIP LOCKED
             LIMIT 1',
            ['company_id' => $companyId, 'course_id' => $courseId, 'period' => $accessPeriodSeconds]
        );
        return $rows[0] ?? null;
    }

    public function allocateCredit(int $creditId, int $userId, int $enrolmentId, int $actorUserId): void
    {
        $this->db->executeStatement(
            'INSERT INTO course_credit_allocations
                ( credit_id, user_id, enrolment_id, status, assigned_by_user_id, assigned_at)
             VALUES
                ( :credit_id, :user_id, :enrolment_id, :status, :assigned_by_user_id, :assigned_at)',
            [
                'credit_id' => $creditId,
                'user_id' => $userId,
                'enrolment_id' => $enrolmentId,
                'status' => 'assigned',
                'assigned_by_user_id' => $actorUserId,
                'assigned_at' => gmdate('Y-m-d H:i:sP'),
            ]
        );
    }

    public function addCredit(?int $companyId, ?int $userId, int $courseId, int $period, int $quantity, string $reason, string $note, int $actorUserId): int
    {
        $rows = $this->db->fetchAllAssociative(
            'INSERT INTO course_credits
                (public_id, company_id, user_id, course_id, access_period_seconds,
                 quantity, source_type, note, created_by_user_id, created_at)
             VALUES
                (:public_id, :company_id, :user_id, :course_id, :access_period_seconds,
                 :quantity, :source_type, :note, :created_by_user_id, :created_at)
             RETURNING id',
            [
                'public_id' => Uuid::v4(),
                'company_id' => $companyId,
                'user_id' => $userId,
                'course_id' => $courseId,
                'access_period_seconds' => $period,
                'quantity' => $quantity,
                'source_type' => $reason,
                'note' => trim($note),
                'created_by_user_id' => $actorUserId,
                'created_at' => gmdate('Y-m-d H:i:sP'),
            ]
        );

        return (int) ($rows[0]['id'] ?? 0);
    }

    /** @return list<int> */
    public function activeCompanyUserEnrolmentIds(int $companyId, int $userId): array
    {
        $rows = $this->db->fetchAllAssociative(
            "SELECT ce.id
             FROM course_enrolments ce
             JOIN company_users cu ON cu.user_id=ce.user_id AND cu.company_id=:company_id
             WHERE ce.user_id=:user_id AND ce.is_preview=FALSE AND ce.status IN ('assigned','active','completed')",
            ['company_id' => $companyId, 'user_id' => $userId]
        );
        return array_map(static fn(array $row): int => (int) $row['id'], $rows);
    }

    public function removeEnrolmentAccess(int $enrolmentId, int $actorUserId, string $reason): void
    {
        $rows = $this->db->fetchAllAssociative(
            'UPDATE course_enrolments
                SET status = :status,
                    access_removed_at = :removed_at,
                    access_removed_by_user_id = :removed_by,
                    access_removed_reason = :reason,
                    updated_at = :updated_at
              WHERE id = :id AND is_preview = FALSE
             RETURNING started_at',
            [
                'status' => 'cancelled',
                'removed_at' => gmdate('Y-m-d H:i:sP'),
                'removed_by' => $actorUserId,
                'reason' => trim($reason),
                'updated_at' => gmdate('Y-m-d H:i:sP'),
                'id' => $enrolmentId,
            ]
        );
        if ($rows === []) {
            throw new RuntimeException('The enrolment does not exist.');
        }

        // A credit is only returned when the learner never started: starting consumes it
        // permanently, which is the rule CreditConsumptionRegressionTest defends.
        $startedAt = $rows[0]['started_at'] ?? null;
        if ($startedAt === null || $startedAt === '') {
            $this->db->executeStatement(
                "UPDATE course_credit_allocations
                 SET status='returned', returned_at=NOW()
                 WHERE enrolment_id=:enrolment_id AND status='assigned'",
                ['enrolment_id' => $enrolmentId]
            );
        }
    }

    public function restoreEnrolmentAccess(int $enrolmentId, int $actorUserId): void
    {
        $enrolment = $this->db->fetchAssociative(
            'SELECT id, user_id, course_id, started_at FROM course_enrolments
              WHERE id = :id AND is_preview = FALSE',
            ['id' => $enrolmentId]
        );
        if ($enrolment === false) {
            throw new RuntimeException('The enrolment does not exist.');
        }

        $duplicates = (int) $this->db->fetchOne(
            "SELECT COUNT(*)::int FROM course_enrolments
              WHERE id <> :id AND user_id = :user_id AND course_id = :course_id
                AND is_preview = FALSE AND status IN ('assigned','active','completed')",
            [
                'id' => $enrolmentId,
                'user_id' => (int) $enrolment['user_id'],
                'course_id' => (int) $enrolment['course_id'],
            ]
        );
        if ($duplicates > 0) {
            throw new RuntimeException('This learner already has active access to the course. Remove the duplicate access before restoring this enrolment.');
        }

        $startedAt = $enrolment['started_at'] ?? null;
        $this->db->executeStatement(
            'UPDATE course_enrolments
                SET status = :status,
                    access_removed_at = NULL,
                    access_removed_by_user_id = NULL,
                    access_removed_reason = :reason,
                    updated_at = :updated_at
              WHERE id = :id',
            [
                'status' => ($startedAt === null || $startedAt === '') ? 'assigned' : 'active',
                'reason' => '',
                'updated_at' => gmdate('Y-m-d H:i:sP'),
                'id' => $enrolmentId,
            ]
        );

        $this->db->executeStatement(
            "UPDATE course_credit_allocations
             SET status=CASE WHEN consumed_at IS NOT NULL OR status='consumed' THEN 'consumed' ELSE 'assigned' END,
                 returned_at=CASE WHEN consumed_at IS NULL AND status<>'consumed' THEN NULL ELSE returned_at END
             WHERE enrolment_id=:enrolment_id AND status IN ('returned','assigned','consumed')",
            ['enrolment_id' => $enrolmentId]
        );
    }
}