<?php

/*
Generated by: ChatGPT

Date time: 2026/08/12 23:56 SAST

Version: 0.5.7.5.1

Description:
Provides PostgreSQL persistence queries and data-access operations for login token records.

Changelog:
2026/08/12 23:56 SAST
- Updated source metadata for the Catto Learning 0.5.5 release.
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Updated source metadata for the Catto Learning 0.5.2 release.
2026/08/11 15:02 SAST
- Standardised this source file with the Catto Learning 0.5.1 SAST metadata header.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Persistence;


final class LoginTokenRepository
{
    public function __construct(private readonly Database $db)
    {
    }

    /** @param array<string,mixed> $context */
    public function create(
        string $tokenHash,
        string $email,
        string $purpose,
        ?int $userId,
        array $context,
        int $ttlSeconds,
        string $ipHash
    ): void {
        $this->db->executeStatement(
            'INSERT INTO auth_login_tokens
                (user_id, email, purpose, token_hash, context, expires_at, requested_ip_hash, created_at)
             VALUES
                (:user_id, :email, :purpose, :token_hash, :context, :expires_at, :requested_ip_hash, :created_at)',
            [
                'user_id' => $userId,
                'email' => $email,
                'purpose' => $purpose,
                'token_hash' => $tokenHash,
                'context' => json_encode($context, JSON_THROW_ON_ERROR),
                'expires_at' => gmdate('Y-m-d H:i:sP', time() + $ttlSeconds),
                'requested_ip_hash' => $ipHash,
                'created_at' => gmdate('Y-m-d H:i:sP'),
            ]
        );
    }

    /** @return array<string,mixed>|null */
    public function findUsableForUpdate(string $tokenHash, string $purpose): ?array
    {
        // SQL is required for the row lock that makes token consumption atomic.
        $row = $this->db->fetchAssociative(
            'SELECT * FROM auth_login_tokens
             WHERE token_hash = :token_hash AND purpose = :purpose AND used_at IS NULL AND expires_at > NOW()
             FOR UPDATE',
            ['token_hash' => $tokenHash, 'purpose' => $purpose]
        );

        return $row === false ? null : $row;
    }

    public function markUsed(int $id): void
    {
        $this->db->executeStatement(
            'UPDATE auth_login_tokens SET used_at = :used_at WHERE id = :id',
            ['used_at' => gmdate('Y-m-d H:i:sP'), 'id' => $id]
        );
    }

    public function deleteByHash(string $tokenHash): void
    {
        $this->db->executeStatement(
            'DELETE FROM auth_login_tokens WHERE token_hash = :token_hash AND used_at IS NULL',
            ['token_hash' => $tokenHash]
        );
    }

    public function recentEmailCount(string $email, int $windowSeconds): int
    {
        return (int) $this->db->fetchOne(
            'SELECT COUNT(*)::int FROM auth_login_tokens WHERE email = :email AND created_at > :since',
            ['email' => $email, 'since' => gmdate('Y-m-d H:i:sP', time() - $windowSeconds)]
        );
    }

    public function recentIpCount(string $ipHash, int $windowSeconds): int
    {
        return (int) $this->db->fetchOne(
            'SELECT COUNT(*)::int FROM auth_login_tokens WHERE requested_ip_hash = :ip_hash AND created_at > :since',
            ['ip_hash' => $ipHash, 'since' => gmdate('Y-m-d H:i:sP', time() - $windowSeconds)]
        );
    }

    public function prune(): int
    {
        // SQL is used because PostgreSQL interval arithmetic is clearer here.
        return $this->db->executeStatement(
            "DELETE FROM auth_login_tokens
             WHERE expires_at < NOW() - INTERVAL '7 days'
                OR used_at < NOW() - INTERVAL '7 days'"
        );
    }
}