<?php

/*
Generated by: ChatGPT

Date time: 2026/08/12 23:56 SAST

Version: 0.5.7.5

Description:
Provides PostgreSQL persistence queries and data-access operations for maintenance records.

Changelog:
2026/08/12 23:56 SAST
- Updated source metadata for the Catto Learning 0.5.5 release.
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Updated source metadata for the Catto Learning 0.5.2 release.
2026/08/11 15:02 SAST
- Standardised this source file with the Catto Learning 0.5.1 SAST metadata header.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Persistence;

use CattoLearning\Infrastructure\Persistence\M\AuthLoginTokensM;
use CattoLearning\Infrastructure\Persistence\M\AuthSessionsM;
use CattoLearning\Infrastructure\Persistence\M\WebSessionsM;
use DB\SQL;

final class MaintenanceRepository
{
    public function __construct(private readonly SQL $db)
    {
    }

    /** @return array{login_tokens:int,auth_sessions:int,web_sessions:int} */
    public function pending(int $webSessionTtl): array
    {
        $loginCutoff = gmdate('Y-m-d H:i:sP', time() - 7 * 86400);
        $authCutoff = gmdate('Y-m-d H:i:sP', time() - 30 * 86400);
        $webCutoff = gmdate('Y-m-d H:i:sP', time() - $webSessionTtl);

        $loginTokens = new AuthLoginTokensM($this->db);
        $authSessions = new AuthSessionsM($this->db);
        $webSessions = new WebSessionsM($this->db);

        return [
            'login_tokens' => $loginTokens->count([
                '(expires_at < ? OR used_at < ?)',
                $loginCutoff,
                $loginCutoff,
            ]),
            'auth_sessions' => $authSessions->count([
                '(expires_at < ? OR revoked_at < ?)',
                $authCutoff,
                $authCutoff,
            ]),
            'web_sessions' => $webSessions->count([
                'last_activity < ?',
                $webCutoff,
            ]),
        ];
    }

    /** @return array{login_tokens:int,auth_sessions:int,web_sessions:int} */
    public function prune(int $webSessionTtl): array
    {
        $pending = $this->pending($webSessionTtl);
        $loginCutoff = gmdate('Y-m-d H:i:sP', time() - 7 * 86400);
        $authCutoff = gmdate('Y-m-d H:i:sP', time() - 30 * 86400);
        $webCutoff = gmdate('Y-m-d H:i:sP', time() - $webSessionTtl);

        // SQL is used for efficient bulk deletion. This remains confined to a repository.
        $this->db->exec(
            'DELETE FROM auth_login_tokens WHERE expires_at < :cutoff OR used_at < :cutoff',
            [':cutoff' => $loginCutoff]
        );
        $this->db->exec(
            'DELETE FROM auth_sessions WHERE expires_at < :cutoff OR revoked_at < :cutoff',
            [':cutoff' => $authCutoff]
        );
        $this->db->exec(
            'DELETE FROM web_sessions WHERE last_activity < :cutoff',
            [':cutoff' => $webCutoff]
        );

        return $pending;
    }
}