<?php

/*
Generated by: Claude Code CLI

Date time: 2026/08/23 04:19 SAST

Version: 0.5.8

Description:
Provides PostgreSQL persistence queries and data-access operations for maintenance records.

Changelog:
2026/08/23 04:19 SAST
- Documented the database prune as deliberately universe-agnostic expired-session collection.
2026/08/12 23:56 SAST
- Updated source metadata for the Catto Learning 0.5.5 release.
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Updated source metadata for the Catto Learning 0.5.2 release.
2026/08/11 15:02 SAST
- Standardised this source file with the Catto Learning 0.5.1 SAST metadata header.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Persistence;

use CattoLearning\Infrastructure\Persistence\M\AuthLoginTokensM;
use CattoLearning\Infrastructure\Persistence\M\AuthSessionsM;
use CattoLearning\Infrastructure\Persistence\M\WebSessionsM;
use DB\SQL;

final class MaintenanceRepository
{
    public function __construct(private readonly SQL $db)
    {
    }

    /**
     * Expired authentication infrastructure awaiting collection.
     *
     * Deliberately universe-agnostic. These are expired sessions and spent login tokens, not
     * business records: an expired SEED session is as much rubbish as an expired REAL one, and
     * scoping the sweep would leave seed rubbish behind for cleanup to trip over. `web_sessions`
     * could not be scoped in any case - it is not seed-aware (decision D3) and has no identity
     * column to scope by.
     *
     * Disclosure is handled by the section rather than the query: this is reachable only through
     * Administration Settings, which requires SYSTEM.SETTING.VIEW and is therefore ADMIN-only.
     *
     * @return array{login_tokens:int,auth_sessions:int,web_sessions:int}
     */
    public function pending(int $webSessionTtl): array
    {
        $loginCutoff = gmdate('Y-m-d H:i:sP', time() - 7 * 86400);
        $authCutoff = gmdate('Y-m-d H:i:sP', time() - 30 * 86400);
        $webCutoff = gmdate('Y-m-d H:i:sP', time() - $webSessionTtl);

        $loginTokens = new AuthLoginTokensM($this->db);
        $authSessions = new AuthSessionsM($this->db);
        $webSessions = new WebSessionsM($this->db);

        return [
            'login_tokens' => $loginTokens->count([
                '(expires_at < ? OR used_at < ?)',
                $loginCutoff,
                $loginCutoff,
            ]),
            'auth_sessions' => $authSessions->count([
                '(expires_at < ? OR revoked_at < ?)',
                $authCutoff,
                $authCutoff,
            ]),
            'web_sessions' => $webSessions->count([
                'last_activity < ?',
                $webCutoff,
            ]),
        ];
    }

    /**
     * Deletes expired authentication infrastructure in both universes.
     *
     * Pruning by cutoff only. It never touches a business row and never consults a seed token, so
     * it cannot interfere with seed cleanup: a seed set's own rows are removed by
     * SeedRepository::deleteSet(), and outstanding login tokens for the identities being removed
     * are invalidated there by user rather than waiting for expiry here.
     *
     * @return array{login_tokens:int,auth_sessions:int,web_sessions:int}
     */
    public function prune(int $webSessionTtl): array
    {
        $pending = $this->pending($webSessionTtl);
        $loginCutoff = gmdate('Y-m-d H:i:sP', time() - 7 * 86400);
        $authCutoff = gmdate('Y-m-d H:i:sP', time() - 30 * 86400);
        $webCutoff = gmdate('Y-m-d H:i:sP', time() - $webSessionTtl);

        // SQL is used for efficient bulk deletion. This remains confined to a repository.
        $this->db->exec(
            'DELETE FROM auth_login_tokens WHERE expires_at < :cutoff OR used_at < :cutoff',
            [':cutoff' => $loginCutoff]
        );
        $this->db->exec(
            'DELETE FROM auth_sessions WHERE expires_at < :cutoff OR revoked_at < :cutoff',
            [':cutoff' => $authCutoff]
        );
        $this->db->exec(
            'DELETE FROM web_sessions WHERE last_activity < :cutoff',
            [':cutoff' => $webCutoff]
        );

        return $pending;
    }
}