<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/04 20:49 SAST

Version: 0.6

Description:
Composes the two-step SQL every paginated list in Catto Learning runs: pick the identifiers
belonging to the requested page first, then perform the joins, aggregates and correlated
sub-selects for those rows and no others.

Architectural boundary: a pure SQL-composition helper. It holds no connection, executes
nothing and knows nothing about routes, views or the Pagination value object beyond the
approved page sizes it clamps against. Only repositories call it.

Why this exists:

A list query written the obvious way joins and aggregates the whole filtered population and
then throws all but twenty-five rows away. Administration People joined six tables and grouped
them before its LIMIT, so page one of a hundred thousand people aggregated a hundred thousand
people's roles and enrolments to display twenty-five. The work is proportional to the dataset
rather than to the page, which is the property that makes a list unusable at volume and looks
like nothing at all on development data.

The fix is to run a cheap key query first - the same WHERE, the same ORDER BY, the same LIMIT
and OFFSET, but touching only the columns an index can serve - and then join outwards from that
small set. PostgreSQL calls this a deferred join. It is not an approximation: the two queries
describe exactly the same rows in exactly the same order.

The order expression is supplied once and used twice, in the key query and again in the detail
query. That is deliberate. The detail query re-joins the same tables, so its own row order is
whatever the join produces unless it is told; a second hand-written ORDER BY there would be free
to drift from the first, and a page whose rows are ordered differently from the keys that
selected them is a page of the right rows in the wrong sequence - which reads as rows randomly
moving between pages rather than as an ordering defect.

Changelog:
2026/09/04 20:49 SAST
- Created for the v0.6 Pagination 2.0 release.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Persistence;

use CattoLearning\Support\Pagination;

final class PageQuery
{
    /** The CTE name the detail query joins against. */
    public const KEYS = 'page';

    /**
     * The LIMIT/OFFSET clause for a paginated query.
     *
     * PostgreSQL rejects a text-bound parameter in LIMIT/OFFSET through this driver, so these
     * two values are the only ones interpolated into SQL anywhere in the persistence layer.
     * Callers must already have normalised them through {@see Pagination}; the clamp here is
     * defence in depth so no repository ever interpolates a value it has not itself constrained.
     */
    public static function limitOffset(int $limit, int $offset): string
    {
        $limit = max(1, min(max(Pagination::PAGE_SIZES), $limit));

        return ' LIMIT ' . $limit . ' OFFSET ' . max(0, $offset);
    }

    /**
     * Wraps a key query and a detail query into one deferred-join statement.
     *
     * @param string $keys   A complete SELECT returning exactly one identifier column named `id`,
     *                       carrying the dataset's WHERE clause but no ORDER BY, LIMIT or OFFSET
     *                       of its own.
     * @param string $detail A complete SELECT that joins `page` on the identifier and projects the
     *                       display columns, carrying no ORDER BY of its own.
     * @param string $order  The one ORDER BY expression, valid in both queries because both name
     *                       the same table aliases.
     */
    public static function deferred(string $keys, string $detail, string $order, int $limit, int $offset): string
    {
        return 'WITH ' . self::KEYS . " AS (\n"
            . $keys . "\nORDER BY " . $order . self::limitOffset($limit, $offset) . "\n)\n"
            . $detail . "\nORDER BY " . $order;
    }
}
