<?php
/*
Generated by: ChatGPT

Date time: 2026/08/19 01:13 SAST

Version: 0.5.7.4

Description:
Persists roles, user-role assignments and role-permission ACL mappings. Role keys are uppercase. ADMIN is recoverable and protected at the application layer.

Changelog:
2026/08/19 01:13 SAST
- Added role descriptions, permission queries, role CRUD and role-permission replacement.
- Renamed built-in role keys to uppercase, including ADMIN.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Persistence;

use DB\SQL;
use RuntimeException;
use Throwable;

/**
 * Database boundary for role membership and ACL assignment.
 */
final class RoleRepository
{
    public function __construct(private readonly SQL $db)
    {
    }

    public function assign(int $userId, string $role): void
    {
        $role = strtoupper(trim($role));
        if ($role === 'ADMIN') {
            $this->ensureAdminRole();
        }
        $rows = $this->db->exec('SELECT id FROM roles WHERE role_key=:role LIMIT 1', [':role' => $role]);
        if (!isset($rows[0])) {
            throw new RuntimeException('Unknown role: ' . $role);
        }
        $this->db->exec(
            'INSERT INTO user_roles (user_id,role_id,created_at) VALUES (:user_id,:role_id,NOW()) ON CONFLICT (user_id,role_id) DO NOTHING',
            [':user_id' => $userId, ':role_id' => (int) $rows[0]['id']]
        );
    }

    /** @return list<string> */
    public function roles(int $userId): array
    {
        $rows = $this->db->exec(
            'SELECT r.role_key FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=:user_id ORDER BY r.role_key',
            [':user_id' => $userId]
        );
        return array_values(array_map(static fn(array $row): string => (string) $row['role_key'], $rows));
    }

    /** @return list<string> */
    public function permissionsForUser(int $userId): array
    {
        $rows = $this->db->exec(
            'SELECT DISTINCT p.permission_key
             FROM user_roles ur
             JOIN role_permissions rp ON rp.role_id=ur.role_id
             JOIN permissions p ON p.id=rp.permission_id
             WHERE ur.user_id=:user_id
             ORDER BY p.permission_key',
            [':user_id' => $userId]
        );
        return array_values(array_map(static fn(array $row): string => (string) $row['permission_key'], $rows));
    }

    public function bootstrapAdministrator(int $userId, string $email, string $configuredAdminEmail): bool
    {
        if ($configuredAdminEmail === '' || strtolower($email) !== strtolower($configuredAdminEmail)) {
            return false;
        }

        // APP_ADMIN_EMAIL is the recovery identity, not merely the first user
        // who happened to receive ADMIN. Recreate the protected row when
        // necessary and ensure that configured identity is always mapped to it.
        $this->ensureAdminRole();
        $this->assign($userId, 'ADMIN');
        return true;
    }

    /**
     * Recreates the protected ADMIN row when only that row has been lost.
     */
    public function ensureAdminRole(): int
    {
        $rows = $this->db->exec(
            "INSERT INTO roles (role_key,role_name,role_description)
             VALUES ('ADMIN','Administrator','System Administrator')
             ON CONFLICT (role_key) DO UPDATE SET role_name=EXCLUDED.role_name, role_description=EXCLUDED.role_description
             RETURNING id"
        );
        return (int) ($rows[0]['id'] ?? 0);
    }

    public function revoke(int $userId, string $role): void
    {
        $role = strtoupper(trim($role));
        $rows = $this->db->exec('SELECT id FROM roles WHERE role_key=:role LIMIT 1', [':role' => $role]);
        if (!isset($rows[0])) {
            throw new RuntimeException('Unknown role: ' . $role);
        }
        $this->db->exec(
            'DELETE FROM user_roles WHERE user_id=:user_id AND role_id=:role_id',
            [':user_id' => $userId, ':role_id' => (int) $rows[0]['id']]
        );
    }

    public function countUsersWithRole(string $role): int
    {
        $rows = $this->db->exec(
            'SELECT COUNT(*)::int AS total FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE r.role_key=:role',
            [':role' => strtoupper(trim($role))]
        );
        return (int) ($rows[0]['total'] ?? 0);
    }

    public function countActiveUsersWithRole(string $role): int
    {
        $rows = $this->db->exec(
            "SELECT COUNT(*)::int AS total
             FROM user_roles ur JOIN roles r ON r.id=ur.role_id JOIN users u ON u.id=ur.user_id
             WHERE r.role_key=:role AND u.status='active'",
            [':role' => strtoupper(trim($role))]
        );
        return (int) ($rows[0]['total'] ?? 0);
    }

    /** @return list<array<string,mixed>> */
    public function all(): array
    {
        return $this->db->exec('SELECT id,role_key,role_name,role_description FROM roles ORDER BY CASE WHEN role_key=\'ADMIN\' THEN 0 ELSE 1 END, role_name');
    }

    /** @return list<array<string,mixed>> */
    public function allWithPermissionCounts(): array
    {
        return $this->db->exec(
            "SELECT r.id,r.role_key,r.role_name,r.role_description,
                    COUNT(DISTINCT ur.user_id)::int AS user_count,
                    COUNT(DISTINCT rp.permission_id)::int AS permission_count
             FROM roles r
             LEFT JOIN user_roles ur ON ur.role_id=r.id
             LEFT JOIN role_permissions rp ON rp.role_id=r.id
             GROUP BY r.id
             ORDER BY CASE WHEN r.role_key='ADMIN' THEN 0 ELSE 1 END,r.role_name"
        );
    }

    /** @return array<string,mixed>|null */
    public function findById(int $roleId): ?array
    {
        $rows = $this->db->exec(
            "SELECT r.id,r.role_key,r.role_name,r.role_description,
                    COUNT(DISTINCT ur.user_id)::int AS user_count
             FROM roles r LEFT JOIN user_roles ur ON ur.role_id=r.id
             WHERE r.id=:id GROUP BY r.id LIMIT 1",
            [':id' => $roleId]
        );
        return $rows[0] ?? null;
    }

    public function createRole(string $key, string $name, string $description): int
    {
        try {
            $rows = $this->db->exec(
                'INSERT INTO roles (role_key,role_name,role_description) VALUES (:key,:name,:description) RETURNING id',
                [':key' => $key, ':name' => $name, ':description' => $description]
            );
        } catch (Throwable $e) {
            throw new RuntimeException('Unable to create the role. The role key may already exist.', 0, $e);
        }
        return (int) ($rows[0]['id'] ?? 0);
    }

    public function updateRole(int $roleId, string $key, string $name, string $description): void
    {
        $this->db->exec(
            'UPDATE roles SET role_key=:key,role_name=:name,role_description=:description WHERE id=:id',
            [':key' => $key, ':name' => $name, ':description' => $description, ':id' => $roleId]
        );
    }

    public function deleteRole(int $roleId): void
    {
        $this->db->exec('DELETE FROM roles WHERE id=:id AND role_key<>\'ADMIN\'', [':id' => $roleId]);
    }

    /** @return list<string> */
    public function permissionKeysForRole(int $roleId): array
    {
        $rows = $this->db->exec(
            'SELECT p.permission_key FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role_id=:role_id ORDER BY p.permission_key',
            [':role_id' => $roleId]
        );
        return array_values(array_map(static fn(array $row): string => (string) $row['permission_key'], $rows));
    }

    /** @param list<string> $permissionKeys */
    public function replaceRolePermissions(int $roleId, array $permissionKeys): void
    {
        $this->db->begin();
        try {
            $this->db->exec('DELETE FROM role_permissions WHERE role_id=:role_id', [':role_id' => $roleId]);
            foreach ($permissionKeys as $key) {
                $this->db->exec(
                    'INSERT INTO role_permissions (role_id,permission_id)
                     SELECT :role_id,p.id FROM permissions p WHERE p.permission_key=:permission_key
                     ON CONFLICT (role_id,permission_id) DO NOTHING',
                    [':role_id' => $roleId, ':permission_key' => $key]
                );
            }
            $this->db->commit();
        } catch (Throwable $e) {
            $this->db->rollback();
            throw $e;
        }
    }

    /** @param list<string> $roles */
    public function replaceUserRoles(int $userId, array $roles): void
    {
        $allowed = array_map(static fn(array $row): string => (string) $row['role_key'], $this->all());
        $roles = array_values(array_unique(array_filter(
            array_map(static fn(string $role): string => strtoupper(trim($role)), $roles),
            static fn(string $role): bool => in_array($role, $allowed, true)
        )));
        $current = $this->roles($userId);
        foreach ($current as $role) {
            if (!in_array($role, $roles, true)) $this->revoke($userId, $role);
        }
        foreach ($roles as $role) $this->assign($userId, $role);
    }
}
