<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/09 20:10 SAST

Version: 0.7

Description:
Redirects mail addressed to an invented domain back to the platform's own domain.

Architectural boundary: infrastructure. It rewrites an address and nothing else - no transport, no
templates, no decision about whether to send.

Generated identities need addresses that look like addresses, which means inventing domains. Those
domains do not exist, so mail to them would bounce or, worse, leave for somewhere that does exist.
Every invented domain therefore ends in `.invalid`, which RFC 2606 reserves precisely so it can
never resolve, and this rewrites the domain to APP_DOMAIN on the way out. The local part is kept, so
the recipient is still recognisable in the inbox that receives it.

The rewrite is deliberately narrow. An address that is not recognisably invented is returned
untouched, because diverting a genuine address would be worse than any bounce.

Changelog:
2026/09/09 20:10 SAST
- Replaces GeneratedDomainRouter. Delivery now goes to APP_DOMAIN rather than a configured seed domain, and nothing here refers to seed data: there is one kind of data, and these are simply the domains the platform invents.
*/

declare(strict_types=1);

namespace CattoLearning\Infrastructure\Mail;

final class GeneratedDomainRouter
{
    /**
     * Suffix every invented domain ends with.
     *
     * Reserved by RFC 2606 so it can never resolve, which makes an un-rewritten address
     * undeliverable by construction rather than by convention.
     */
    public const GENERATED_DOMAIN_SUFFIX = '.invalid';

    public function __construct(private readonly string $deliveryDomain)
    {
    }

    /** True when this address belongs to a domain the platform invented. */
    public static function isGeneratedAddress(string $email): bool
    {
        $email = strtolower(trim($email));

        return $email !== '' && str_ends_with($email, self::GENERATED_DOMAIN_SUFFIX);
    }

    /**
     * The domain for one generated company.
     *
     * The run suffix and the company index both appear so the domain is unique across companies
     * within a run and across runs, which `companies.domain` requires globally.
     */
    public static function generatedDomain(string $companySlug, int $index, string $runSuffix): string
    {
        return $companySlug . '-' . $index . '-' . $runSuffix . self::GENERATED_DOMAIN_SUFFIX;
    }

    /**
     * The local part for one generated identity.
     *
     * Unique on its own, because the rewrite below discards the domain. The person's name is kept
     * so the address is still recognisable in an inbox.
     */
    public static function generatedLocalPart(string $nameSlug, int $index, string $runSuffix): string
    {
        return strtolower($nameSlug) . '.' . $index . '.' . $runSuffix;
    }

    /**
     * The address mail should actually be sent to.
     *
     * A real address is returned untouched. That is the important half: this must never rewrite
     * anything that is not recognisably invented, or genuine mail would be diverted.
     */
    public function deliveryAddress(string $email): string
    {
        if (!self::isGeneratedAddress($email) || $this->deliveryDomain === '') {
            return $email;
        }
        $at = strrpos($email, '@');
        if ($at === false || $at === 0) {
            return $email;
        }

        return substr($email, 0, $at) . '@' . $this->deliveryDomain;
    }

    /** True when a delivery domain is configured; without one, nothing is rewritten. */
    public function isConfigured(): bool
    {
        return $this->deliveryDomain !== '';
    }

    public function deliveryDomain(): string
    {
        return $this->deliveryDomain;
    }
}
