<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/10 02:20 SAST

Version: 0.7

Description:
A redirect thrown from anywhere in a controller, rather than returned from the end of one.

Architectural boundary: HTTP. It carries a path and a status and nothing else; RedirectListener
turns it into a response.

It exists because a guard has to be able to stop. `requireUser()` returns a CurrentUser, and the
signature is the point - a caller writes `$user = $this->requireUser()` and then uses `$user`
without a null check. Under Fat-Free the guard called exit(); under Symfony a controller must return
its response, so a guard that wanted to send the reader to the sign-in page had no way to do it
without every caller checking a return value and forwarding it. Two hundred call sites would then
each carry three lines of plumbing, and the one that forgot would carry on with no identity.

Deliberately extends Exception rather than RuntimeException: BaseController::handle() catches
RuntimeException to turn a domain failure into a flash message, and a redirect must pass straight
through that.

Changelog:
2026/09/10 02:20 SAST
- Created for the Fat-Free to Symfony route migration.
*/

declare(strict_types=1);

namespace CattoLearning\Http;

use Exception;

final class HttpRedirect extends Exception
{
    public function __construct(
        public readonly string $path,
        public readonly int $status = 303
    ) {
        parent::__construct('Redirect to ' . $path);
    }
}
