<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/09 20:40 SAST
- Dropped the cross-universe guard with the rest of the REAL/SEED split: there is one kind of data.
2026/09/07 20:00 SAST

Version: 0.6

Description:
Adds company favourites: courses a company is interested in for its staff but has not bought.

Additive. The v0.6 baseline is not touched, no table is dropped or recreated, and an installed
database upgrades by running this alone - which is the shape `release:validate` enforces.

Why this is a table of its own rather than a flag on the learner favourites.

A company favourite is a **company-to-course** relationship, not a favourite belonging to whichever
person happens to administer the company today. Modelled as a user favourite it would leave with that
person - owner decision, 2026/09/07: "the company admin chooses this. company staff who favourite
courses, do not affect company favourites."

Changelog:
2026/09/07 20:00 SAST
- Created for the v0.6 company favourites, ahead of Commerce.
*/

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class AddCompanyFavourites extends AbstractMigration
{
    public function up(): void
    {
        $this->execute(<<<'SQL'
CREATE TABLE company_favourites (
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    -- Who added it, kept for the audit trail and deliberately nullable: the person may leave the
    -- company or the platform, and the company's interest in the course outlives them.
    added_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (company_id, course_id)
);

-- The list is read company-first and newest-first, and the reverse index is the child side of the
-- course foreign key, which PostgreSQL never creates on its own.
CREATE INDEX company_favourites_company_created_idx
    ON company_favourites (company_id, created_at DESC, course_id DESC);
CREATE INDEX company_favourites_course_fk_idx ON company_favourites (course_id);
CREATE INDEX company_favourites_added_by_fk_idx ON company_favourites (added_by_user_id);

SQL);
    }

    public function down(): void
    {
        $this->execute('DROP TABLE IF EXISTS company_favourites');
    }
}
