<?php

/*
Generated by: Claude Code CLI

Date time: 2026/08/23 04:19 SAST

Version: 0.5.8

Description:
Turns one requested record volume into a coherent set of entity counts.

Architectural boundary: pure arithmetic. No SQL, no database, no randomness. The generator asks
this class how many of each root entity to build; everything below a root follows from fixed
per-entity shapes, so the projected total is deterministic and testable.

The requested volume is a soft whole-set target, not a quota per table. Referential integrity
wins: it is better to overshoot slightly than to emit a course with no modules or an enrolment
with no progress. Anything else would produce exactly the unrealistic data this feature exists
to avoid.

Changelog:
2026/08/23 04:19 SAST
- Created for the v0.5.8 Seed Database phase.
*/

declare(strict_types=1);

namespace CattoLearning\Seed;

final class SeedGenerationPlan
{
    /** Smallest set worth generating; below this the graph cannot show volume behaviour. */
    public const MINIMUM_VOLUME = 100;

    /**
     * Largest set one request may ask for.
     *
     * The generator runs in a single transaction, so an unbounded request would hold a long write
     * transaction on a development database. Generate several sets rather than one enormous one.
     *
     * This is a policy ceiling, not a memory one. The generator streams: it builds a chunk of rows,
     * writes it, keeps the generated ids and discards the rows, so its peak cost is set by
     * SeedGenerator::GENERATION_CHUNK rather than by the size of the request. A full 500,000-row
     * set peaks at about 58 MB against the deployed 128 MB limit.
     */
    public const MAXIMUM_VOLUME = 500000;

    public const DEFAULT_VOLUME = 5000;

    /** Fixed shape of one generated course. */
    public const LESSONS_PER_COURSE = 4;
    public const QUESTIONS_PER_ASSESSMENT = 4;
    public const OPTIONS_PER_QUESTION = 4;
    public const GRADE_BANDS_PER_COURSE = 4;

    /** Fixed shape of one generated enrolment that has been worked through. */
    public const ATTEMPTS_PER_ENROLMENT = 2;

    /**
     * The share of the requested volume that is people, and how the rest is apportioned.
     *
     * People are the figure the interface is judged on, so they are set as a fraction of the
     * request rather than falling out of a divisor: a request for 100,000 yields 7,500 of them,
     * inside the 5-10% band. Everything else is scaled from the same request.
     */
    private const PEOPLE_SHARE = 0.075;
    private const COURSE_SHARE = 0.010;
    private const ENROLMENT_SHARE = 0.080;
    private const FAVOURITE_SHARE = 0.030;
    private const REQUEST_SHARE = 0.030;
    private const CREDIT_SHARE = 0.015;

    /** People per company, which decides how many companies a request produces. */
    private const PEOPLE_PER_COMPANY = 8;

    /**
     * How much of the catalogue is a real course rather than a catalogue entry.
     *
     * A course with modules, assessments, questions and answer options costs about 126 rows; one
     * with only its metadata costs about seven. Giving every course the full treatment made a
     * thousand courses cost 126,000 rows on their own, which is why the old plan could only afford
     * three hundred of them. A minority are built out and the rest are listed, which is both
     * affordable and closer to a real catalogue, where most of what exists is not what anyone opens.
     */
    private const RICH_COURSE_SHARE = 0.15;

    /**
     * How many enrolments carry a full history of attempts, answers and progress.
     *
     * The other nine in ten are ordinary enrolments with no assessment activity, which is also
     * what a real cohort looks like: most people who are signed up have not finished.
     */
    private const WORKED_ENROLMENT_SHARE = 0.10;

    public readonly int $requestedVolume;
    public readonly int $companies;
    public readonly int $users;
    public readonly int $courses;

    /** Courses that get modules, assessments, questions and options. The rest are metadata only. */
    public readonly int $richCourses;

    public readonly int $enrolments;

    /** Enrolments that carry progress, attempts and answers. The rest are enrolments and nothing more. */
    public readonly int $workedEnrolments;

    public readonly int $requests;
    public readonly int $credits;
    public readonly int $favourites;

    /**
     * Audit entries, computed last as whatever is left of the budget.
     *
     * This is what makes a request land on the number that was asked for. Every other figure is a
     * ratio and each rounds independently, so their sum drifts; an audit row costs exactly one row
     * and references only rows that already exist, so it is the one quantity that can absorb the
     * difference without distorting the shape of the graph. A request for 100,000 now delivers
     * 100,000, rather than the 87,510 the previous plan promised and the projection mis-stated.
     */
    public readonly int $auditEntries;

    private function __construct(int $requestedVolume)
    {
        $this->requestedVolume = $requestedVolume;

        // Every figure is a share of the request rather than a divisor chosen to make a total
        // come out. The previous plan worked the other way round and it showed: a request for
        // 100,000 produced 1,282 people, because people were whatever was left after course
        // content had taken its share.
        $this->users = max(12, (int) round($requestedVolume * self::PEOPLE_SHARE));
        $this->companies = max(2, (int) round($this->users / self::PEOPLE_PER_COMPANY));
        $this->courses = max(3, (int) round($requestedVolume * self::COURSE_SHARE));
        $this->richCourses = max(1, min($this->courses, (int) round($this->courses * self::RICH_COURSE_SHARE)));

        // No more enrolments than there are people: the schema permits one open enrolment per
        // person and course, and a plan that asks for more would spend the difference colliding.
        $this->enrolments = max(2, min($this->users, (int) round($requestedVolume * self::ENROLMENT_SHARE)));
        $this->workedEnrolments = max(1, min($this->enrolments, (int) round($this->enrolments * self::WORKED_ENROLMENT_SHARE)));

        $this->favourites = max(2, min($this->users, (int) round($requestedVolume * self::FAVOURITE_SHARE)));
        $this->requests = max(2, min($this->users, (int) round($requestedVolume * self::REQUEST_SHARE)));
        $this->credits = max(2, (int) round($requestedVolume * self::CREDIT_SHARE));

        // Whatever is left. Never negative, and never zero: a set with no audit trail would leave
        // the Activity screen empty at every volume.
        $this->auditEntries = max(
            $this->users,
            $requestedVolume - $this->rowsBeforeAudit()
        );
    }

    /**
     * Every row the plan projects except the audit trail.
     *
     * Kept separate so the audit figure can be the remainder without projectedRows() having to
     * call itself.
     */
    private function rowsBeforeAudit(): int
    {
        return array_sum($this->businessRows());
    }

    /**
     * The projected rows for everything except audit_log.
     *
     * The assessment tables are projected from `workedEnrolments`, not from every enrolment. That
     * disagreement is the whole of the old 12.5% shortfall: the projection assumed each enrolment
     * produced attempts, sessions and answers, while the generator skipped every enrolment that had
     * not been started - exactly one third of them - so four tables under-delivered by precisely
     * that third and the operator was shown a total the generator never intended to write.
     *
     * @return array<string,int>
     */
    private function businessRows(): array
    {
        $lessons = $this->richCourses * self::LESSONS_PER_COURSE;
        $assessments = $this->richCourses * $this->assessmentsPerCourse();
        $questions = $assessments * self::QUESTIONS_PER_ASSESSMENT;
        $worked = $this->workedEnrolments;
        $completed = intdiv($worked, 3);

        return [
            'users' => $this->users,
            'user_emails' => $this->users,
            'user_roles' => $this->users,
            'companies' => $this->companies,
            'company_users' => $this->users,
            'courses' => $this->courses,
            'course_items' => $lessons + $assessments,
            'course_structure_nodes' => $lessons + $assessments,
            'course_item_placements' => $lessons + $assessments,
            'course_item_assessments' => $assessments,
            'assessment_questions' => $questions,
            'assessment_options' => $questions * self::OPTIONS_PER_QUESTION,
            'course_grade_bands' => $this->courses * self::GRADE_BANDS_PER_COURSE,
            'course_price_variants' => $this->courses,
            'course_editors' => $this->courses,
            'course_enrolments' => $this->enrolments,
            'assessment_attempts' => $worked * self::ATTEMPTS_PER_ENROLMENT,
            'assessment_responses' => $worked * self::ATTEMPTS_PER_ENROLMENT * self::QUESTIONS_PER_ASSESSMENT,
            'assessment_sessions' => $worked,
            'assessment_session_questions' => $worked * self::QUESTIONS_PER_ASSESSMENT,
            'course_results' => $completed,
            // One per completed enrolment. This used to project half of them, against a generator
            // that issued one each and carried a cap that never bound.
            'certificates' => $completed,
            'course_favourites' => $this->favourites,
            'course_requests' => $this->requests,
            'course_credits' => $this->credits,
            'course_credit_allocations' => $this->credits,
            'course_edit_history' => $this->courses,
        ];
    }

    /**
     * The volumes a request may ask for.
     *
     * @return array{minimum:int,maximum:int,default:int}
     */
    public static function bounds(): array
    {
        return [
            'minimum' => self::MINIMUM_VOLUME,
            'maximum' => self::MAXIMUM_VOLUME,
            'default' => self::DEFAULT_VOLUME,
        ];
    }

    public static function forVolume(mixed $requestedVolume): self
    {
        return new self(self::normaliseVolume($requestedVolume));
    }

    /**
     * Clamps an untrusted volume into the supported range.
     *
     * A malformed value falls back to the default rather than raising: this arrives from an
     * administration form, and a typo should not be an error page.
     */
    public static function normaliseVolume(mixed $value): int
    {
        if (is_int($value)) {
            $volume = $value;
        } elseif (is_string($value) && preg_match('/^\d+$/', trim($value)) === 1) {
            $volume = (int) trim($value);
        } else {
            return self::DEFAULT_VOLUME;
        }

        return max(self::MINIMUM_VOLUME, min(self::MAXIMUM_VOLUME, $volume));
    }

    /** Assessments per course: one per module plus one final. */
    public function assessmentsPerCourse(): int
    {
        return self::LESSONS_PER_COURSE + 1;
    }

    /**
     * Row count this plan is expected to produce, per table.
     *
     * Used to show the operator what they are about to create before they commit to it, and
     * asserted in tests so a change to the shape constants cannot silently change the volume
     * a given request produces.
     *
     * @return array<string,int>
     */
    public function projectedRows(): array
    {
        return $this->businessRows() + ['audit_log' => $this->auditEntries];
    }

    /**
     * Tags attached to each generated course.
     *
     * Not projected and not counted. A tag association carries no seed token - the tag itself is
     * shared with the genuine catalogue - so it is not part of the set's manifest, and the rows go
     * with their courses through the cascade rather than being removed by token.
     */
    public const TAGS_PER_COURSE = 3;


    public function projectedTotal(): int
    {
        return array_sum($this->projectedRows());
    }
}
