<?php

/*
Generated by: Claude Code CLI

Date time: 2026/08/23 04:19 SAST

Version: 0.5.8

Description:
Read-only entity lookup endpoint backing the Administration and Company entity pickers.

Returns a small HTML fragment of selectable results so htmx can swap it straight into the
page. It exists to replace the whole-table <select> controls that previously populated the
Activity filter bar, the Credits entry form and the person-profile company selector.

Architectural boundary: this controller performs authorisation and rendering only. All
matching happens in EntityLookupRepository, and every result is subject to the caller's
existing company/platform resource scope.

The route is GET and read-only, so it carries no CSRF token. Every state-changing form that
consumes a selected id remains POST + CSRF protected; this endpoint cannot change state.

Changelog:
2026/08/23 04:19 SAST
- Threaded the Seed Database data universe through this file so every business read states which universe it means.
2026/08/20 20:02 SAST
- Created for the v0.5.7.6 pagination and large-data UI foundations release.
*/

declare(strict_types=1);

namespace CattoLearning\Http\Controller;

use CattoLearning\Application\PlatformAdministrationService;
use Symfony\Component\HttpFoundation\RequestStack;
use CattoLearning\Auth\AuthService;
use CattoLearning\Auth\CurrentUser;
use CattoLearning\Infrastructure\Persistence\CompanyRepository;
use CattoLearning\Infrastructure\Persistence\EntityLookupRepository;
use CattoLearning\View\ThemeRenderer;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Attribute\Route;

final class AdminLookupController extends BaseController
{
    /**
     * The permission required to search each entity type.
     *
     * Searching an entity is a read of that entity, so each type reuses the ordinary .VIEW
     * permission for its resource. A .VIEW permission must never authorise a write, and this
     * endpoint performs none.
     *
     * @var array<string,string>
     */
    private const TYPE_PERMISSIONS = [
        'people' => 'PLATFORM.PERSON.VIEW',
        'companies' => 'PLATFORM.COMPANY.VIEW',
        'courses' => 'COURSE.MANAGEMENT.VIEW',
    ];

    public function __construct(
        AuthService $auth,
        ThemeRenderer $view,
        RequestStack $requests,
        private readonly PlatformAdministrationService $platformAdministration,
        private readonly CompanyRepository $companies
    ) {
        parent::__construct($auth, $view, $requests);
    }

    /**
     * Searches one entity type and renders the results fragment.
     *
     * Responds 400 for an unknown entity type rather than silently returning nothing, because
     * htmx swaps error responses by default and a silent empty list would look like "no
     * matches" instead of "you asked for something that does not exist".
     *
     */
    #[Route('/admin/lookup/{type}', name: 'admin_lookup_search', requirements: ['type' => '[a-zA-Z0-9_-]+'], methods: ['GET'])]
    public function search(): Response
    {
        $type = strtolower(trim($this->param('type')));
        if (!EntityLookupRepository::isSupportedType($type)) {
            throw new BadRequestHttpException('Unknown lookup type.');
        }

        $user = $this->requirePermission(self::TYPE_PERMISSIONS[$type]);
        $query = (string) ($_GET['q'] ?? '');
        $target = preg_replace('/[^a-z0-9_-]/i', '', (string) ($_GET['target'] ?? '')) ?? '';

        $results = $this->platformAdministration->lookupEntities($type, $query, $this->scopeCompanyId($user));

        return $this->renderFragment('partials/entity-lookup-results', [
            'lookup_type' => $type,
            'lookup_target' => $target,
            'lookup_query' => trim($query),
            'lookup_results' => $results,
            'lookup_min_length' => EntityLookupRepository::MIN_QUERY_LENGTH,
            'lookup_max_results' => EntityLookupRepository::MAX_RESULTS,
            'lookup_searched' => mb_strlen(trim($query)) >= EntityLookupRepository::MIN_QUERY_LENGTH,
        ]);
    }

    /**
     * Resolves the company a lookup must be restricted to.
     *
     * A platform-wide operator searches everything. Anyone else is confined to their own
     * company, so a company-scoped role cannot enumerate people or courses outside it.
     */
    private function scopeCompanyId(CurrentUser $user): int
    {
        if ($user->hasPermission('PLATFORM.DASHBOARD.VIEW')) return 0;

        $company = $this->companies->findForUser($user->id);

        // A user with no active company gets an impossible scope rather than a platform-wide
        // one: failing closed is the only safe default for a search endpoint.
        return $company === null ? -1 : (int) $company['id'];
    }
}
