<?php

/*
Generated by: ChatGPT

Date time: 2026/09/06 15:00 SAST

Version: 0.6

Description:
Handles platform-administrator course-category management, including full category CRUD, ordering, activation, safe reassignment before deletion, and inline category creation used by course authoring and import forms.

Changelog:

2026/09/08 10:00 SAST

- Removed the taxonomy distribution chart.
2026/09/07 02:45 SAST
- The taxonomy screen shows how the published catalogue is spread across its top-level branches, with the uncategorised remainder.
2026/09/06 15:00 SAST
- Course categories became a three-level hierarchy and stopped carrying a data universe. Course counts beside a category name are scoped to the reader's universe; the label itself is not.
2026/08/12 23:56 SAST
- Updated source metadata for the Catto Learning 0.5.5 release.
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Added administrator course-category management for Catto Learning 0.5.2.
- Added an inline JSON category-creation endpoint for course creation, editing and import workflows.
*/

declare(strict_types=1);

namespace CattoLearning\Http\Controller;

use CattoLearning\Course\CourseService;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Attribute\Route;

use CattoLearning\View\ThemeRenderer;

use CattoLearning\Auth\AuthService;


use InvalidArgumentException;
use RuntimeException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;

final class AdminCourseCategoryController extends BaseController
{
    public function __construct(
        AuthService $auth,
        ThemeRenderer $view,
        RequestStack $requests,
        private readonly CourseService $courses
    ) {
        parent::__construct($auth, $view, $requests);
    }


    #[Route('/admin/courses/categories', name: 'admin_course_category_index', methods: ['GET'])]
    public function index(): Response
    {
        $user = $this->requirePermission('COURSE.CATEGORY.MANAGE');
        // The All/Real/Seed control, for the same reason the tags screen has one: the label is
        // shared and the courses filed under it are not, so a screen with no selector counts REAL
        // only and reports zero against every category of a generated catalogue.

        return $this->render('admin-course-categories', [
            'title' => 'Course categories',
            'course_group' => 'categories',
            // Counted in the reader's universe. The label is shared; what is filed under it is
            // not, so a genuine administrator viewing REAL must not be shown generated courses in
            // the tally beside a category name.
            'categories' => $this->courses->categories(),
            'parent_options' => $this->courses->categoryParentOptions(),
        ]);
    }


    #[Route('/admin/courses/categories', name: 'admin_course_category_create', methods: ['POST'])]
    public function create(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('COURSE.CATEGORY.MANAGE');
        return $this->handle(function () use ($user): void {
            $category = $this->courses->createCategory($_POST, $user->id);
            $this->flash('success', 'The course category “' . (string) $category['name'] . '” was created.');
            $this->redirect('/admin/courses/categories');
        }, '/admin/courses/categories');
    }


    #[Route('/admin/courses/categories/{id}', name: 'admin_course_category_edit', requirements: ['id' => '\\d+'], methods: ['GET'])]
    public function edit(): Response
    {
        $user = $this->requirePermission('COURSE.CATEGORY.MANAGE');
        $categoryId = $this->categoryId();
        $category = $this->courses->category($categoryId);
        $replacementCategories = array_values(array_filter(
            $this->courses->categories(),
            static fn(array $candidate): bool => (int) $candidate['id'] !== $categoryId
        ));
        return $this->render('admin-course-category-edit', [
            'title' => 'Edit category · ' . (string) $category['name'],
            'course_group' => 'categories',
            'category' => $category,
            'replacement_categories' => $replacementCategories,
            // Everything this category may be filed under: never itself, never one of its own
            // sub-categories, and never a category that is already at the deepest level.
            'parent_options' => $this->courses->categoryParentOptions($categoryId),
        ]);
    }


    #[Route('/admin/courses/categories/{id}', name: 'admin_course_category_update', requirements: ['id' => '\\d+'], methods: ['POST'])]
    public function update(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('COURSE.CATEGORY.MANAGE');
        $categoryId = $this->categoryId();
        return $this->handle(function () use ($user, $categoryId): void {
            $this->courses->updateCategory($categoryId, $_POST, $user->id);
            $this->flash('success', 'The course category was updated.');
            $this->redirect('/admin/courses/categories/' . $categoryId);
        }, '/admin/courses/categories/' . $categoryId);
    }


    #[Route('/admin/courses/categories/{id}/move', name: 'admin_course_category_move', requirements: ['id' => '\\d+'], methods: ['POST'])]
    public function move(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('COURSE.CATEGORY.MANAGE');
        $categoryId = $this->categoryId();
        return $this->handle(function () use ($user, $categoryId): void {
            $this->courses->moveCategory($categoryId, trim((string) ($_POST['direction'] ?? '')), $user->id);
            $this->redirect('/admin/courses/categories');
        }, '/admin/courses/categories');
    }


    #[Route('/admin/courses/categories/{id}/delete', name: 'admin_course_category_delete', requirements: ['id' => '\\d+'], methods: ['POST'])]
    public function delete(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('COURSE.CATEGORY.MANAGE');
        $categoryId = $this->categoryId();
        $replacement = (int) ($_POST['replacement_category_id'] ?? 0);
        return $this->handle(function () use ($user, $categoryId, $replacement): void {
            $this->courses->deleteCategory($categoryId, $replacement > 0 ? $replacement : null, $user->id);
            $this->flash('success', 'The course category was deleted.');
            $this->redirect('/admin/courses/categories');
        }, '/admin/courses/categories/' . $categoryId);
    }


    #[Route('/admin/courses/categories/inline', name: 'admin_course_category_inline_create', methods: ['POST'])]
    public function inlineCreate(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('COURSE.CATEGORY.MANAGE');

        // The one JSON answer outside /api/v1: the category picker creates a category without
        // leaving the form it is sitting in, so the caller is this platform's own JavaScript.
        try {
            $category = $this->courses->createCategory($_POST, $user->id);

            return new JsonResponse([
                'category' => [
                    'id' => (int) $category['id'],
                    'name' => (string) $category['name'],
                    'slug' => (string) $category['slug'],
                ],
            ], Response::HTTP_CREATED);
        } catch (InvalidArgumentException|RuntimeException $e) {
            return new JsonResponse(['error' => $e->getMessage()], Response::HTTP_UNPROCESSABLE_ENTITY);
        }
    }

    private function categoryId(): int
    {
        $categoryId = (int) $this->param('id');
        if ($categoryId < 1) {
            throw new InvalidArgumentException('The course category does not exist.');
        }
        return $categoryId;
    }
}