<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/09 23:25 SAST

Version: 0.7

Description:
The Seed Database screen: fills an empty installation with a coherent graph of data.

Architectural boundary: HTTP. It checks the permission and the CSRF token, hands the request to
SeedDatabaseService and renders. It owns no generation logic and no SQL.

What this screen no longer has is sets, tokens and cleanup. Generated rows are ordinary rows now, so
there is nothing to clean up by provenance - the database is disposable during development and is
reset wholesale when it needs to be. What it does have, and the reason it exists, is the button that
puts data on the screens so they can be judged with something in them.

Changelog:
2026/09/09 23:25 SAST
- Rebuilt after the REAL/SEED split was removed. Generation kept; per-set listing, detail and cleanup dropped with the tokens they were keyed on.
*/

declare(strict_types=1);

namespace CattoLearning\Http\Controller;

use Base;
use CattoLearning\Application\AdministrationSectionRegistry;
use CattoLearning\Auth\AuthService;
use CattoLearning\Seed\SeedDatabaseService;
use CattoLearning\View\ThemeRenderer;

final class AdminSeedController extends BaseController
{
    public function __construct(
        Base $f3,
        AuthService $auth,
        ThemeRenderer $view,
        private readonly SeedDatabaseService $seeds,
        private readonly AdministrationSectionRegistry $adminSections
    ) {
        parent::__construct($f3, $auth, $view);
    }

    /** The standalone Seed Database section. */
    public function index(): void
    {
        $this->requirePermission('SYSTEM.SEED.VIEW');

        $this->render('admin-section', $this->sectionData() + [
            'title' => 'Seed Database · Administration',
            'page_title' => 'Seed Database',
            'page_kicker' => 'Platform administration',
            'admin_section' => $this->adminSections->get('seed'),
            'admin_layout' => 'section',
        ]);
    }

    /**
     * Generates one set of data.
     *
     * The time limit is lifted for this request only. Generation at volume takes a while, and this
     * is a deliberate ADMIN-only maintenance action on a disposable database rather than something
     * an ordinary request path can reach.
     */
    public function generate(): void
    {
        $this->requireCsrf();
        $user = $this->requirePermission('SYSTEM.SEED.MANAGE');

        $this->handle(function () use ($user): void {
            set_time_limit(0);
            $result = $this->seeds->generate(
                $_POST['volume'] ?? null,
                (string) ($_POST['description'] ?? ''),
                $user->id
            );

            $this->flash('success', sprintf(
                'Generated %s records in %.1f seconds.',
                number_format($result['records']),
                $result['seconds']
            ));
            $this->redirect('/admin/seed');
        }, '/admin/seed');
    }

    /** @return array<string,mixed> */
    private function sectionData(): array
    {
        return ['seed_volume' => $this->seeds->volumeBounds()];
    }
}
