<?php

/*
Generated by: ChatGPT

Date time: 2026/08/23 04:19 SAST

Version: 0.5.8

Description:
Handles web requests for assessment operations, enforcing access rules and coordinating Catto Learning application services and views.

Changelog:
2026/08/23 04:19 SAST
- Threaded the Seed Database data universe through this file so every business read states which universe it means.
2026/08/12 23:56 SAST
- Updated source metadata for the Catto Learning 0.5.5 release.
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Updated source metadata for the Catto Learning 0.5.2 release.
2026/08/11 15:02 SAST
- Standardised this source file with the Catto Learning 0.5.1 SAST metadata header.
*/

declare(strict_types=1);

namespace CattoLearning\Http\Controller;

use CattoLearning\Course\AssessmentService;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Attribute\Route;

use CattoLearning\View\ThemeRenderer;

use CattoLearning\Auth\AuthService;

use Symfony\Component\HttpFoundation\Response;

final class AssessmentController extends BaseController
{
    public function __construct(
        AuthService $auth,
        ThemeRenderer $view,
        RequestStack $requests,
        private readonly AssessmentService $assessments
    ) {
        parent::__construct($auth, $view, $requests);
    }


    #[Route('/learn/{slug}/module/{position}/assessment', name: 'assessment_module_overview', requirements: ['slug' => '[a-zA-Z0-9_-]+', 'position' => '\\d+'], methods: ['GET'])]
    public function moduleOverview(): Response
    {
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $position = (int) $this->param('position');
        $preview = $this->previewMode();
        return $this->handle(function () use ($user, $slug, $position, $preview): Response {
            $data = $this->assessments->moduleOverview($user->id, $slug, $position, $preview);
            return $this->render('assessment-overview', $this->viewData($data, $slug, $preview) + [
                'title' => (string) $data['assessment']['title'],
                'start_action' => '/learn/' . rawurlencode($slug) . '/module/' . $position . '/assessment/start' . $this->previewQuery($preview),
                'back_url' => '/learn/' . rawurlencode($slug) . '/module/' . $position . $this->previewQuery($preview),
            ]);
        }, '/learn/' . rawurlencode($slug) . '/module/' . $position . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/diagnostic/{key}', name: 'assessment_diagnostic_overview', requirements: ['slug' => '[a-zA-Z0-9_-]+', 'key' => '[a-zA-Z0-9_-]+'], methods: ['GET'])]
    public function diagnosticOverview(): Response
    {
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $key = (string) $this->param('key');
        $preview = $this->previewMode();
        return $this->handle(function () use ($user, $slug, $key, $preview): Response {
            $data = $this->assessments->diagnosticOverview($user->id, $slug, $key, $preview);
            return $this->render('assessment-overview', $this->viewData($data, $slug, $preview) + [
                'title' => (string) $data['assessment']['title'],
                'start_action' => '/learn/' . rawurlencode($slug) . '/diagnostic/' . rawurlencode($key) . '/start' . $this->previewQuery($preview),
                'back_url' => '/learn/' . rawurlencode($slug) . $this->previewQuery($preview),
                'is_diagnostic' => true,
            ]);
        }, '/learn/' . rawurlencode($slug) . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/diagnostic/{key}/start', name: 'assessment_start_diagnostic', requirements: ['slug' => '[a-zA-Z0-9_-]+', 'key' => '[a-zA-Z0-9_-]+'], methods: ['POST'])]
    public function startDiagnostic(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $key = (string) $this->param('key');
        $preview = $this->previewMode();
        return $this->handle(function () use ($user, $slug, $key, $preview): void {
            $session = $this->assessments->startDiagnosticAttempt($user->id, $slug, $key, $preview);
            $this->redirect('/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode((string) $session['public_id']) . $this->previewQuery($preview));
        }, '/learn/' . rawurlencode($slug) . '/diagnostic/' . rawurlencode($key) . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/final/assessment', name: 'assessment_final_overview', requirements: ['slug' => '[a-zA-Z0-9_-]+'], methods: ['GET'])]
    public function finalOverview(): Response
    {
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $preview = $this->previewMode();
        return $this->handle(function () use ($user, $slug, $preview): Response {
            $data = $this->assessments->finalOverview($user->id, $slug, $preview);
            return $this->render('assessment-overview', $this->viewData($data, $slug, $preview) + [
                'title' => (string) $data['assessment']['title'],
                'start_action' => '/learn/' . rawurlencode($slug) . '/final/assessment/start' . $this->previewQuery($preview),
                'back_url' => '/learn/' . rawurlencode($slug) . $this->previewQuery($preview),
            ]);
        }, '/learn/' . rawurlencode($slug) . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/module/{position}/assessment/start', name: 'assessment_start_module', requirements: ['slug' => '[a-zA-Z0-9_-]+', 'position' => '\\d+'], methods: ['POST'])]
    public function startModule(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $position = (int) $this->param('position');
        $preview = $this->previewMode();
        $mode = (string) ($_POST['mode'] ?? 'graded');
        return $this->handle(function () use ($user, $slug, $position, $preview, $mode): void {
            $session = $this->assessments->startModuleAttempt($user->id, $slug, $position, $mode, $preview);
            $this->redirect('/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode((string) $session['public_id']) . $this->previewQuery($preview));
        }, '/learn/' . rawurlencode($slug) . '/module/' . $position . '/assessment' . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/final/assessment/start', name: 'assessment_start_final', requirements: ['slug' => '[a-zA-Z0-9_-]+'], methods: ['POST'])]
    public function startFinal(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $preview = $this->previewMode();
        $mode = (string) ($_POST['mode'] ?? 'graded');
        return $this->handle(function () use ($user, $slug, $preview, $mode): void {
            $session = $this->assessments->startFinalAttempt($user->id, $slug, $mode, $preview);
            $this->redirect('/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode((string) $session['public_id']) . $this->previewQuery($preview));
        }, '/learn/' . rawurlencode($slug) . '/final/assessment' . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/assessment/session/{session}', name: 'assessment_session', requirements: ['slug' => '[a-zA-Z0-9_-]+', 'session' => '\\d+'], methods: ['GET'])]
    public function session(): Response
    {
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $publicId = (string) $this->param('session');
        $preview = $this->previewMode();
        return $this->handle(function () use ($user, $slug, $publicId, $preview): Response {
            $session = $this->assessments->session($user->id, $publicId);
            if ((string) $session['status'] !== 'in_progress') {
                $this->redirect('/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode($publicId) . '/result' . $this->previewQuery($preview));
            }
            $feedback = is_array($_SESSION['assessment_feedback'] ?? null) ? $_SESSION['assessment_feedback'] : null;
            unset($_SESSION['assessment_feedback']);
            return $this->render('assessment-question', [
                'title' => (string) $session['assessment_title'],
                'session' => $session,
                'question' => $session['question'],
                'feedback' => $feedback,
                'respond_action' => '/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode($publicId) . '/respond' . $this->previewQuery($preview),
                'finish_action' => '/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode($publicId) . '/finish' . $this->previewQuery($preview),
                'is_preview' => $preview,
                'preview_query' => $this->previewQuery($preview),
                'load_assessment_timer' => true,
            ]);
        }, '/learn/' . rawurlencode($slug) . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/assessment/session/{session}/respond', name: 'assessment_respond', requirements: ['slug' => '[a-zA-Z0-9_-]+', 'session' => '\\d+'], methods: ['POST'])]
    public function respond(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $publicId = (string) $this->param('session');
        $preview = $this->previewMode();
        $questionId = (int) ($_POST['question_id'] ?? 0);
        $skip = isset($_POST['skip']);
        $optionId = isset($_POST['option_id']) ? (int) $_POST['option_id'] : null;
        return $this->handle(function () use ($user, $slug, $publicId, $preview, $questionId, $optionId, $skip): void {
            $next = $this->assessments->respond($user->id, $publicId, $questionId, $optionId, $skip);
            if (isset($next['feedback']) && is_array($next['feedback'])) {
                $_SESSION['assessment_feedback'] = $next['feedback'];
            }
            $suffix = (string) $next['status'] === 'in_progress' ? '' : '/result';
            $this->redirect('/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode($publicId) . $suffix . $this->previewQuery($preview));
        }, '/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode($publicId) . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/assessment/session/{session}/finish', name: 'assessment_finish', requirements: ['slug' => '[a-zA-Z0-9_-]+', 'session' => '\\d+'], methods: ['POST'])]
    public function finish(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $publicId = (string) $this->param('session');
        $preview = $this->previewMode();
        return $this->handle(function () use ($user, $slug, $publicId, $preview): void {
            $this->assessments->finish($user->id, $publicId);
            $this->redirect('/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode($publicId) . '/result' . $this->previewQuery($preview));
        }, '/learn/' . rawurlencode($slug) . '/assessment/session/' . rawurlencode($publicId) . $this->previewQuery($preview));
    }


    #[Route('/learn/{slug}/assessment/session/{session}/result', name: 'assessment_result', requirements: ['slug' => '[a-zA-Z0-9_-]+', 'session' => '\\d+'], methods: ['GET'])]
    public function result(): Response
    {
        $user = $this->requirePermission('LEARNING.ASSESSMENT.TAKE');
        $slug = (string) $this->param('slug');
        $publicId = (string) $this->param('session');
        $preview = $this->previewMode();
        return $this->handle(function () use ($user, $slug, $publicId, $preview): Response {
            $session = $this->assessments->result($user->id, $publicId);
            return $this->render('assessment-session-result', [
                'title' => 'Assessment result',
                'session' => $session,
                'course_url' => '/learn/' . rawurlencode($slug) . $this->previewQuery($preview),
                'retake_url' => match ((string) $session['assessment_type']) {
                    'final' => '/learn/' . rawurlencode($slug) . '/final/assessment' . $this->previewQuery($preview),
                    'diagnostic' => '/learn/' . rawurlencode($slug) . '/diagnostic/' . rawurlencode((string) ($session['assessment_key'] ?? 'diagnostic')) . $this->previewQuery($preview),
                    default => '/learn/' . rawurlencode($slug) . '/module/' . (int) $session['module_position'] . '/assessment' . $this->previewQuery($preview),
                },
                'is_preview' => $preview,
            ]);
        }, '/learn/' . rawurlencode($slug) . $this->previewQuery($preview));
    }

    private function previewMode(): bool
    {
        $preview = (string) ($_GET['preview'] ?? '') === '1';
        if ($preview) {
            $this->requireCourseAuthor();
        }
        return $preview;
    }

    private function previewQuery(bool $preview): string
    {
        return $preview ? '?preview=1' : '';
    }

    /**
     * @param array<string,mixed> $data
     * @return array<string,mixed>
     */
    private function viewData(array $data, string $slug, bool $preview): array
    {
        return $data + [
            'course' => $data['course'],
            'assessment' => $data['assessment'],
            'module' => $data['module'],
            'is_preview' => $preview,
            'preview_query' => $this->previewQuery($preview),
            'course_url' => '/learn/' . rawurlencode($slug) . $this->previewQuery($preview),
        ];
    }
}