<?php

/*
Generated by: Claude Code CLI

Date time: 2026/10/07 SAST

Version: 0.8.8.10

Description:
Administration → Courses → Certificate Designs: the list of designs (picture, name, the courses
that use it, when it was last edited), the default for new courses, and one form per design - its
look, logo, wording, signatory and small print - beside a preview that is the PDF the certificate
will be. A new design opens the same form. Save keeps a version a certificate can always be drawn
again from; nothing about versions is shown. Delete moves the design's courses to another design.

The editor can be opened from a course's certificate page; it then returns there (return_to, only a
course certificate page is accepted).

Changelog:
2026/10/07 SAST
- Created for certificate designs, replacing the generic document template pages for certificates.
*/

declare(strict_types=1);

namespace CattoLearning\Http\Controller;

use CattoLearning\Auth\AuthService;
use CattoLearning\Course\Certificate\CertificateDesign;
use CattoLearning\Course\Certificate\CertificateDesignService;
use CattoLearning\Course\Certificate\CertificateLooks;
use CattoLearning\Course\Certificate\CertificateWording;
use CattoLearning\View\ThemeRenderer;
use InvalidArgumentException;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class CertificateDesignController extends BaseController
{
    private const BASE = '/admin/certificates/designs';

    public function __construct(
        AuthService $auth,
        ThemeRenderer $view,
        RequestStack $requests,
        private readonly CertificateDesignService $designs,
    ) {
        parent::__construct($auth, $view, $requests);
    }

    #[Route('/admin/certificates/designs', name: 'admin_certificate_designs', methods: ['GET'])]
    public function index(): Response
    {
        $user = $this->requirePermission('CERTIFICATE.DESIGN.VIEW');
        $designs = $this->designs->designs();
        return $this->render('admin-certificate-designs', [
            'title' => 'Certificate designs',
            'designs' => array_map(self::listRow(...), $designs),
            'default_id' => $this->defaultId($designs),
            'can_manage' => $user->hasPermission('CERTIFICATE.DESIGN.MANAGE'),
        ]);
    }

    #[Route('/admin/certificates/designs/default', name: 'admin_certificate_design_default', methods: ['POST'])]
    public function setDefault(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('CERTIFICATE.DESIGN.MANAGE');
        return $this->handle(function () use ($user): void {
            $this->designs->setDefault((int) $this->posted('design_id'), $user->id);
            $this->flash('success', 'New courses will start with that design.');
            $this->redirect(self::BASE);
        }, self::BASE);
    }

    #[Route('/admin/certificates/designs/new', name: 'admin_certificate_design_new', methods: ['GET'])]
    public function create(): Response
    {
        $this->requirePermission('CERTIFICATE.DESIGN.MANAGE');
        $look = (string) $this->request()->query->get('look', 'classic');
        $look = isset(CertificateLooks::installed()[$look]) ? $look : 'classic';
        return $this->editor(null, '', CertificateDesign::starter($look), [], '/admin/certificates/looks/' . $look . '/preview.pdf');
    }

    #[Route('/admin/certificates/designs', name: 'admin_certificate_design_store', methods: ['POST'])]
    public function store(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('CERTIFICATE.DESIGN.MANAGE');
        $saved = $this->designs->save(null, $_POST, $_FILES, $user->id);
        if ($saved['errors'] !== []) {
            return $this->editor(null, $saved['name'], $saved['design'], $saved['errors'], '', 422);
        }
        $this->flash('success', 'The design “' . $saved['name'] . '” was saved.');
        $this->redirect($this->returnTo() ?? self::BASE . '/' . $saved['id']);
    }

    #[Route('/admin/certificates/designs/{id}', name: 'admin_certificate_design', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function edit(): Response
    {
        $this->requirePermission('CERTIFICATE.DESIGN.VIEW');
        $design = $this->found((int) $this->param('id'));
        return $this->editor($design['id'], (string) $design['name'], $design['design'], [], self::BASE . '/' . $design['id'] . '/preview.pdf', 200, $design);
    }

    #[Route('/admin/certificates/designs/{id}', name: 'admin_certificate_design_update', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function update(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('CERTIFICATE.DESIGN.MANAGE');
        $design = $this->found((int) $this->param('id'));
        $saved = $this->designs->save($design['id'], $_POST, $_FILES, $user->id);
        if ($saved['errors'] !== []) {
            return $this->editor($design['id'], $saved['name'], $saved['design'], $saved['errors'], '', 422, $design);
        }
        $this->flash('success', 'The design “' . $saved['name'] . '” was saved. Certificates issued from now on use it; certificates already issued keep the design they were issued with.');
        $this->redirect($this->returnTo() ?? self::BASE . '/' . $design['id']);
    }

    /** The posted form drawn as the sample certificate, without saving anything. */
    #[Route('/admin/certificates/designs/preview.pdf', name: 'admin_certificate_design_preview', methods: ['POST'])]
    public function preview(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('CERTIFICATE.DESIGN.MANAGE');
        $form = $this->designs->fromForm($_POST, $_FILES, $user->id);
        $checked = $this->designs->check($form['design']);
        if ($checked['pdf'] === null) {
            return $this->problems([...$form['errors'], ...$checked['errors']]);
        }
        return self::pdf($checked['pdf'], 'certificate-preview.pdf');
    }

    #[Route('/admin/certificates/designs/{id}/preview.pdf', name: 'admin_certificate_design_saved_preview', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function savedPreview(): Response
    {
        $this->requirePermission('CERTIFICATE.DESIGN.VIEW');
        $design = $this->found((int) $this->param('id'));
        return self::pdf($this->designs->previewPdf($design['id']), 'certificate-preview.pdf');
    }

    /** An installed look's starter design, for a new design's first preview. */
    #[Route('/admin/certificates/looks/{look}/preview.pdf', name: 'admin_certificate_look_preview', requirements: ['look' => '[a-z-]+'], methods: ['GET'])]
    public function lookPreview(): Response
    {
        $this->requirePermission('CERTIFICATE.DESIGN.VIEW');
        $look = (string) $this->param('look');
        if (!isset(CertificateLooks::installed()[$look])) {
            throw $this->notFound('There is no such look.');
        }
        $checked = $this->designs->check(CertificateDesign::starter($look));
        return self::pdf((string) $checked['pdf'], 'certificate-preview.pdf');
    }

    #[Route('/admin/certificates/designs/{id}/duplicate', name: 'admin_certificate_design_duplicate', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function duplicate(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('CERTIFICATE.DESIGN.MANAGE');
        $design = $this->found((int) $this->param('id'));
        return $this->handle(function () use ($design, $user): void {
            $copy = $this->designs->duplicate($design['id'], $user->id);
            $this->flash('success', 'A copy of “' . $design['name'] . '” was made. Change it here.');
            $this->redirect(self::BASE . '/' . $copy);
        }, self::BASE);
    }

    #[Route('/admin/certificates/designs/{id}/delete', name: 'admin_certificate_design_delete', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function confirmDelete(): Response
    {
        $this->requirePermission('CERTIFICATE.DESIGN.MANAGE');
        $design = $this->found((int) $this->param('id'));
        $others = array_values(array_filter($this->designs->designs(), static fn(array $row): bool => $row['id'] !== $design['id']));
        return $this->render('admin-certificate-design-delete', [
            'title' => 'Delete ' . $design['name'],
            'design' => self::listRow($design),
            'courses' => $this->designs->coursesUsing($design['id']),
            'others' => array_map(static fn(array $row): array => ['id' => $row['id'], 'name' => (string) $row['name']], $others),
            'suggested' => $this->defaultId($others) ?? ($others[0]['id'] ?? 0),
        ]);
    }

    #[Route('/admin/certificates/designs/{id}/delete', name: 'admin_certificate_design_destroy', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function delete(): Response
    {
        $this->requireCsrf();
        $user = $this->requirePermission('CERTIFICATE.DESIGN.MANAGE');
        $design = $this->found((int) $this->param('id'));
        return $this->handle(function () use ($design, $user): void {
            $this->designs->delete($design['id'], (int) $this->posted('replacement_id'), $user->id);
            $this->flash('success', 'The design “' . $design['name'] . '” was deleted. Certificates already issued with it are not changed.');
            $this->redirect(self::BASE);
        }, self::BASE . '/' . $design['id'] . '/delete');
    }

    /** A small picture of an uploaded background, logo or signature, for the pickers. */
    #[Route('/admin/certificates/pictures/{sha}.png', name: 'admin_certificate_picture', requirements: ['sha' => '[0-9a-f]{64}'], methods: ['GET'])]
    public function picture(): Response
    {
        $user = $this->requireUser();
        if (!$user->hasPermission('CERTIFICATE.DESIGN.VIEW') && !$user->hasPermission('COURSE.CERTIFICATE.MANAGE')) {
            throw new \Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException('You do not have permission to access this function.');
        }
        $thumbnail = $this->designs->thumbnail((string) $this->param('sha'), max(80, min(960, (int) $this->request()->query->get('w', 480))));
        if ($thumbnail === null) {
            throw $this->notFound('That picture does not exist.');
        }
        return new Response($thumbnail['bytes'], 200, ['Content-Type' => $thumbnail['mime'], 'Cache-Control' => 'private, max-age=31536000, immutable', 'X-Content-Type-Options' => 'nosniff']);
    }

    /**
     * @param list<string> $errors
     * @param array<string,mixed>|null $saved the design as stored, when it exists
     */
    private function editor(?int $id, string $name, CertificateDesign $design, array $errors, string $previewSource, int $status = 200, ?array $saved = null): Response
    {
        $user = $this->requireUser();
        $looks = [];
        foreach (CertificateLooks::installed() as $key => $look) {
            $looks[] = ['value' => $key, 'label' => $look->name, 'image' => self::lookImage($key), 'note' => $look->description];
        }
        if ($design->background !== null) {
            $looks[] = ['value' => CertificateLooks::CUSTOM, 'label' => 'Your own background', 'image' => self::pictureUrl($design->background->sha), 'note' => 'Uploaded'];
        }
        $placements = [];
        foreach (CertificateLooks::PLACEMENTS as $key => $label) {
            $placements[] = ['value' => $key, 'label' => $label, 'image' => '/img/certificates/placement-' . $key . '.svg'];
        }
        return $this->render('admin-certificate-design', [
            'title' => $id === null ? 'New certificate design' : $name,
            'design_id' => $id,
            'name' => $name,
            'design' => $design->toArray(),
            'looks' => $looks,
            'placements' => $placements,
            'typefaces' => CertificateLooks::TYPEFACES,
            'fields' => CertificateWording::fields(),
            'styles' => CertificateWording::STYLES,
            'pictures' => [
                'background' => $design->background === null ? null : self::pictureUrl($design->background->sha),
                'logo' => $design->logo === null ? null : self::pictureUrl($design->logo->sha),
                'signature' => $design->signature === null ? null : self::pictureUrl($design->signature->sha),
            ],
            'errors' => $errors,
            'preview_src' => $previewSource,
            'saved' => $saved === null ? null : ['updated_at' => $saved['updated_at'], 'updated_by' => $saved['updated_by_name'], 'course_count' => $saved['course_count']],
            'return_to' => $this->returnTo(),
            'can_manage' => $user->hasPermission('CERTIFICATE.DESIGN.MANAGE'),
            'load_certificate_editor' => true,
        ], $status);
    }

    /**
     * A plain page in the preview frame listing what stops the design being drawn.
     *
     * @param list<string> $errors
     */
    private function problems(array $errors): Response
    {
        $items = implode('', array_map(static fn(string $error): string => '<li>' . htmlspecialchars($error, ENT_QUOTES) . '</li>', $errors));
        return new Response('<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Preview</title>'
            . '<style>body{font:16px/1.5 system-ui,sans-serif;margin:1.5rem;color:#1c2430}h1{font-size:1.1rem}</style></head><body>'
            . '<h1>The preview cannot be drawn yet</h1><ul>' . $items . '</ul></body></html>', 422, ['Content-Type' => 'text/html; charset=UTF-8', 'Cache-Control' => 'no-store']);
    }

    /** @return array<string,mixed> */
    private function found(int $id): array
    {
        try {
            return $this->designs->design($id);
        } catch (InvalidArgumentException) {
            throw $this->notFound('That certificate design does not exist.');
        }
    }

    /** Only a course's certificate page may be returned to. */
    private function returnTo(): ?string
    {
        $target = (string) ($this->request()->request->get('return_to') ?? $this->request()->query->get('return_to') ?? '');
        return preg_match('#^/admin/courses/\d+/certificate$#D', $target) === 1 ? $target : null;
    }

    /** @param list<array<string,mixed>> $designs */
    private function defaultId(array $designs): ?int
    {
        foreach ($designs as $design) {
            if ($design['is_current']) {
                return (int) $design['id'];
            }
        }
        return null;
    }

    /**
     * @param array<string,mixed> $design
     * @return array<string,mixed>
     */
    public static function listRow(array $design): array
    {
        /** @var CertificateDesign $value */
        $value = $design['design'];
        return [
            'id' => (int) $design['id'], 'name' => (string) $design['name'], 'is_default' => (bool) $design['is_current'],
            'course_count' => (int) $design['course_count'], 'updated_at' => $design['updated_at'], 'updated_by' => $design['updated_by_name'],
            'image' => $value->background !== null && $value->isCustom() ? self::pictureUrl($value->background->sha) : self::lookImage($value->look),
        ];
    }

    public static function lookImage(string $look): string
    {
        return '/img/certificates/looks/' . (isset(CertificateLooks::installed()[$look]) ? $look : 'classic') . '.png';
    }

    public static function pictureUrl(string $sha): string
    {
        return '/admin/certificates/pictures/' . $sha . '.png';
    }

    private static function pdf(string $bytes, string $filename): Response
    {
        return new Response($bytes, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="' . $filename . '"',
            'X-Content-Type-Options' => 'nosniff',
            'Cache-Control' => 'private, no-store',
        ]);
    }
}
