<?php
/*
Generated by: ChatGPT

Date time: 2026/09/09 02:10 SAST

Version: 0.7

Description:
Checks high-risk Catto Learning runtime contracts, with special guards for filesystem-authoritative Theme Package 3.0 with rebuildable registry, platform-owned page bodies, exact-parent child themes and Factory Reset isolation.

Changelog:
2026/09/09 02:10 SAST
- Checks the Theme Package 4.0 guards, and that the renderer still addresses templates by namespace rather than composing a path of its own.
2026/08/23 04:19 SAST
- Discover the single baseline migration by glob instead of naming it, so a rebased baseline does not require editing every call site.
2026/08/15 12:32 SAST
- Replaced Theme Package 2.0/database-materialisation guards with Theme Package 3.0 filesystem guards.
*/
declare(strict_types=1);

$root = dirname(__DIR__);
$errors = [];
$need = static function(bool $ok, string $message) use (&$errors): void { if (!$ok) $errors[] = $message; };
$read = static function(string $path) use ($need): string { $need(is_file($path), 'Missing: ' . $path); return is_file($path) ? (string)file_get_contents($path) : ''; };

$manager = $read($root . '/src/View/ThemeManager.php');
foreach (['assertInstallableManifest','findByNameVersion','themeLayers','public/css/theme.css','Theme Package 3.0','resyncRegistry','registryOutOfSync'] as $token) $need(str_contains($manager,$token),'ThemeManager runtime guard missing: '.$token);
foreach (['ThemeRepository','resolveChain','versionSatisfies','theme.upgraded','materialise'] as $token) $need(!str_contains($manager,$token),'Obsolete theme runtime token remains: '.$token);

$validator = $read($root . '/src/View/ThemePackageValidator.php');
foreach (["SCHEMA_VERSION = '4.0'","TEMPLATE_API = '2.0'",'public/css/theme.css','standalone theme must contain base.html.twig','parent.version'] as $token) $need(str_contains($validator,$token),'Theme validator guard missing: '.$token);

$renderer = $read($root . '/src/View/ThemeRenderer.php');
// The renderer addresses templates by namespace now: @platform is the core-owned page bodies and
// @theme is the theme a request renders in, so what is checked is that it still asks ThemeTemplates
// for both rather than composing a path of its own.
foreach (['pageTemplate($page)','layoutFor(','templates->use('] as $token) $need(str_contains($renderer,$token),'Theme renderer guard missing: '.$token);
$need(!str_contains($renderer,'themes/factory-reset/pages'),'Theme renderer must not source functional pages from Factory Reset.');

$base = $read($root . '/themes/factory-reset/base.html.twig');
foreach (['block page_body','@theme/partials/navigation.html.twig','@theme/partials/flash.html.twig','@theme/partials/footer.html.twig'] as $token) $need(str_contains($base,$token),'Factory Reset base runtime dependency missing: '.$token);

$baselineMatches = glob($root . '/database/migrations/*_baseline.php') ?: [];
$need(count($baselineMatches) === 1, 'Expected exactly one baseline migration, found ' . count($baselineMatches) . '.');
$baseline = $baselineMatches === [] ? '' : $read($baselineMatches[0]);
foreach (['theme_definitions','theme_files','theme_assets'] as $token) $need(!str_contains($baseline,'CREATE TABLE '.$token),'Theme source table must not exist: '.$token);
// The baseline must record *an* active theme, not a particular version. It pinned 1.0.1 while two
// later migrations advanced the value; v0.6 collapsed those into one baseline that records the
// bundled version directly, and validate-release.php is what checks the two agree.
$need((bool) preg_match("/\('active_theme', 'factory-reset-v\d+\.\d+\.\d+'\)/", $baseline), 'Default active_theme seed is missing.');
$need(str_contains($baseline,'CREATE TABLE theme_registry'),'Rebuildable theme metadata registry is missing.');
$need(str_contains($baseline,'CREATE TABLE permissions') && str_contains($baseline,'CREATE TABLE role_permissions'),'ACL schema is missing.');
$auditStart = strpos($baseline, 'CREATE TABLE audit_log');
$auditEnd = $auditStart === false ? false : strpos($baseline, 'CREATE INDEX audit_log_user', $auditStart);
$auditBlock = ($auditStart !== false && $auditEnd !== false) ? substr($baseline, $auditStart, $auditEnd - $auditStart) : '';
$need(str_contains($auditBlock,'ip_address INET NULL') && !str_contains($auditBlock,'ip_hash'),'audit_log must store raw IP without an IP hash.');


$app = $read($root . '/src/Application/App.php');
// One router, one container. Fat-Free and PHP-DI are gone and neither may come back: two routers
// meant a route could be claimed twice, and two containers meant one object graph described twice.
$need(!str_contains($app, 'Base::instance()'), 'Fat-Free must not be reintroduced into the HTTP bootstrap.');
$need(str_contains($app, 'self::handleWithSymfony('), 'The HTTP bootstrap must hand the request to the Symfony kernel.');
$need(!is_file($root . '/src/Application/ContainerFactory.php'), 'The PHP-DI composition root must not return.');
$need(!is_file($root . '/src/Http/Routing/RouteRegistrar.php'), 'The Fat-Free route registrar must not return.');
$need(!str_contains($app,'new HomeController('), 'HTTP bootstrap must not eagerly construct controllers.');
$need(!is_file($root . '/src/Http/Routing/LazyControllerHandler.php'), 'Custom LazyControllerHandler must not return; F3 owns PSR-11 route resolution.');
$need(!is_file($root . '/src/Application/AppContext.php'), 'Obsolete AppContext must not exist.');
$need(!is_file($root . '/src/Application/ServiceFactory.php'), 'Obsolete ServiceFactory must not exist.');

$coreJs = $read($root . '/public_html/js/platform-overrides.js');
foreach (['data-open-modal','/theme/palette'] as $token) $need(str_contains($coreJs,$token),'Core platform JS guard missing: '.$token);
$need(!str_contains($coreJs,'data-admin-tab'),'Legacy Administration tab JavaScript must not return.');
$adminWorkspace = $read($root . '/resources/views/pages/admin-control-centre.html.twig');
$need(str_contains($adminWorkspace,'data-admin-workspace'),'Consolidated Administration workspace contract is missing.');
$need(!str_contains($adminWorkspace,'data-admin-tab'),'Administration workspace must not depend on tab-selection controls.');
$need(is_file($root . '/src/Application/AdministrationSectionRegistry.php'),'Administration section registry is missing.');
$need(is_file($root . '/src/Application/AccountSectionRegistry.php'),'Account section registry is missing.');
$need(is_file($root . '/src/Application/CompanySectionRegistry.php'),'Company section registry is missing.');
foreach (['footer_navigation','account_sections','company_sections'] as $token) $need(str_contains($renderer,$token),'Stable Theme API guard missing: '.$token);
$need(!str_contains($coreJs,'data-theme-file'),'Removed Theme Studio JavaScript must not return.');
$factoryJs = glob($root . '/themes/factory-reset/public/js/*.js') ?: [];
$need($factoryJs === [], 'Factory Reset must not contain platform-owned JavaScript.');

if ($errors) {
    fwrite(STDERR, "Runtime hazard check failed:\n- " . implode("\n- ", $errors) . "\n");
    exit(1);
}
echo "Runtime hazard check passed: filesystem themes and platform page bodies are isolated.\n";