<?php

/*
Generated by: ChatGPT

Date time: 2026/08/12 02:45 SAST

Version: 0.5.4

Description:
Provides application-layer coordination for app context, connecting Catto Learning domain services, persistence and HTTP workflows.

Changelog:
2026/08/11 23:24 SAST
- Updated source metadata for Catto Learning 0.5.3.
2026/08/11 22:21 SAST
- Updated source metadata for the Catto Learning 0.5.2 release.
2026/08/11 16:54 SAST
- Exposed the central runtime settings resolver through the application context.
2026/08/11 15:02 SAST
- Standardised this source file with the Catto Learning 0.5.1 SAST metadata header.
*/

declare(strict_types=1);

namespace CattoLearning\Application;

use CattoLearning\Api\ApiAuthService;
use CattoLearning\Api\ApiTokenService;
use CattoLearning\Api\AuthorizationService;
use CattoLearning\Auth\AuthService;
use CattoLearning\Company\CompanyService;
use CattoLearning\Configuration\RuntimeSettings;
use CattoLearning\Course\CourseRepository;
use CattoLearning\Course\CourseService;
use CattoLearning\Course\CoursePortabilityService;
use CattoLearning\Course\AssessmentService;
use CattoLearning\Course\LearningService;
use CattoLearning\Event\EventDispatcher;
use CattoLearning\Infrastructure\Mail\MailerInterface;
use CattoLearning\Infrastructure\Persistence\AuditRepository;
use CattoLearning\Maintenance\MaintenanceService;
use CattoLearning\View\ThemeManager;
use CattoLearning\View\ThemeRenderer;

final readonly class AppContext
{
    public function __construct(
        public AuthService $auth,
        public PlatformAdministrationService $platformAdministration,
        public CompanyService $companies,
        public CourseRepository $courseRepository,
        public CourseService $courses,
        public CoursePortabilityService $portability,
        public AssessmentService $assessments,
        public LearningService $learning,
        public AuditRepository $audit,
        public EventDispatcher $events,
        public MailerInterface $mailer,
        public ThemeManager $themes,
        public MaintenanceService $maintenance,
        public ThemeRenderer $view,
        public ApiAuthService $apiAuth,
        public ApiTokenService $apiTokens,
        public AuthorizationService $authorization,
        public RuntimeSettings $settings,
        public string $instanceRoot
    ) {
    }
}