<?php

/*
Generated by: Claude Code CLI

Date time: 2026/08/25 13:59 SAST

Version: 0.5.8.3

Description:
Stage D contracts that hold without a database: what the selector may be built from, what the
context may be read from, and that the control renders.

The tampering rules are the reason this file exists. "The selected company must be explicit,
validated server-side and impossible to widen by parameter tampering" is a property of where the
value comes from, and the cheapest way to lose it is for somebody to add a convenient
`?company_id=` fallback years from now. A test that reads the source is unusual, but this is a
boundary where the absence of a line of code is the security property.

Changelog:

2026/08/25 13:59 SAST

- Created for the v0.5.8.3 Stage D Platform ADMIN selected-company context.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use CattoLearning\Company\SelectedCompanyContext;
use CattoLearning\Tests\Support\RenderHarness;
use PHPUnit\Framework\TestCase;
use ReflectionClass;

final class CompanyContextContractTest extends TestCase
{
    private static function source(string $relative): string
    {
        return (string) file_get_contents(dirname(__DIR__, 2) . '/' . $relative);
    }

    // --- where the selection may come from -----------------------------------------------------

    /**
     * The selection is never read from the query string.
     *
     * A GET parameter is an instruction from the client, and this is an authorisation boundary.
     * Accepting `?company_id=` would let anyone who can reach /company widen their own scope by
     * editing a URL, and it would also make a read path change what the next read returns.
     */
    public function testTheContextIsNeverReadFromTheQueryString(): void
    {
        $source = self::source('src/Company/SelectedCompanyContext.php');

        self::assertStringNotContainsString('$_GET', $source, 'The administered company must not come from the URL.');
        self::assertStringNotContainsString('$_REQUEST', $source, '$_REQUEST includes the query string.');
        self::assertStringContainsString('$_SESSION', $source, 'The selection is held server-side.');
    }

    /** Selecting is a POST route; nothing in the Company workspace selects on a GET. */
    public function testSelectingIsAPostRoute(): void
    {
        $routes = self::source('src/Application/App.php');

        self::assertStringContainsString(
            "POST /company/context",
            $routes,
            'Choosing the administered company must be a POST.'
        );
        self::assertStringNotContainsString(
            "GET /company/context",
            $routes,
            'A GET that changes which company is administered is a read that writes.'
        );
    }

    /** The only writer of the session key is select(); every read path re-validates instead. */
    public function testOnlySelectAndClearWriteTheSelection(): void
    {
        $source = self::source('src/Company/SelectedCompanyContext.php');

        self::assertSame(
            1,
            substr_count($source, '$_SESSION[self::SESSION_KEY] ='),
            'Exactly one assignment, inside select(), after every check has passed.'
        );
        self::assertSame(
            1,
            substr_count($source, 'unset($_SESSION[self::SESSION_KEY])'),
            'Exactly one clear, so discarding a stale selection has one implementation.'
        );
    }

    // --- who may select ------------------------------------------------------------------------

    /**
     * A generated identity may never select a company, whatever permissions it holds.
     *
     * Seed roles carry the same business permission keys as their normal counterparts by design,
     * so the permission alone cannot be the test. `users.seed_token` is the source of truth for
     * identity universe, exactly as it is for the data-universe selector.
     */
    public function testASeedIdentityMayNeverSelect(): void
    {
        $method = (new ReflectionClass(SelectedCompanyContext::class))->getMethod('canSelect');
        $body = self::source('src/Company/SelectedCompanyContext.php');

        self::assertTrue($method->isPublic());
        self::assertStringContainsString(
            'isSeedIdentity()',
            $body,
            'The seed-identity test must gate the selector, not the permission alone.'
        );
    }

    /** The read scope that offers the selector is a view permission, and writes keep their own checks. */
    public function testTheSelectorIsGatedOnReadScope(): void
    {
        self::assertSame('PLATFORM.DASHBOARD.VIEW', SelectedCompanyContext::SELECTOR_PERMISSION);
        self::assertStringEndsWith(
            '.VIEW',
            SelectedCompanyContext::SELECTOR_PERMISSION,
            'Offering the selector is a read capability; a .VIEW permission must never authorise a write.'
        );
    }

    // --- the company-courses rule --------------------------------------------------------------

    /**
     * A company's two relationships to a course are stated separately, and each shares one rule
     * between its rows and its count.
     *
     * They were one predicate - owned OR credited - behind one screen called "Courses". Those are
     * opposites: one is stock the company sells, the other stock it consumes, and a list holding
     * both answers neither question. Since v0.6 they are two constants, and the resolver picks one;
     * recombining them into a single predicate is the regression this guards.
     *
     * The rows and the count still share whichever one is chosen, which is the older half of this
     * contract: before Stage D the rows ran `publishedCourses()` against a published count, so the
     * list had a total that did not belong to it.
     */
    public function testACompanysTwoCourseRelationshipsAreStatedSeparately(): void
    {
        $source = self::source('src/Course/CourseRepository.php');

        // The constant, not the word: the file's own changelog records that the combined rule once
        // existed, and that record is the point of a changelog.
        self::assertStringNotContainsString(
            'self::COMPANY_COURSES_WHERE',
            $source,
            'The combined owned-or-credited rule must not come back.'
        );
        self::assertStringContainsString('COMPANY_OWNED_WHERE', $source);
        self::assertStringContainsString('COMPANY_TRAINING_WHERE', $source);
        self::assertStringContainsString(
            "const COMPANY_OWNED_WHERE = 'c.owner_company_id = :company_id'",
            $source,
            'Owned is the provider relationship: the company made the course.'
        );
        self::assertStringContainsString(
            'course_credits cr',
            $source,
            'Training is the entitlement relationship: the company bought seats.'
        );

        // One resolver, used by the rows and by the count, so the two cannot pick differently.
        self::assertSame(
            2,
            substr_count($source, 'self::companyCourseWhere('),
            'The resolver is used exactly twice: once by the rows and once by the count.'
        );
    }

    /** The Company workspace no longer shows the whole catalogue as though it were one company's. */
    public function testTheCompanySurfacesNoLongerUsePublishedCourses(): void
    {
        $service = self::source('src/Application/PlatformAdministrationService.php');
        $companyBlock = substr($service, (int) strpos($service, 'function companyControlCentre'));

        // The arrow matters: it matches a call rather than the word appearing in a comment
        // explaining why the call was removed.
        self::assertStringNotContainsString(
            '->publishedCourses(',
            $companyBlock,
            'Every published course on the platform is not a company\'s course list.'
        );
        self::assertStringNotContainsString('->publishedCoursesCount(', $companyBlock);
        self::assertStringContainsString('->companyCourses(', $companyBlock);
        self::assertStringContainsString('->companyCoursesCount(', $companyBlock);
    }

    // --- the control renders -------------------------------------------------------------------

    /** @return array<string,mixed> */
    private static function switcherHive(string $universe = 'real'): array
    {
        return [
            'can_select_company' => true,
            'company_context_mode' => 'selected',
            'company_context_name' => 'Highveld Mining',
            'company_context_domain' => 'highveld.test',
            'company_context_id' => 42,
            'company_context_universe' => $universe,
            'company_switcher' => [
                'picker_search' => '',
                'picker_pagination' => null,
                'picker_companies' => [[
                    'id' => 7, 'name' => 'Table Bay Logistics', 'domain' => 'tablebay.test',
                    'status' => 'active', 'status_label' => 'Active', 'is_system' => false,
                    'universe' => 'real', 'universe_label' => 'REAL', 'is_seed' => false,
                ]],
            ],
        ];
    }

    /** The control names the company being administered and which universe that puts it in. */
    public function testTheControlRendersForAPlatformAdministrator(): void
    {
        $html = RenderHarness::render('partials/company-context.html', RenderHarness::hiveWith(self::switcherHive()));

        self::assertStringContainsString('company-context', $html);
        self::assertStringContainsString('Highveld Mining', $html);
        self::assertStringContainsString('REAL', $html, 'The administrator must see which universe the company puts them in.');
        self::assertStringContainsString('Switch company', $html);
    }

    /** Administering a generated company says so, because it otherwise looks identical to a real one. */
    public function testTheControlNamesTheSeedUniverse(): void
    {
        $html = RenderHarness::render('partials/company-context.html', RenderHarness::hiveWith(self::switcherHive('seed')));

        self::assertStringContainsString('SEED', $html);
    }

    /** Selecting is a POST carrying a CSRF token, never a link. */
    public function testSelectingIsAPostWithCsrf(): void
    {
        $html = RenderHarness::render('partials/company-context.html', RenderHarness::hiveWith(self::switcherHive()));

        self::assertStringContainsString('action="/company/context"', $html);
        self::assertStringContainsString('method="post"', $html);
        self::assertStringContainsString('name="csrf"', $html, 'Selecting must carry a CSRF token.');
        self::assertStringContainsString('Table Bay Logistics', $html, 'The picker renders its first page server-side.');
    }

    /**
     * The picker is a modal with the accessible attributes and a way out.
     *
     * A modal that can only be closed with a mouse is not finished, so the close control and the
     * dialog semantics are part of the contract rather than presentation the theme may drop.
     */
    public function testThePickerModalIsAccessible(): void
    {
        $html = RenderHarness::render('partials/company-context.html', RenderHarness::hiveWith(self::switcherHive()));

        self::assertStringContainsString('role="dialog"', $html);
        self::assertStringContainsString('aria-modal="true"', $html);
        self::assertStringContainsString('data-open-modal="company-switch"', $html);
        self::assertStringContainsString('data-close-modal', $html);
    }

    /** Without JavaScript the switcher still has a destination. */
    public function testThePickerHasANonJavascriptFallback(): void
    {
        $html = RenderHarness::render('partials/company-context.html', RenderHarness::hiveWith(self::switcherHive()));

        self::assertStringContainsString('/company/picker', $html);
        self::assertStringContainsString('method="get"', $html, 'Search must work as an ordinary GET form.');
    }

    /** An ordinary Company Administrator is shown no switcher at all. */
    public function testTheControlIsAbsentWithoutTheCapability(): void
    {
        $html = RenderHarness::render('partials/company-context.html', RenderHarness::hiveWith([
            'can_select_company' => false,
            'company_context_mode' => 'own',
            'company_context_name' => 'Table Bay Logistics',
            'company_context_id' => 7,
            'company_context_universe' => 'real',
        ]));

        // The file's own header comment still renders - F3 emits HTML comments, and they are
        // stripped later in the response - so the test is that no control is emitted, not that
        // the output is byte-empty.
        self::assertStringNotContainsString('Switch company', $html);
        self::assertStringNotContainsString('/company/context', $html);
        self::assertStringNotContainsString('Table Bay Logistics', $html, 'No company name is disclosed by the control.');
        self::assertStringNotContainsString('<form', $html, 'A Company Administrator gets no switcher to submit.');
        self::assertStringNotContainsString('<button', $html);
    }

    /**
     * The control's own markup carries no template tokens inside comments.
     *
     * F3 parses its own tags inside HTML comments, and a comment delimiter written inside a
     * comment body ends it early and leaks the remainder onto the page. This has happened before.
     */
    public function testTheControlsCommentsArePlainProse(): void
    {
        $markup = self::source('resources/views/partials/company-context.html');

        preg_match_all('/<!--(.*?)-->/s', $markup, $comments);
        foreach ($comments[1] as $comment) {
            self::assertStringNotContainsString('{{', $comment, 'A template token inside a comment becomes real markup.');
            self::assertStringNotContainsString('<', $comment, 'An angle bracket inside a comment becomes a tag.');
            self::assertStringNotContainsString('--', $comment, 'A comment delimiter inside a comment ends it early.');
        }
    }
}
