<?php

/*
Generated by: ChatGPT

Date time: 2026/08/20 06:17 SAST

Version: 0.5.7.5

Description:
Protects the presence of the core Catto Learning briefing documents without imposing a maximum document count in the repository root or docs/.

Changelog:
2026/08/20 06:17 SAST
- Replaced the invented closed-set documentation restriction with presence checks for the required core briefing documents.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use PHPUnit\Framework\TestCase;

final class DocumentationLayoutTest extends TestCase
{
    public function testCanonicalDocumentationIsPresent(): void
    {
        $root = dirname(__DIR__, 2);

        self::assertFileExists($root . '/README.md');
        self::assertFileExists($root . '/CHANGELOG.md');
        self::assertFileExists($root . '/LICENSE');

        $required = [
            'COURSE-SPECIFICATION.md',
            'HANDOFF.md',
            'OPERATIONS.md',
            'PROJECT-INSTRUCTIONS.md',
            'ROADMAP.md',
            'THEME-SDK.md',
        ];
        $docs = array_map('basename', glob($root . '/docs/*.md') ?: []);
        foreach ($required as $document) {
            self::assertContains(
                $document,
                $docs,
                'Required documentation is missing from docs/: ' . $document
            );
        }
    }
}
