<?php

/*
Generated by: ChatGPT

Date time: 2026/08/18 22:47 SAST

Version: 0.5.7.5.1

Description:
Protects the optional Geocoder PHP audit-IP integration contract.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use CattoLearning\Support\GeoIpLocator;
use PHPUnit\Framework\TestCase;

final class GeoIpContractTest extends TestCase
{
    public function testPrivateIpDoesNotRequireGeoipDatabase(): void
    {
        $locator = new GeoIpLocator('');

        self::assertFalse($locator->isAvailable());
        self::assertSame('Local/private', $locator->locate('127.0.0.1'));
        self::assertSame('GeoIP unavailable', $locator->locate('8.8.8.8'));
        self::assertSame('🇿🇦', GeoIpLocator::flagForCountryCode('ZA'));
        self::assertSame('🇬🇧', GeoIpLocator::flagForCountryCode('gb'));
        self::assertSame('', GeoIpLocator::flagForCountryCode('invalid'));
    }

    public function testAuditPersistenceAndViewsExposeIpAndLocation(): void
    {
        $root = dirname(__DIR__, 2);
        $audit = (string) file_get_contents($root . '/src/Infrastructure/Persistence/AuditRepository.php');
        $activity = (string) file_get_contents($root . '/resources/views/partials/admin/activity.html');
        $composer = (string) file_get_contents($root . '/composer.json');

        self::assertStringContainsString('ClientFingerprint::ipAddress()', $audit);
        self::assertStringNotContainsString('ip_hash', $audit);
        self::assertStringContainsString('@event.ip_address', $activity);
        self::assertStringContainsString('@event.geo_location', $activity);
        self::assertStringContainsString('geocoder-php/geoip2-provider', $composer);
    }
}