<?php

/*
Generated by: Claude Code CLI

Date time: 2026/10/06 SAST

Version: 0.8.8.7

Description:
Configuration is .env, read with phpdotenv's rules. PHP's INI parser is not a .env reader: it treats
# lines as data, so an ordinary comment with a bracket made the whole file unreadable and the front
controller could not find the code root. This fails the build if anything in src/, public_html/,
tools/ or bin/ calls parse_ini_file() or parse_ini_string(). Calls are found with PHP's tokenizer, so
a comment that names the functions (as the front controller's does) is not a call.

Architectural boundary: unit. It reads source files only.

Changelog:
2026/10/06 SAST
- Created after the front controller's parse_ini_file() broke a VPS installation.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use PHPUnit\Framework\TestCase;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;

final class IniParserContractTest extends TestCase
{
    private const BANNED = ['parse_ini_file', 'parse_ini_string'];

    public function testNothingCallsTheIniParser(): void
    {
        $root = dirname(__DIR__, 2);
        $calls = [];
        $scanned = 0;
        foreach (['src', 'public_html', 'tools', 'bin'] as $directory) {
            foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root . '/' . $directory, RecursiveDirectoryIterator::SKIP_DOTS)) as $file) {
                $path = (string) $file;
                if (!self::isPhp($path)) {
                    continue;
                }
                $scanned++;
                foreach (self::callsIn((string) file_get_contents($path)) as $line => $function) {
                    $calls[] = substr($path, strlen($root) + 1) . ':' . $line . ' calls ' . $function . '()';
                }
            }
        }
        self::assertGreaterThan(100, $scanned, 'The scan reached the source tree.');
        self::assertSame([], $calls, 'Read configuration with phpdotenv rules, never with the INI parser.');
    }

    public function testTheScanFindsACallButNotAComment(): void
    {
        self::assertSame([2 => 'parse_ini_file'], self::callsIn("<?php\n\$x = parse_ini_file('a');\n// parse_ini_string(\$y) in a comment\n"));
        self::assertSame([1 => 'parse_ini_string'], self::callsIn("<?php \\parse_ini_string(\$y);"));
        self::assertSame([], self::callsIn("<?php \$object->parse_ini_file(); /* parse_ini_file() */"));
    }

    /** PHP sources: *.php, and extensionless scripts such as bin/console that open with PHP. */
    private static function isPhp(string $path): bool
    {
        if (str_ends_with($path, '.php')) {
            return true;
        }
        if (pathinfo($path, PATHINFO_EXTENSION) !== '') {
            return false;
        }
        $head = (string) @file_get_contents($path, false, null, 0, 64);
        return str_starts_with($head, '<?php') || (str_starts_with($head, '#!') && str_contains($head, '<?php'));
    }

    /** @return array<int,string> line => banned function called there */
    private static function callsIn(string $source): array
    {
        $tokens = array_values(array_filter(token_get_all($source), static fn(mixed $token): bool => !is_array($token) || !in_array($token[0], [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true)));
        $calls = [];
        foreach ($tokens as $index => $token) {
            if (!is_array($token) || !in_array($token[0], [T_STRING, T_NAME_FULLY_QUALIFIED], true)) {
                continue;
            }
            $name = strtolower(ltrim($token[1], '\\'));
            $previous = $tokens[$index - 1] ?? null;
            $next = $tokens[$index + 1] ?? null;
            $isMethod = is_array($previous) && in_array($previous[0], [T_OBJECT_OPERATOR, T_NULLSAFE_OBJECT_OPERATOR, T_DOUBLE_COLON, T_FUNCTION], true);
            if (in_array($name, self::BANNED, true) && $next === '(' && !$isMethod) {
                $calls[$token[2]] = $name;
            }
        }
        return $calls;
    }
}
