<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/07 16:00 SAST

Version: 0.6

Description:
Every screen carries the same page header, and the header's parameters are written in a form the
template engine can actually compile.

Two separate contracts, both learned the hard way while rolling the header out.

The first is coverage. A reader has to find the same four answers - where am I, what is this page
called, what is it for, how do I get back - in the same place on every screen. Seventeen pages had no
header at all, and nothing said so; the ones that did have one had each written their own markup, so
the answers moved from page to page.

The second is the shape of a set attribute, which is where three separate defects came from in one
sitting:

  - F3 splits an include's `with` attribute on every comma, quoted or not, so a lead containing a
    comma silently became two broken parameters. That is why the parameters are set tags and not
    `with` values.
  - A set attribute is evaluated as ONE expression, not as interpolated text. Mixing literal words
    with template tokens compiles to a PHP syntax error and takes the whole page down, so a mixed
    value has to be written as a concatenation.
  - A value must have balanced tokens. An unbalanced one is a parse error rather than a wrong
    string, so it fails at render and never at review.

None of the three is visible by reading the markup, which is exactly why they are asserted.

Changelog:
2026/09/07 16:00 SAST
- Created with the shared page header.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use PHPUnit\Framework\TestCase;

final class PageHeadContractTest extends TestCase
{
    /**
     * Screens that deliberately carry no platform header.
     *
     * The home page is its own hero and a header above it would be a second title. The course
     * player and the assessment runner carry their own chrome - a course has its own name, progress
     * and navigation, and a platform header above that competes with the thing the reader came for.
     * The error page has no context to describe, and the catalogue and course detail are heroes in
     * their own right.
     *
     * @var array<string,string>
     */
    private const WITHOUT_HEADER = [
        'home.html' => 'Its own hero; a header would be a second title.',
        'error.html' => 'No context to describe.',
        'course-detail.html' => 'The course is the hero.',
        'learn-module.html' => 'Carries its own course toolbar, which is the compact header.',
        'assessment-question.html' => 'One question, full width, nothing else on screen.',
    ];

    /**
     * Every page template.
     *
     * The emptiness check is not defensive noise. Three of the assertions below iterate this list
     * and pass trivially when it is empty, and an empty list is exactly what a wrong root produces -
     * so without this the whole class reports success while inspecting nothing.
     *
     * @return list<string>
     */
    private static function pages(): array
    {
        $paths = glob(dirname(__DIR__, 2) . '/resources/views/pages/*.html') ?: [];
        self::assertNotSame([], $paths, 'No page templates were found, so these tests prove nothing.');

        return $paths;
    }

    public function testEveryPageCarriesTheSharedHeader(): void
    {
        $missing = [];

        foreach (self::pages() as $path) {
            $name = basename($path);
            $markup = (string) file_get_contents($path);
            $has = str_contains($markup, 'partials/page-head.html');

            if (isset(self::WITHOUT_HEADER[$name])) {
                self::assertFalse(
                    $has,
                    $name . ' is listed as headerless but includes the header. Remove it from the list '
                    . 'rather than leaving the list wrong.'
                );
                continue;
            }
            if (!$has) {
                $missing[] = $name;
            }
        }

        self::assertSame(
            [],
            $missing,
            "These screens have no page header, so a reader arriving on one cannot tell where they "
            . "are:\n  " . implode("\n  ", $missing)
        );
    }

    /** No screen may hand-roll the header markup beside the shared one. */
    public function testNoPageWritesItsOwnHeaderMarkup(): void
    {
        $offenders = [];

        foreach (self::pages() as $path) {
            $markup = (string) file_get_contents($path);
            if (str_contains($markup, '<section class="cl-page-head"')) {
                $offenders[] = basename($path);
            }
        }

        self::assertSame([], $offenders, 'The header is a shared partial, not markup to copy.');
    }

    /**
     * Every header parameter compiles.
     *
     * A set attribute is one expression. Literal text mixed with a template token is a PHP syntax
     * error at render, and unbalanced tokens are the same.
     */
    public function testHeaderParametersAreSingleCompilableExpressions(): void
    {
        $offenders = [];

        foreach (array_merge(self::pages(), glob(dirname(__DIR__, 2) . '/resources/views/partials/*.html') ?: []) as $path) {
            $markup = (string) file_get_contents($path);
            if (preg_match('/<set ph_[^>]*\/>/', $markup, $block) !== 1) {
                continue;
            }

            preg_match_all('/(ph_[a-z_]+)="([^"]*)"/', $block[0], $attributes, PREG_SET_ORDER);
            foreach ($attributes as [, $key, $value]) {
                if (!str_contains($value, '{{')) {
                    continue;
                }
                if (substr_count($value, '{{') !== substr_count($value, '}}')) {
                    $offenders[] = basename($path) . ' ' . $key . ': unbalanced tokens';
                    continue;
                }
                // One token spanning the whole value, or nothing but tokens.
                if (preg_match('/^\{\{.*\}\}$/s', trim($value)) !== 1 || substr_count($value, '{{') > 1) {
                    $offenders[] = basename($path) . ' ' . $key . ': literal text mixed with a token';
                }
            }
        }

        self::assertSame(
            [],
            $offenders,
            "A set attribute is one expression, not interpolated text. Write a mixed value as a "
            . "concatenation:\n  " . implode("\n  ", $offenders)
        );
    }

    /** The parameters never travel on an include's with attribute, which splits them on commas. */
    public function testHeaderParametersAreNeverPassedOnAnIncludeWith(): void
    {
        $offenders = [];

        foreach (array_merge(self::pages(), glob(dirname(__DIR__, 2) . '/resources/views/partials/*.html') ?: []) as $path) {
            $markup = (string) file_get_contents($path);
            if (preg_match('/page-head\.html" with=/', $markup) === 1) {
                $offenders[] = basename($path);
            }
        }

        self::assertSame(
            [],
            $offenders,
            'F3 splits a with attribute on every comma, quoted or not, so a lead containing one '
            . 'silently becomes two broken parameters.'
        );
    }

    /**
     * No screen carries two headings for itself.
     *
     * Adding the shared header to pages that already had their own produced eleven screens with the
     * title twice - which is worse than the inconsistency it was meant to fix, because it reads as a
     * rendering fault rather than as a style. A page's own h1 is allowed only where the h1 belongs to
     * the artefact rather than to the page: a certificate, a module being previewed, a role name that
     * *is* the heading.
     */
    public function testNoPageCarriesTwoHeadings(): void
    {
        $offenders = [];

        foreach (self::pages() as $path) {
            $name = basename($path);
            $markup = (string) file_get_contents($path);
            if (!str_contains($markup, 'partials/page-head.html')) {
                continue;
            }

            $own = preg_match_all('/<h1[\s>]/', $markup);
            if ($own === 0) {
                continue;
            }
            // The compact header exists precisely for a screen whose own artefact carries the title.
            if (str_contains($markup, 'ph_compact=')) {
                continue;
            }
            $offenders[] = $name;
        }

        self::assertSame(
            [],
            $offenders,
            "These screens print their title twice - once in the shared header and once in their own "
            . "markup:\n  " . implode("\n  ", $offenders)
        );
    }

}
