<?php

/*
Generated by: ChatGPT

Date time: 2026/08/17 04:00 SAST

Version: 0.5.7.5.1

Description:
Protects the HTTP route table by verifying every declared Catto Learning route resolves to a real controller method, route signatures remain unique, and high-value public/authenticated/administration entry points remain registered.

Changelog:
2026/08/17 23:56 SAST
- Added coverage for the stable /account entry route.
2026/08/17 04:00 SAST
- Added route-table smoke coverage after the native F3/PHP-DI routing migration.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use PHPUnit\Framework\TestCase;

final class RouteSmokeContractTest extends TestCase
{
    public function testEveryDeclaredRouteTargetsARealControllerMethodAndIsUnique(): void
    {
        $source = (string) file_get_contents(__DIR__ . '/../../src/Application/App.php');
        preg_match_all('/use\s+([^;]+);/', $source, $useMatches);
        $imports = [];
        foreach ($useMatches[1] ?? [] as $fqcn) {
            $fqcn = trim((string) $fqcn);
            $imports[basename(str_replace('\\', '/', $fqcn))] = $fqcn;
        }

        preg_match_all(
            "/\\\$routes->add\\('([^']+)',\\s*([A-Za-z0-9_]+)::class,\\s*'([^']+)'\\);/",
            $source,
            $matches,
            PREG_SET_ORDER
        );
        self::assertGreaterThanOrEqual(139, count($matches), 'The application route table unexpectedly shrank.');

        $signatures = [];
        foreach ($matches as $match) {
            $route = (string) $match[1];
            $shortClass = (string) $match[2];
            $method = (string) $match[3];
            self::assertArrayHasKey($shortClass, $imports, 'Controller import missing for ' . $shortClass . '.');
            $class = $imports[$shortClass];
            self::assertTrue(class_exists($class), 'Controller class does not autoload: ' . $class);
            self::assertTrue(method_exists($class, $method), $route . ' targets missing method ' . $class . '::' . $method . '().');
            self::assertArrayNotHasKey($route, $signatures, 'Duplicate HTTP route signature: ' . $route);
            $signatures[$route] = $class . '::' . $method;
        }

        foreach ([
            'GET /' => 'HomeController::index',
            'GET /courses' => 'CourseController::catalogue',
            'GET /login' => 'AuthController::loginForm',
            'GET /account/library' => 'AccountController::learning',
            'GET /account' => 'AccountController::index',
            'GET /account/profile' => 'AccountController::profile',
            'GET /company' => 'CompanyController::index',
            'GET /admin' => 'AdminController::index',
            'GET /admin/dashboard' => 'AdminController::dashboard',
            'GET /admin/people' => 'AdminController::people',
            'GET /admin/companies' => 'AdminController::companies',
            'GET /admin/enrolments' => 'AdminController::enrolments',
            'GET /admin/credits' => 'AdminController::credits',
            'GET /admin/activity' => 'AdminController::activity',
            'GET /admin/reports' => 'AdminController::reports',
            'GET /admin/themes' => 'AdminController::themes',
            'GET /admin/roles' => 'AdminController::roles',
            'GET /admin/settings' => 'AdminController::settings',
            'GET /admin/courses' => 'AdminCourseController::index',
            'POST /admin/themes/activate' => 'AdminController::activateTheme',
            'POST /admin/themes/resync' => 'AdminController::resyncThemes',
        ] as $route => $expectedTarget) {
            self::assertArrayHasKey($route, $signatures);
            self::assertStringEndsWith($expectedTarget, str_replace('CattoLearning\\Http\\Controller\\', '', $signatures[$route]));
        }
    }
}