<?php

/*
Generated by: Claude Code CLI

Date time: 2026/08/25 05:10 SAST

Version: 0.5.8.2

Description:
Freezes the Seed Database table policy recorded in owner decisions D3 and D4.

This catalogue is a security boundary, not a convenience list. Adding a table to it widens what
the generator may write; adding a column to the actor allowlist widens what may legitimately
cross the REAL/SEED boundary. Both are asserted here exactly, so neither can be extended by
accident or in passing.

The catalogue is also checked against the real baseline schema, because a declaration that names
a column the database does not have would silently produce a trigger that never fires.

Changelog:

2026/08/25 05:10 SAST

- Removed two collateral checks superseded by SeedSchemaContractTest, which proves the same property against the complete foreign-key inventory rather than the guarded subset.

2026/08/25 03:40 SAST

- Pinned the collateral model against the schema, so the cleanup exemption list cannot drift from the baseline ON DELETE clauses.
2026/08/23 04:19 SAST
- Created for the v0.5.8 Seed Database phase.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use CattoLearning\Seed\SeedTableCatalog;
use PHPUnit\Framework\TestCase;
use RuntimeException;

final class SeedCatalogContractTest extends TestCase
{
    /** The single baseline migration, discovered rather than named. */
    private static function baselineMigration(): string
    {
        $matches = glob(dirname(__DIR__, 2) . '/database/migrations/*_baseline.php') ?: [];
        if (count($matches) !== 1) {
            throw new RuntimeException('Expected exactly one baseline migration, found ' . count($matches) . '.');
        }

        return (string) file_get_contents($matches[0]);
    }

    /** @return array<string,string> table => the body of its CREATE TABLE statement */
    private static function tableBodies(): array
    {
        preg_match_all('/CREATE TABLE (\w+)\s*\((.*?)\n\);/s', self::baselineMigration(), $matches, PREG_SET_ORDER);
        $bodies = [];
        foreach ($matches as $match) {
            $bodies[$match[1]] = $match[2];
        }

        return $bodies;
    }

    /** Decision D3 froze this list, amended to 30 tables in v0.6. */
    /**
     * The frozen inventory, thirty tables since v0.6.
     *
     * `course_categories` left it, and `tags` and `course_tags` were never in it: a category and a
     * tag classify a course rather than describing a person, a company or a transaction, so they
     * are labels shared by both universes exactly as roles and permissions already are. The full
     * reasoning, and the amendment to owner decision D3, is recorded in SeedTableCatalog.
     */
    public function testSeedAwareTableListIsFrozen(): void
    {
        self::assertSame([
            'users', 'user_emails', 'user_roles', 'auth_sessions',
            'companies', 'company_users',
            'courses', 'course_price_variants', 'course_modules',
            'course_content_blocks', 'course_assessments', 'assessment_questions',
            'assessment_options', 'course_grade_bands', 'course_media', 'course_editors',
            'course_enrolments', 'module_progress', 'assessment_attempts', 'assessment_responses',
            'assessment_sessions', 'assessment_session_questions', 'course_results', 'certificates',
            'course_favourites', 'course_requests', 'course_credits', 'course_credit_allocations',
            'course_edit_history', 'audit_log',
        ], SeedTableCatalog::seedAwareTables());

        self::assertCount(30, SeedTableCatalog::seedAwareTables());
    }

    /** The two changes decision D3 made to the original proposal, asserted individually. */
    public function testDecisionD3ExclusionAndInclusion(): void
    {
        self::assertFalse(
            SeedTableCatalog::isSeedAware('web_sessions'),
            'web_sessions is ephemeral session-handler storage and must never carry seed provenance.'
        );
        self::assertArrayHasKey('web_sessions', SeedTableCatalog::nonSeedAwareTables());

        self::assertTrue(
            SeedTableCatalog::isSeedAware('course_media'),
            'course_media is seed-aware so a SEED course may hold genuine uploaded test media.'
        );
    }

    /** Platform configuration is shared by both universes and must stay untagged. */
    public function testPlatformConfigurationIsNeverSeedAware(): void
    {
        foreach (['roles', 'permissions', 'role_permissions', 'app_options', 'theme_registry', 'api_tokens', 'auth_login_tokens'] as $table) {
            self::assertArrayHasKey($table, SeedTableCatalog::nonSeedAwareTables());
            self::assertFalse(SeedTableCatalog::isSeedAware($table), $table . ' must not be seed-aware.');
        }
    }

    /**
     * The complete decision D4 allowlist, asserted exactly.
     *
     * Every entry here is a column where a SEED row may point at a genuine REAL ADMIN for
     * accountability. Widening this array widens the only sanctioned hole in the universe
     * boundary, so it is spelled out rather than pattern-matched.
     */
    public function testActorAllowlistIsExact(): void
    {
        self::assertSame([
            'audit_log' => ['user_id'],
            'companies' => ['created_by_user_id'],
            'courses' => ['created_by_user_id', 'updated_by_user_id'],
            'course_price_variants' => ['created_by_user_id', 'updated_by_user_id'],
            'course_media' => ['created_by_user_id'],
            'course_edit_history' => ['user_id'],
            'course_editors' => ['assigned_by_user_id'],
            'course_enrolments' => ['assigned_by_user_id', 'access_removed_by_user_id'],
            'course_requests' => ['decided_by_user_id'],
            'course_credits' => ['created_by_user_id'],
            'course_credit_allocations' => ['assigned_by_user_id'],
            // Amendment, owner's instruction 2026/09/09: a genuine immutable ADMIN straddles both
            // universes and may bookmark a generated course. Deliberately this column only - a
            // favourite grants nothing and cascades away with the seed set, so it cannot outlive
            // the data it points at. See SeedTableCatalog for the full record.
            'course_favourites' => ['user_id'],
        ], SeedTableCatalog::actorAllowlist());
    }

    /**
     * Decision D4 point 5: subject and business columns never qualify for the exception.
     *
     * These are the ones most likely to be added by mistake, because they are also user
     * references and look superficially similar to the actor columns above.
     */
    /**
     * The one column the 2026/09/09 amendment moved, and the reason it is safe to have moved it.
     *
     * A favourite is a bookmark. It grants no access, carries no entitlement, and the row takes
     * its universe from the course, so it is deleted with the seed set that owns that course. A
     * REAL administrator holding one therefore leaves nothing behind. That is what separates it
     * from every entry in the test above, each of which would outlive the generated data or confer
     * something on the identity holding it.
     */
    public function testAFavouriteMayNameARealAdministratorButStillBelongsToTheCourse(): void
    {
        self::assertTrue(SeedTableCatalog::isActorColumn('course_favourites', 'user_id'));

        // The course reference keeps its guard: the favourite is still the course's universe.
        $guarded = SeedTableCatalog::sameUniverseReferences()['course_favourites'] ?? [];
        self::assertSame(['course_id' => 'courses'], $guarded, 'A favourite must still take the universe of its course.');
    }

    public function testSubjectColumnsAreNeverTreatedAsActorColumns(): void
    {
        foreach ([
            ['courses', 'owner_user_id'],
            ['course_enrolments', 'user_id'],
            ['company_users', 'user_id'],
            ['course_editors', 'user_id'],
            ['course_requests', 'user_id'],
            ['course_credits', 'user_id'],
            ['course_credit_allocations', 'user_id'],
            ['user_emails', 'user_id'],
            ['user_roles', 'user_id'],
            ['auth_sessions', 'user_id'],
        ] as [$table, $column]) {
            self::assertFalse(
                SeedTableCatalog::isActorColumn($table, $column),
                $table . '.' . $column . ' is a business relationship, not administrative attribution.'
            );
        }
    }

    /** A column cannot be both guarded and exempt; that would make the guard meaningless. */
    public function testNoColumnIsBothGuardedAndAllowlisted(): void
    {
        foreach (SeedTableCatalog::actorAllowlist() as $table => $columns) {
            foreach ($columns as $column) {
                self::assertArrayNotHasKey(
                    $column,
                    SeedTableCatalog::sameUniverseReferences()[$table] ?? [],
                    $table . '.' . $column . ' cannot be both same-universe guarded and actor-allowlisted.'
                );
            }
        }
    }

    /** Every guarded reference must point at another seed-aware table. */
    public function testGuardedReferencesTargetSeedAwareTables(): void
    {
        foreach (SeedTableCatalog::sameUniverseConstraints() as $constraint) {
            self::assertTrue(
                SeedTableCatalog::isSeedAware($constraint['references']),
                $constraint['table'] . '.' . $constraint['column'] . ' references '
                . $constraint['references'] . ', which carries no seed_token to compare against.'
            );
        }
    }

    /**
     * The declaration must describe the database that actually exists.
     *
     * A catalogue naming a column the schema does not have produces a trigger argument that
     * silently matches nothing, which is the worst kind of failure: the guard appears present.
     */
    public function testCatalogueMatchesTheBaselineSchema(): void
    {
        $bodies = self::tableBodies();

        foreach (SeedTableCatalog::seedAwareTables() as $table) {
            self::assertArrayHasKey($table, $bodies, 'Seed-aware table ' . $table . ' is not in the baseline.');
        }
        foreach (array_keys(SeedTableCatalog::nonSeedAwareTables()) as $table) {
            self::assertArrayHasKey($table, $bodies, 'Non-seed-aware table ' . $table . ' is not in the baseline.');
        }

        foreach (SeedTableCatalog::sameUniverseConstraints() as $constraint) {
            self::assertMatchesRegularExpression(
                '/^\s+' . preg_quote($constraint['column'], '/') . '\s/m',
                $bodies[$constraint['table']] ?? '',
                $constraint['table'] . '.' . $constraint['column'] . ' does not exist in the baseline.'
            );
        }

        foreach (SeedTableCatalog::actorAllowlist() as $table => $columns) {
            foreach ($columns as $column) {
                self::assertMatchesRegularExpression(
                    '/^\s+' . preg_quote($column, '/') . '\s/m',
                    $bodies[$table] ?? '',
                    $table . '.' . $column . ' does not exist in the baseline.'
                );
            }
        }
    }

    /** Cleanup must be the exact reverse of generation, or it deletes parents before children. */
    public function testCleanupOrderReversesGenerationOrder(): void
    {
        self::assertSame(
            array_reverse(SeedTableCatalog::generationOrder()),
            SeedTableCatalog::cleanupOrder()
        );
    }

    /** Decision D3: the generator fabricates neither media rows nor sessions. */
    public function testGeneratorMayNotFabricateMediaOrSessions(): void
    {
        $generated = SeedTableCatalog::generatorTables();

        self::assertNotContains('course_media', $generated);
        self::assertNotContains('auth_sessions', $generated);
        self::assertContains('users', $generated);
        self::assertContains('courses', $generated);

        foreach (array_keys(SeedTableCatalog::generatorExclusions()) as $table) {
            self::assertTrue(
                SeedTableCatalog::isSeedAware($table),
                'An excluded table is still seed-aware; it is only the generator that may not write it.'
            );
        }
    }

    /** The infrastructure token must be a well-formed UUID that no generator can produce. */
    public function testInfrastructureTokenIsAReservedUuid(): void
    {
        self::assertMatchesRegularExpression(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/',
            SeedTableCatalog::INFRASTRUCTURE_TOKEN
        );
        self::assertStringStartsWith('00000000-0000-', SeedTableCatalog::INFRASTRUCTURE_TOKEN);
    }

    /**
     * Every collateral reference names a seed-aware table on both sides.
     *
     * A plan can only follow an edge if both ends carry a token; an edge into a table with no
     * seed_token would silently never match.
     */
    public function testEveryCollateralReferenceIsSeedAwareOnBothSides(): void
    {
        $offenders = [];
        foreach (SeedTableCatalog::collateralReferences() as $reference) {
            foreach (['child', 'parent'] as $side) {
                if (!SeedTableCatalog::isSeedAware($reference[$side])) {
                    $offenders[] = $reference['child'] . '.' . $reference['column'] . ' -> ' . $reference[$side];
                }
            }
        }

        self::assertSame([], array_unique($offenders));
    }


}
