<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/10 02:25 SAST

Version: 0.7

Description:
The slanted texture is a named platform element, defined once and available to every theme.

The owner's definition, 2026/09/10: "bands that slant at 45 degrees from top left to bottom right.
It has two bands rows each about 10px thick, alternating in colour, light grey with a darker grey."

It began as one theme's stage canvas. Named, it becomes core's, and the point of naming it is that
the next theme does not write its own gradient at its own angle and call it the same thing. So this
asserts the definition is still core's and still says what the owner said: the angle, the two bands,
the thickness, and the three custom properties a theme re-colours it through rather than replacing
it.

The properties matter as much as the gradient. A theme that needs a darker texture sets
--cl-texture-dark; a theme that writes `background: repeating-linear-gradient(...)` of its own has
forked the element, and the platform then has two textures wearing one name.

Architectural boundary: unit. It reads the core stylesheet and touches nothing else.

Changelog:
2026/09/10 02:25 SAST
- Created when the slanted texture became a named element.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use PHPUnit\Framework\TestCase;

final class SlantedTextureContractTest extends TestCase
{
    private const CORE_CSS = __DIR__ . '/../../public_html/css/catto-platform.css';

    public function testCoreDefinesTheTextureTheOwnerDescribed(): void
    {
        $css = self::stylesheet();

        foreach ([
            '--cl-texture-light:' => 'the lighter of the two bands',
            '--cl-texture-dark:' => 'the darker of the two bands',
            '--cl-texture-band:10px' => 'bands about 10px thick',
            '--cl-texture-angle:45deg' => 'slanting at 45 degrees from top left to bottom right',
            '.cl-slanted-texture' => 'the named class itself',
        ] as $token => $what) {
            self::assertStringContainsString(
                $token,
                $css,
                'Core no longer states ' . $what . ' (' . $token . '), so the slanted texture is not defined.'
            );
        }

        // Two bands, alternating, drawn from the properties rather than from literals - which is
        // what makes it re-colourable by a theme instead of only re-writable.
        self::assertMatchesRegularExpression(
            '/repeating-linear-gradient\(var\(--cl-texture-angle\),\s*var\(--cl-texture-dark\)\s*0\s*var\(--cl-texture-band\),\s*var\(--cl-texture-light\)\s*var\(--cl-texture-band\)\s*calc\(var\(--cl-texture-band\)\s*\*\s*2\)\)/',
            $css,
            'The texture must be two alternating bands built from the custom properties.'
        );
    }

    public function testTheTextureIsAvailableWithoutATheme(): void
    {
        // Availability is the whole reason it moved into core: a theme should have to set three
        // colours at most, never redefine the element. If the class only existed in a theme
        // stylesheet, "available in all themes" would mean five copies to keep in step.
        $css = self::stylesheet();

        $bare = (int) preg_match('/(^|})\s*:root\s*\{[^}]*--cl-texture-angle/', $css);
        self::assertSame(
            1,
            $bare,
            'The texture properties must be declared on a bare :root, or a theme that sets none of '
            . 'them gets no texture at all.'
        );
    }

    private static function stylesheet(): string
    {
        // Comments are stripped first. A guard that matches its own explanatory comment passes
        // while the rule it protects is gone, which has happened in this codebase twice.
        $css = (string) file_get_contents(self::CORE_CSS);

        return (string) preg_replace('#/\*.*?\*/#s', '', $css);
    }
}
