<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/10 02:25 SAST

Version: 0.7

Description:
A social profile link is an anchor other people click, so what goes in the field matters.

The owner's list, 2026/09/10, is twelve platforms. A field that accepted any URL would eventually
hold somebody else's, rendered from this platform's pages under this platform's name - so an address
must be https and must be on the platform it claims to be on.

The near-miss host is the case worth writing down: "notlinkedin.com" ends with "linkedin.com" as a
string and is a different company. Matching has to be the host itself or a subdomain of it, and this
asserts both halves.

Architectural boundary: unit. It exercises a value object and touches nothing else.

Changelog:
2026/09/10 02:25 SAST
- Created with the Profile submenu's social media page.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use CattoLearning\Support\SocialPlatform;
use PHPUnit\Framework\TestCase;
use RuntimeException;

final class SocialPlatformTest extends TestCase
{
    public function testTheCatalogueIsTheTwelvePlatformsTheOwnerNamed(): void
    {
        self::assertSame(
            ['linkedin','youtube','github','google','facebook','instagram','x','threads','tiktok','whatsapp','telegram','signal'],
            SocialPlatform::keys(),
            'The platforms and their order are the owner\'s, 2026/09/10, and the form renders them in this order.'
        );
    }

    public function testAnAddressOnThePlatformIsKept(): void
    {
        foreach ([
            ['linkedin', 'https://www.linkedin.com/in/someone'],
            ['github', 'https://github.com/someone'],
            ['x', 'https://x.com/someone'],
            ['x', 'https://twitter.com/someone'],
            ['youtube', 'https://youtu.be/abcdefg'],
            ['whatsapp', 'https://wa.me/27820000000'],
            ['telegram', 'https://t.me/someone'],
        ] as [$platform, $url]) {
            self::assertSame($url, SocialPlatform::normalise($platform, $url), $url . ' is a valid ' . $platform . ' address.');
        }
    }

    public function testAnEmptyValueMeansRemoveTheLink(): void
    {
        // Not an error. The form has one field per platform and no delete control, so clearing the
        // field is the only way to say "I do not have one of these".
        self::assertNull(SocialPlatform::normalise('linkedin', ''));
        self::assertNull(SocialPlatform::normalise('linkedin', '   '));
    }

    public function testAHostThatMerelyEndsWithThePlatformIsRefused(): void
    {
        $this->expectException(RuntimeException::class);
        SocialPlatform::normalise('linkedin', 'https://notlinkedin.com/in/someone');
    }

    public function testASubdomainOfThePlatformIsAccepted(): void
    {
        self::assertSame(
            'https://za.linkedin.com/in/someone',
            SocialPlatform::normalise('linkedin', 'https://za.linkedin.com/in/someone')
        );
    }

    public function testAnotherSitesAddressIsRefused(): void
    {
        $this->expectException(RuntimeException::class);
        SocialPlatform::normalise('linkedin', 'https://evil.example.com/in/someone');
    }

    public function testPlainHttpIsRefused(): void
    {
        // Following a stored http link would downgrade every visitor who clicks it.
        $this->expectException(RuntimeException::class);
        SocialPlatform::normalise('linkedin', 'http://www.linkedin.com/in/someone');
    }

    public function testSomethingThatIsNotAUrlIsRefused(): void
    {
        $this->expectException(RuntimeException::class);
        SocialPlatform::normalise('linkedin', 'linkedin.com/in/someone');
    }

    public function testTheFormModelCarriesEveryPlatformWhateverIsStored(): void
    {
        $form = SocialPlatform::form(['github' => 'https://github.com/someone']);

        self::assertCount(12, $form, 'Every platform is offered, whether or not the person has filled it in.');
        $byKey = array_column($form, 'url', 'key');
        self::assertSame('https://github.com/someone', $byKey['github']);
        self::assertSame('', $byKey['linkedin'], 'A platform with nothing stored renders an empty field, not a missing one.');
    }
}
