<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/08 10:00 SAST

Version: 0.6

Description:
A table row is one line, it fits, and nothing in it stacks.

This exists because the rule was written once, asserted nowhere, and was wrong on every screen. Core
said `.cl-ui-row-actions{flex-wrap:nowrap}` at specificity (0,1,0); every theme says
`.gn-main .cl-ui-row-actions{flex-wrap:wrap}` at (0,2,0) and loads afterwards. The core rule lost on every
page, the buttons stacked anyway, and the passing build said nothing - because nothing was asked.

Three separate failures produced the same symptom and each is checked separately:

  - a theme overriding the core rule, which is why core now says it with !important;
  - a cell laying its content out with a container core never sees, such as a hand-written
    `d-flex flex-wrap` instead of `.cl-ui-row-actions`;
  - a table using a wrapper class core does not style, such as Bootstrap's `table-responsive`, so
    none of the rules reach it at all.

Changelog:
2026/09/08 10:00 SAST
- Created after the one-row rule shipped broken on every screen.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use PHPUnit\Framework\TestCase;

final class TableRowContractTest extends TestCase
{
    private static function root(): string
    {
        return dirname(__DIR__, 2);
    }

    private static function css(): string
    {
        return (string) file_get_contents(self::root() . '/public_html/css/catto-platform.css');
    }

    /** @return list<string> */
    private static function views(): array
    {
        $paths = array_merge(
            glob(self::root() . '/resources/views/partials/**/*.html.twig') ?: [],
            glob(self::root() . '/resources/views/partials/*.html.twig') ?: [],
            glob(self::root() . '/resources/views/pages/*.html.twig') ?: []
        );
        self::assertNotSame([], $paths, 'No templates were found, so these tests prove nothing.');

        return $paths;
    }

    /**
     * The core rules are stated so a theme cannot quietly undo them.
     *
     * Not a style preference. Themes load after core and every one of them sets its own row-action
     * layout at a higher specificity, so without this the rule is decorative.
     */
    public function testTheOneRowRulesOutrankTheThemes(): void
    {
        $css = self::css();

        foreach ([
            'white-space:nowrap!important',
            'flex-wrap:nowrap!important',
            // Fixed layout is what actually stops the table outgrowing its box. It replaced
            // `overflow-x:hidden` on the wrapper, which stopped the scrollbar and clipped the row
            // menu with it - the menu opened outside the wrapper and was simply not drawn, which is
            // why pressing it appeared to do nothing.
            'table-layout:fixed!important',
        ] as $token) {
            self::assertStringContainsString($token, $css, 'A theme will override this without it: ' . $token);
        }

        // And the wrapper must not reintroduce the scrollbar the fixed layout removes the need for.
        // !important, because the theme loads after core and declares `.gn-main .cl-ui-table
        // {overflow:auto}` at higher specificity. Without it the wrapper clips and the row menu -
        // absolutely positioned, and required to escape its cell - is never drawn.
        self::assertStringContainsString('.cl-ui-table{width:100%;overflow:visible!important}', $css);

        // Truncation is what makes "no wrapping and no scrolling" possible at all: content wider
        // than its column has to be shortened, because the other two options are the ones banned.
        self::assertStringContainsString('text-overflow:ellipsis', $css);
    }

    /** No table row lays its actions out with a container core does not control. */
    public function testNoTableRowWrapsItsOwnActions(): void
    {
        $offenders = [];

        foreach (self::views() as $path) {
            $markup = (string) file_get_contents($path);
            foreach (self::rowsOf($markup) as $row) {
                if (preg_match('/class="[^"]*\bflex-wrap\b/', $row) === 1) {
                    $offenders[] = basename($path);
                }
            }
        }

        self::assertSame(
            [],
            array_values(array_unique($offenders)),
            "A table row must lay its actions out with .cl-ui-row-actions, which core keeps on one line:\n  "
            . implode("\n  ", array_unique($offenders))
        );
    }

    /** Every table uses the wrapper core actually styles. */
    public function testEveryTableUsesTheCoreWrapper(): void
    {
        $offenders = [];

        foreach (self::views() as $path) {
            $markup = (string) file_get_contents($path);
            if (str_contains($markup, 'table-responsive')) {
                $offenders[] = basename($path);
            }
        }

        self::assertSame(
            [],
            array_values(array_unique($offenders)),
            'table-responsive is a Bootstrap class core never styles, so none of the one-row rules '
            . "reach a table wrapped in it:\n  " . implode("\n  ", array_unique($offenders))
        );
    }

    public function testRowScannerActuallyChecksMigratedTables(): void
    {
        $count = 0;
        foreach (self::views() as $path) $count += count(self::rowsOf((string) file_get_contents($path)));
        self::assertGreaterThan(50, $count);
    }

    /** @return list<string> */
    private static function rowsOf(string $markup): array
    {
        preg_match_all('/<tr\b.*?<\/tr>/s', $markup, $rows);

        return $rows[0];
    }

    /**
     * Every truncated cell can still be read.
     *
     * One row is one line, so a cell wider than its column is cut off with an ellipsis. That is the
     * right visual answer and, on its own, the wrong informational one: the reader can see that
     * something was shortened and has no way to find out what. The tooltip is the whole of the
     * recovery, and it is applied to the rendered table rather than written into each template,
     * because whether a cell overflows depends on the column width, the viewport and the content -
     * none of which a template knows. A cell that fits gets no tooltip, so hovering never repeats
     * what is already on screen.
     */
    public function testTruncatedCellsCarryTheirFullTextAsATooltip(): void
    {
        $js = (string) file_get_contents(dirname(__DIR__, 2) . '/public_html/js/platform-overrides.js');

        self::assertStringContainsString('const applyCellTooltips', $js);
        self::assertStringContainsString(".cl-ui-table td, .cl-ui-table th", $js);
        self::assertStringContainsString('cell.scrollWidth > cell.clientWidth', $js);
        // A page turn replaces the rows, so the pass has to run again on what htmx swapped in.
        self::assertStringContainsString("htmx:afterSwap", $js);
        // A tooltip a template set deliberately - the email behind a person's name - outranks this.
        self::assertStringContainsString("cell.hasAttribute('title')", $js);
    }
}
