<?php

/*
Generated by: Claude Code CLI

Date time: 2026/09/09 02:10 SAST

Version: 0.7

Description:
Template notes are written for the next developer and must not be served to the public.

Architectural boundary: contract test. It reads the templates; it renders nothing.

The rule has not changed but the mechanism has, and the new one is better. Under Fat-Free the notes
were HTML comments and the renderer stripped them from every response on the way out - which worked,
and cost a regular expression over the whole of every page, and would have served the lot verbatim
the day someone removed it. A Twig comment is not output at all: it does not survive compilation, so
there is nothing to strip and nothing to forget.

What this asserts is therefore the input rather than the output: no platform template and no bundled
theme template carries an HTML comment. Anything inside a script, style, pre or textarea is left
alone - a comment delimiter inside a script's own string is that script's business.

Changelog:

2026/09/09 02:10 SAST
- Replaced RenderedCommentStrippingTest, whose subject was removed with the Twig port.
*/

declare(strict_types=1);

namespace CattoLearning\Tests\Unit;

use PHPUnit\Framework\TestCase;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;

final class TemplateCommentContractTest extends TestCase
{
    /** @return list<string> */
    private function templates(string $root): array
    {
        if (!is_dir($root)) {
            return [];
        }
        $found = [];
        foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, \FilesystemIterator::SKIP_DOTS)) as $file) {
            if ($file->isFile() && str_ends_with($file->getFilename(), '.twig')) {
                $found[] = $file->getPathname();
            }
        }
        sort($found);

        return $found;
    }

    /** Everything a script, style, pre or textarea holds is that element's business, not ours. */
    private function outsideMarkupIslands(string $source): string
    {
        return (string) preg_replace('#<(script|style|pre|textarea)\b[^>]*>.*?</\1\s*>#is', '', $source);
    }

    public function testNoPlatformTemplateCarriesAnHtmlComment(): void
    {
        $root = dirname(__DIR__, 2) . '/resources/views';
        $templates = $this->templates($root);
        self::assertNotSame([], $templates, 'No platform templates were found to check.');

        foreach ($templates as $path) {
            self::assertStringNotContainsString(
                '<!--',
                $this->outsideMarkupIslands((string) file_get_contents($path)),
                basename($path) . ' carries an HTML comment; template notes go in a Twig comment, which is never served.'
            );
        }
    }

    public function testNoBundledThemeTemplateCarriesAnHtmlComment(): void
    {
        foreach ($this->templates(dirname(__DIR__, 2) . '/themes') as $path) {
            self::assertStringNotContainsString(
                '<!--',
                $this->outsideMarkupIslands((string) file_get_contents($path)),
                $path . ' carries an HTML comment.'
            );
        }
    }

    /** The notes themselves are still there - the point is where they go, not that they went. */
    public function testTheNotesSurvivedAsTwigComments(): void
    {
        $withNotes = 0;
        foreach ($this->templates(dirname(__DIR__, 2) . '/resources/views') as $path) {
            if (str_contains((string) file_get_contents($path), '{#')) {
                $withNotes++;
            }
        }

        self::assertGreaterThan(30, $withNotes, 'The template metadata headers should have survived the port.');
    }
}
